# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import supervisor_pb2 as supervisor__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in supervisor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SupervisorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/Health',
                request_serializer=supervisor__pb2.HealthRequest.SerializeToString,
                response_deserializer=supervisor__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetHostInfo = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/GetHostInfo',
                request_serializer=supervisor__pb2.GetHostInfoRequest.SerializeToString,
                response_deserializer=supervisor__pb2.HostInfo.FromString,
                _registered_method=True)
        self.CreateVm = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/CreateVm',
                request_serializer=supervisor__pb2.CreateVmRequest.SerializeToString,
                response_deserializer=supervisor__pb2.VmInfo.FromString,
                _registered_method=True)
        self.GetVm = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/GetVm',
                request_serializer=supervisor__pb2.GetVmRequest.SerializeToString,
                response_deserializer=supervisor__pb2.VmInfo.FromString,
                _registered_method=True)
        self.GetVmSpec = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/GetVmSpec',
                request_serializer=supervisor__pb2.GetVmSpecRequest.SerializeToString,
                response_deserializer=supervisor__pb2.CreateVmRequest.FromString,
                _registered_method=True)
        self.ListVms = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/ListVms',
                request_serializer=supervisor__pb2.ListVmsRequest.SerializeToString,
                response_deserializer=supervisor__pb2.ListVmsResponse.FromString,
                _registered_method=True)
        self.DeleteVm = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/DeleteVm',
                request_serializer=supervisor__pb2.DeleteVmRequest.SerializeToString,
                response_deserializer=supervisor__pb2.DeleteVmResponse.FromString,
                _registered_method=True)
        self.StopVm = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/StopVm',
                request_serializer=supervisor__pb2.StopVmRequest.SerializeToString,
                response_deserializer=supervisor__pb2.VmInfo.FromString,
                _registered_method=True)
        self.StartVm = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/StartVm',
                request_serializer=supervisor__pb2.StartVmRequest.SerializeToString,
                response_deserializer=supervisor__pb2.VmInfo.FromString,
                _registered_method=True)
        self.RebootVm = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/RebootVm',
                request_serializer=supervisor__pb2.RebootVmRequest.SerializeToString,
                response_deserializer=supervisor__pb2.VmInfo.FromString,
                _registered_method=True)
        self.ReinstallVm = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/ReinstallVm',
                request_serializer=supervisor__pb2.ReinstallVmRequest.SerializeToString,
                response_deserializer=supervisor__pb2.VmInfo.FromString,
                _registered_method=True)
        self.AddPortForward = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/AddPortForward',
                request_serializer=supervisor__pb2.AddPortForwardRequest.SerializeToString,
                response_deserializer=supervisor__pb2.PortForwardInfo.FromString,
                _registered_method=True)
        self.RemovePortForward = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/RemovePortForward',
                request_serializer=supervisor__pb2.RemovePortForwardRequest.SerializeToString,
                response_deserializer=supervisor__pb2.RemovePortForwardResponse.FromString,
                _registered_method=True)
        self.ListPortForwards = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/ListPortForwards',
                request_serializer=supervisor__pb2.ListPortForwardsRequest.SerializeToString,
                response_deserializer=supervisor__pb2.ListPortForwardsResponse.FromString,
                _registered_method=True)
        self.GetLogs = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/GetLogs',
                request_serializer=supervisor__pb2.GetLogsRequest.SerializeToString,
                response_deserializer=supervisor__pb2.GetLogsResponse.FromString,
                _registered_method=True)
        self.StreamLogs = channel.unary_stream(
                '/aleph.supervisor.v1.Supervisor/StreamLogs',
                request_serializer=supervisor__pb2.StreamLogsRequest.SerializeToString,
                response_deserializer=supervisor__pb2.LogChunk.FromString,
                _registered_method=True)
        self.StartBackup = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/StartBackup',
                request_serializer=supervisor__pb2.StartBackupRequest.SerializeToString,
                response_deserializer=supervisor__pb2.BackupInfo.FromString,
                _registered_method=True)
        self.GetBackupStatus = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/GetBackupStatus',
                request_serializer=supervisor__pb2.GetBackupStatusRequest.SerializeToString,
                response_deserializer=supervisor__pb2.BackupInfo.FromString,
                _registered_method=True)
        self.ListBackups = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/ListBackups',
                request_serializer=supervisor__pb2.ListBackupsRequest.SerializeToString,
                response_deserializer=supervisor__pb2.ListBackupsResponse.FromString,
                _registered_method=True)
        self.DownloadBackup = channel.unary_stream(
                '/aleph.supervisor.v1.Supervisor/DownloadBackup',
                request_serializer=supervisor__pb2.DownloadBackupRequest.SerializeToString,
                response_deserializer=supervisor__pb2.BackupChunk.FromString,
                _registered_method=True)
        self.DeleteBackup = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/DeleteBackup',
                request_serializer=supervisor__pb2.DeleteBackupRequest.SerializeToString,
                response_deserializer=supervisor__pb2.DeleteBackupResponse.FromString,
                _registered_method=True)
        self.RestoreBackup = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/RestoreBackup',
                request_serializer=supervisor__pb2.RestoreBackupRequest.SerializeToString,
                response_deserializer=supervisor__pb2.VmInfo.FromString,
                _registered_method=True)
        self.ExportVm = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/ExportVm',
                request_serializer=supervisor__pb2.ExportVmRequest.SerializeToString,
                response_deserializer=supervisor__pb2.MigrationInfo.FromString,
                _registered_method=True)
        self.ImportVm = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/ImportVm',
                request_serializer=supervisor__pb2.ImportVmRequest.SerializeToString,
                response_deserializer=supervisor__pb2.VmInfo.FromString,
                _registered_method=True)
        self.GetMigrationStatus = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/GetMigrationStatus',
                request_serializer=supervisor__pb2.GetMigrationStatusRequest.SerializeToString,
                response_deserializer=supervisor__pb2.MigrationInfo.FromString,
                _registered_method=True)
        self.InitializeConfidential = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/InitializeConfidential',
                request_serializer=supervisor__pb2.InitializeConfidentialRequest.SerializeToString,
                response_deserializer=supervisor__pb2.InitializeConfidentialResponse.FromString,
                _registered_method=True)
        self.GetMeasurement = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/GetMeasurement',
                request_serializer=supervisor__pb2.GetMeasurementRequest.SerializeToString,
                response_deserializer=supervisor__pb2.Measurement.FromString,
                _registered_method=True)
        self.InjectSecret = channel.unary_unary(
                '/aleph.supervisor.v1.Supervisor/InjectSecret',
                request_serializer=supervisor__pb2.InjectSecretRequest.SerializeToString,
                response_deserializer=supervisor__pb2.InjectSecretResponse.FromString,
                _registered_method=True)


class SupervisorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """── Host ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHostInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVm(self, request, context):
        """── VM lifecycle ──
        Idempotent on vm_id: re-sending the same spec for a live VM returns its
        current VmInfo (safe retry after UNAVAILABLE / DEADLINE_EXCEEDED); a
        different spec for a live vm_id fails ALREADY_EXISTS.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVmSpec(self, request, context):
        """The spec a live VM was created from, as the supervisor holds it. Lets
        the client rebuild its own records after a restart. UNIMPLEMENTED for
        VMs created outside the spec path (legacy in-process executions).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopVm(self, request, context):
        """Stop a VM without releasing its definition: it stays listed (STOPPED)
        and StartVm brings it back. Persistent VMs only today; for ephemeral
        VMs the cycle is DeleteVm + CreateVm (UNIMPLEMENTED here).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartVm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RebootVm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReinstallVm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPortForward(self, request, context):
        """── Port forwarding ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePortForward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPortForwards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogs(self, request, context):
        """── Logs ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartBackup(self, request, context):
        """── Backups ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBackupStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBackups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadBackup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBackup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreBackup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportVm(self, request, context):
        """── Migration ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportVm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMigrationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeConfidential(self, request, context):
        """── Confidential ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMeasurement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InjectSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SupervisorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=supervisor__pb2.HealthRequest.FromString,
                    response_serializer=supervisor__pb2.HealthResponse.SerializeToString,
            ),
            'GetHostInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHostInfo,
                    request_deserializer=supervisor__pb2.GetHostInfoRequest.FromString,
                    response_serializer=supervisor__pb2.HostInfo.SerializeToString,
            ),
            'CreateVm': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVm,
                    request_deserializer=supervisor__pb2.CreateVmRequest.FromString,
                    response_serializer=supervisor__pb2.VmInfo.SerializeToString,
            ),
            'GetVm': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVm,
                    request_deserializer=supervisor__pb2.GetVmRequest.FromString,
                    response_serializer=supervisor__pb2.VmInfo.SerializeToString,
            ),
            'GetVmSpec': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVmSpec,
                    request_deserializer=supervisor__pb2.GetVmSpecRequest.FromString,
                    response_serializer=supervisor__pb2.CreateVmRequest.SerializeToString,
            ),
            'ListVms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVms,
                    request_deserializer=supervisor__pb2.ListVmsRequest.FromString,
                    response_serializer=supervisor__pb2.ListVmsResponse.SerializeToString,
            ),
            'DeleteVm': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVm,
                    request_deserializer=supervisor__pb2.DeleteVmRequest.FromString,
                    response_serializer=supervisor__pb2.DeleteVmResponse.SerializeToString,
            ),
            'StopVm': grpc.unary_unary_rpc_method_handler(
                    servicer.StopVm,
                    request_deserializer=supervisor__pb2.StopVmRequest.FromString,
                    response_serializer=supervisor__pb2.VmInfo.SerializeToString,
            ),
            'StartVm': grpc.unary_unary_rpc_method_handler(
                    servicer.StartVm,
                    request_deserializer=supervisor__pb2.StartVmRequest.FromString,
                    response_serializer=supervisor__pb2.VmInfo.SerializeToString,
            ),
            'RebootVm': grpc.unary_unary_rpc_method_handler(
                    servicer.RebootVm,
                    request_deserializer=supervisor__pb2.RebootVmRequest.FromString,
                    response_serializer=supervisor__pb2.VmInfo.SerializeToString,
            ),
            'ReinstallVm': grpc.unary_unary_rpc_method_handler(
                    servicer.ReinstallVm,
                    request_deserializer=supervisor__pb2.ReinstallVmRequest.FromString,
                    response_serializer=supervisor__pb2.VmInfo.SerializeToString,
            ),
            'AddPortForward': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPortForward,
                    request_deserializer=supervisor__pb2.AddPortForwardRequest.FromString,
                    response_serializer=supervisor__pb2.PortForwardInfo.SerializeToString,
            ),
            'RemovePortForward': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePortForward,
                    request_deserializer=supervisor__pb2.RemovePortForwardRequest.FromString,
                    response_serializer=supervisor__pb2.RemovePortForwardResponse.SerializeToString,
            ),
            'ListPortForwards': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPortForwards,
                    request_deserializer=supervisor__pb2.ListPortForwardsRequest.FromString,
                    response_serializer=supervisor__pb2.ListPortForwardsResponse.SerializeToString,
            ),
            'GetLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogs,
                    request_deserializer=supervisor__pb2.GetLogsRequest.FromString,
                    response_serializer=supervisor__pb2.GetLogsResponse.SerializeToString,
            ),
            'StreamLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=supervisor__pb2.StreamLogsRequest.FromString,
                    response_serializer=supervisor__pb2.LogChunk.SerializeToString,
            ),
            'StartBackup': grpc.unary_unary_rpc_method_handler(
                    servicer.StartBackup,
                    request_deserializer=supervisor__pb2.StartBackupRequest.FromString,
                    response_serializer=supervisor__pb2.BackupInfo.SerializeToString,
            ),
            'GetBackupStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBackupStatus,
                    request_deserializer=supervisor__pb2.GetBackupStatusRequest.FromString,
                    response_serializer=supervisor__pb2.BackupInfo.SerializeToString,
            ),
            'ListBackups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBackups,
                    request_deserializer=supervisor__pb2.ListBackupsRequest.FromString,
                    response_serializer=supervisor__pb2.ListBackupsResponse.SerializeToString,
            ),
            'DownloadBackup': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadBackup,
                    request_deserializer=supervisor__pb2.DownloadBackupRequest.FromString,
                    response_serializer=supervisor__pb2.BackupChunk.SerializeToString,
            ),
            'DeleteBackup': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBackup,
                    request_deserializer=supervisor__pb2.DeleteBackupRequest.FromString,
                    response_serializer=supervisor__pb2.DeleteBackupResponse.SerializeToString,
            ),
            'RestoreBackup': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreBackup,
                    request_deserializer=supervisor__pb2.RestoreBackupRequest.FromString,
                    response_serializer=supervisor__pb2.VmInfo.SerializeToString,
            ),
            'ExportVm': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportVm,
                    request_deserializer=supervisor__pb2.ExportVmRequest.FromString,
                    response_serializer=supervisor__pb2.MigrationInfo.SerializeToString,
            ),
            'ImportVm': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportVm,
                    request_deserializer=supervisor__pb2.ImportVmRequest.FromString,
                    response_serializer=supervisor__pb2.VmInfo.SerializeToString,
            ),
            'GetMigrationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMigrationStatus,
                    request_deserializer=supervisor__pb2.GetMigrationStatusRequest.FromString,
                    response_serializer=supervisor__pb2.MigrationInfo.SerializeToString,
            ),
            'InitializeConfidential': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeConfidential,
                    request_deserializer=supervisor__pb2.InitializeConfidentialRequest.FromString,
                    response_serializer=supervisor__pb2.InitializeConfidentialResponse.SerializeToString,
            ),
            'GetMeasurement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeasurement,
                    request_deserializer=supervisor__pb2.GetMeasurementRequest.FromString,
                    response_serializer=supervisor__pb2.Measurement.SerializeToString,
            ),
            'InjectSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.InjectSecret,
                    request_deserializer=supervisor__pb2.InjectSecretRequest.FromString,
                    response_serializer=supervisor__pb2.InjectSecretResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aleph.supervisor.v1.Supervisor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aleph.supervisor.v1.Supervisor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Supervisor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/Health',
            supervisor__pb2.HealthRequest.SerializeToString,
            supervisor__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHostInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/GetHostInfo',
            supervisor__pb2.GetHostInfoRequest.SerializeToString,
            supervisor__pb2.HostInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/CreateVm',
            supervisor__pb2.CreateVmRequest.SerializeToString,
            supervisor__pb2.VmInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/GetVm',
            supervisor__pb2.GetVmRequest.SerializeToString,
            supervisor__pb2.VmInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVmSpec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/GetVmSpec',
            supervisor__pb2.GetVmSpecRequest.SerializeToString,
            supervisor__pb2.CreateVmRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/ListVms',
            supervisor__pb2.ListVmsRequest.SerializeToString,
            supervisor__pb2.ListVmsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/DeleteVm',
            supervisor__pb2.DeleteVmRequest.SerializeToString,
            supervisor__pb2.DeleteVmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopVm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/StopVm',
            supervisor__pb2.StopVmRequest.SerializeToString,
            supervisor__pb2.VmInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartVm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/StartVm',
            supervisor__pb2.StartVmRequest.SerializeToString,
            supervisor__pb2.VmInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RebootVm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/RebootVm',
            supervisor__pb2.RebootVmRequest.SerializeToString,
            supervisor__pb2.VmInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReinstallVm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/ReinstallVm',
            supervisor__pb2.ReinstallVmRequest.SerializeToString,
            supervisor__pb2.VmInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPortForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/AddPortForward',
            supervisor__pb2.AddPortForwardRequest.SerializeToString,
            supervisor__pb2.PortForwardInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemovePortForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/RemovePortForward',
            supervisor__pb2.RemovePortForwardRequest.SerializeToString,
            supervisor__pb2.RemovePortForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPortForwards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/ListPortForwards',
            supervisor__pb2.ListPortForwardsRequest.SerializeToString,
            supervisor__pb2.ListPortForwardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/GetLogs',
            supervisor__pb2.GetLogsRequest.SerializeToString,
            supervisor__pb2.GetLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/StreamLogs',
            supervisor__pb2.StreamLogsRequest.SerializeToString,
            supervisor__pb2.LogChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/StartBackup',
            supervisor__pb2.StartBackupRequest.SerializeToString,
            supervisor__pb2.BackupInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBackupStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/GetBackupStatus',
            supervisor__pb2.GetBackupStatusRequest.SerializeToString,
            supervisor__pb2.BackupInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBackups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/ListBackups',
            supervisor__pb2.ListBackupsRequest.SerializeToString,
            supervisor__pb2.ListBackupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/DownloadBackup',
            supervisor__pb2.DownloadBackupRequest.SerializeToString,
            supervisor__pb2.BackupChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/DeleteBackup',
            supervisor__pb2.DeleteBackupRequest.SerializeToString,
            supervisor__pb2.DeleteBackupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/RestoreBackup',
            supervisor__pb2.RestoreBackupRequest.SerializeToString,
            supervisor__pb2.VmInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportVm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/ExportVm',
            supervisor__pb2.ExportVmRequest.SerializeToString,
            supervisor__pb2.MigrationInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportVm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/ImportVm',
            supervisor__pb2.ImportVmRequest.SerializeToString,
            supervisor__pb2.VmInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMigrationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/GetMigrationStatus',
            supervisor__pb2.GetMigrationStatusRequest.SerializeToString,
            supervisor__pb2.MigrationInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitializeConfidential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/InitializeConfidential',
            supervisor__pb2.InitializeConfidentialRequest.SerializeToString,
            supervisor__pb2.InitializeConfidentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMeasurement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/GetMeasurement',
            supervisor__pb2.GetMeasurementRequest.SerializeToString,
            supervisor__pb2.Measurement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InjectSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.supervisor.v1.Supervisor/InjectSecret',
            supervisor__pb2.InjectSecretRequest.SerializeToString,
            supervisor__pb2.InjectSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
