"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
SPDX-License-Identifier: MIT

Aleph VM Supervisor contract.

This service is the infra-only boundary between the network-agent
(Aleph orchestration: HTTP CRN API, messages, payments, allocations)
and the supervisor (controllers, hypervisors, networking, systemd,
backups). Reference: docs/plans/2026-05-28-aleph-vm-architecture-
backport-design.md.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Backend:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BackendEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Backend.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BACKEND_UNSPECIFIED: _Backend.ValueType  # 0
    BACKEND_FIRECRACKER: _Backend.ValueType  # 1
    BACKEND_QEMU: _Backend.ValueType  # 2
    BACKEND_QEMU_SEV: _Backend.ValueType  # 3

class Backend(_Backend, metaclass=_BackendEnumTypeWrapper):
    """── Lifecycle ────────────────────────────────────────────────────────────"""

BACKEND_UNSPECIFIED: Backend.ValueType  # 0
BACKEND_FIRECRACKER: Backend.ValueType  # 1
BACKEND_QEMU: Backend.ValueType  # 2
BACKEND_QEMU_SEV: Backend.ValueType  # 3
Global___Backend: typing_extensions.TypeAlias = Backend

class _VmStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _VmStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_VmStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    VM_STATUS_UNSPECIFIED: _VmStatus.ValueType  # 0
    VM_STATUS_DEFINED: _VmStatus.ValueType  # 1
    VM_STATUS_BOOTING: _VmStatus.ValueType  # 2
    VM_STATUS_RUNNING: _VmStatus.ValueType  # 3
    VM_STATUS_STOPPING: _VmStatus.ValueType  # 4
    VM_STATUS_STOPPED: _VmStatus.ValueType  # 5
    VM_STATUS_FAILED: _VmStatus.ValueType  # 6

class VmStatus(_VmStatus, metaclass=_VmStatusEnumTypeWrapper): ...

VM_STATUS_UNSPECIFIED: VmStatus.ValueType  # 0
VM_STATUS_DEFINED: VmStatus.ValueType  # 1
VM_STATUS_BOOTING: VmStatus.ValueType  # 2
VM_STATUS_RUNNING: VmStatus.ValueType  # 3
VM_STATUS_STOPPING: VmStatus.ValueType  # 4
VM_STATUS_STOPPED: VmStatus.ValueType  # 5
VM_STATUS_FAILED: VmStatus.ValueType  # 6
Global___VmStatus: typing_extensions.TypeAlias = VmStatus

class _BackupStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BackupStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BackupStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BACKUP_STATUS_UNSPECIFIED: _BackupStatus.ValueType  # 0
    BACKUP_STATUS_PENDING: _BackupStatus.ValueType  # 1
    BACKUP_STATUS_RUNNING: _BackupStatus.ValueType  # 2
    BACKUP_STATUS_COMPLETE: _BackupStatus.ValueType  # 3
    BACKUP_STATUS_FAILED: _BackupStatus.ValueType  # 4

class BackupStatus(_BackupStatus, metaclass=_BackupStatusEnumTypeWrapper):
    """── Backups ──────────────────────────────────────────────────────────────"""

BACKUP_STATUS_UNSPECIFIED: BackupStatus.ValueType  # 0
BACKUP_STATUS_PENDING: BackupStatus.ValueType  # 1
BACKUP_STATUS_RUNNING: BackupStatus.ValueType  # 2
BACKUP_STATUS_COMPLETE: BackupStatus.ValueType  # 3
BACKUP_STATUS_FAILED: BackupStatus.ValueType  # 4
Global___BackupStatus: typing_extensions.TypeAlias = BackupStatus

class _MigrationPhase:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MigrationPhaseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MigrationPhase.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MIGRATION_PHASE_UNSPECIFIED: _MigrationPhase.ValueType  # 0
    MIGRATION_PHASE_PREPARING: _MigrationPhase.ValueType  # 1
    MIGRATION_PHASE_EXPORTING: _MigrationPhase.ValueType  # 2
    MIGRATION_PHASE_IMPORTING: _MigrationPhase.ValueType  # 3
    MIGRATION_PHASE_COMPLETE: _MigrationPhase.ValueType  # 4
    MIGRATION_PHASE_FAILED: _MigrationPhase.ValueType  # 5

class MigrationPhase(_MigrationPhase, metaclass=_MigrationPhaseEnumTypeWrapper):
    """── Migration ────────────────────────────────────────────────────────────"""

MIGRATION_PHASE_UNSPECIFIED: MigrationPhase.ValueType  # 0
MIGRATION_PHASE_PREPARING: MigrationPhase.ValueType  # 1
MIGRATION_PHASE_EXPORTING: MigrationPhase.ValueType  # 2
MIGRATION_PHASE_IMPORTING: MigrationPhase.ValueType  # 3
MIGRATION_PHASE_COMPLETE: MigrationPhase.ValueType  # 4
MIGRATION_PHASE_FAILED: MigrationPhase.ValueType  # 5
Global___MigrationPhase: typing_extensions.TypeAlias = MigrationPhase

class _ErrorCode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ErrorCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ErrorCode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ERROR_CODE_UNSPECIFIED: _ErrorCode.ValueType  # 0
    ERROR_CODE_VM_NOT_FOUND: _ErrorCode.ValueType  # 1
    """Lifecycle"""
    ERROR_CODE_VM_ALREADY_EXISTS: _ErrorCode.ValueType  # 2
    ERROR_CODE_INSUFFICIENT_RESOURCES: _ErrorCode.ValueType  # 3
    ERROR_CODE_RESOURCE_DOWNLOAD_FAILED: _ErrorCode.ValueType  # 4
    """Resource preparation"""
    ERROR_CODE_FILE_TOO_LARGE: _ErrorCode.ValueType  # 5
    ERROR_CODE_VM_SETUP_FAILED: _ErrorCode.ValueType  # 6
    """Backend"""
    ERROR_CODE_MICROVM_INIT_FAILED: _ErrorCode.ValueType  # 7
    ERROR_CODE_INVALID_BACKEND: _ErrorCode.ValueType  # 8
    ERROR_CODE_TEE_UNAVAILABLE: _ErrorCode.ValueType  # 9
    ERROR_CODE_PORT_UNAVAILABLE: _ErrorCode.ValueType  # 10
    """Networking"""
    ERROR_CODE_HOST_NOT_FOUND: _ErrorCode.ValueType  # 11
    ERROR_CODE_BACKUP_NOT_FOUND: _ErrorCode.ValueType  # 12
    """Backup / migration"""
    ERROR_CODE_MIGRATION_IN_PROGRESS: _ErrorCode.ValueType  # 13
    ERROR_CODE_INTERNAL: _ErrorCode.ValueType  # 99
    """Catch-all"""

class ErrorCode(_ErrorCode, metaclass=_ErrorCodeEnumTypeWrapper):
    """── Wire error vocabulary ────────────────────────────────────────────────

    Closed enum of errors the supervisor can return. Server side: map
    backend exceptions (FileTooLargeError, VmSetupError,
    MicroVMFailedInitError, ResourceDownloadError,
    InsufficientResourcesError, HostNotFoundError, ...) into this enum
    and attach an ErrorDetail in the gRPC status trailers. Agent side:
    catch grpc.AioRpcError, read the trailer, translate to HTTP.
    """

ERROR_CODE_UNSPECIFIED: ErrorCode.ValueType  # 0
ERROR_CODE_VM_NOT_FOUND: ErrorCode.ValueType  # 1
"""Lifecycle"""
ERROR_CODE_VM_ALREADY_EXISTS: ErrorCode.ValueType  # 2
ERROR_CODE_INSUFFICIENT_RESOURCES: ErrorCode.ValueType  # 3
ERROR_CODE_RESOURCE_DOWNLOAD_FAILED: ErrorCode.ValueType  # 4
"""Resource preparation"""
ERROR_CODE_FILE_TOO_LARGE: ErrorCode.ValueType  # 5
ERROR_CODE_VM_SETUP_FAILED: ErrorCode.ValueType  # 6
"""Backend"""
ERROR_CODE_MICROVM_INIT_FAILED: ErrorCode.ValueType  # 7
ERROR_CODE_INVALID_BACKEND: ErrorCode.ValueType  # 8
ERROR_CODE_TEE_UNAVAILABLE: ErrorCode.ValueType  # 9
ERROR_CODE_PORT_UNAVAILABLE: ErrorCode.ValueType  # 10
"""Networking"""
ERROR_CODE_HOST_NOT_FOUND: ErrorCode.ValueType  # 11
ERROR_CODE_BACKUP_NOT_FOUND: ErrorCode.ValueType  # 12
"""Backup / migration"""
ERROR_CODE_MIGRATION_IN_PROGRESS: ErrorCode.ValueType  # 13
ERROR_CODE_INTERNAL: ErrorCode.ValueType  # 99
"""Catch-all"""
Global___ErrorCode: typing_extensions.TypeAlias = ErrorCode

@typing.final
class HealthRequest(google.protobuf.message.Message):
    """── Host ─────────────────────────────────────────────────────────────────"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___HealthRequest: typing_extensions.TypeAlias = HealthRequest

@typing.final
class HealthResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    VM_COUNT_FIELD_NUMBER: builtins.int
    status: builtins.str
    """"ok" | "degraded" """
    vm_count: builtins.int
    def __init__(
        self,
        *,
        status: builtins.str = ...,
        vm_count: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status", "vm_count", b"vm_count"]) -> None: ...

Global___HealthResponse: typing_extensions.TypeAlias = HealthResponse

@typing.final
class GetHostInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetHostInfoRequest: typing_extensions.TypeAlias = GetHostInfoRequest

@typing.final
class HostInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CPU_COUNT_FIELD_NUMBER: builtins.int
    CPU_ARCHITECTURE_FIELD_NUMBER: builtins.int
    CPU_VENDOR_FIELD_NUMBER: builtins.int
    CPU_MODEL_FIELD_NUMBER: builtins.int
    CPU_FREQUENCY_MHZ_FIELD_NUMBER: builtins.int
    MEMORY_MIB_FIELD_NUMBER: builtins.int
    MEMORY_TYPE_FIELD_NUMBER: builtins.int
    MEMORY_CLOCK_MHZ_FIELD_NUMBER: builtins.int
    NUMA_NODES_FIELD_NUMBER: builtins.int
    GPUS_FIELD_NUMBER: builtins.int
    SEV_SUPPORTED_FIELD_NUMBER: builtins.int
    SEV_ES_SUPPORTED_FIELD_NUMBER: builtins.int
    SEV_SNP_SUPPORTED_FIELD_NUMBER: builtins.int
    TDX_SUPPORTED_FIELD_NUMBER: builtins.int
    HOSTNAME_FIELD_NUMBER: builtins.int
    KERNEL_VERSION_FIELD_NUMBER: builtins.int
    cpu_count: builtins.int
    """CPU"""
    cpu_architecture: builtins.str
    """e.g. "x86_64", "aarch64" """
    cpu_vendor: builtins.str
    """e.g. "AuthenticAMD", "GenuineIntel" """
    cpu_model: builtins.str
    """e.g. "AMD EPYC 9354P" """
    cpu_frequency_mhz: builtins.int
    """base clock"""
    memory_mib: builtins.int
    """Memory"""
    memory_type: builtins.str
    """e.g. "DDR5" """
    memory_clock_mhz: builtins.int
    sev_supported: builtins.bool
    """TEE support
    SEV (base AMD memory encryption)
    """
    sev_es_supported: builtins.bool
    """SEV-ES (encrypted register state)"""
    sev_snp_supported: builtins.bool
    """SEV-SNP (full attestation)"""
    tdx_supported: builtins.bool
    hostname: builtins.str
    """Identity"""
    kernel_version: builtins.str
    @property
    def numa_nodes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___NumaNode]:
        """Topology"""

    @property
    def gpus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___GpuDevice]: ...
    def __init__(
        self,
        *,
        cpu_count: builtins.int = ...,
        cpu_architecture: builtins.str = ...,
        cpu_vendor: builtins.str = ...,
        cpu_model: builtins.str = ...,
        cpu_frequency_mhz: builtins.int = ...,
        memory_mib: builtins.int = ...,
        memory_type: builtins.str = ...,
        memory_clock_mhz: builtins.int = ...,
        numa_nodes: collections.abc.Iterable[Global___NumaNode] | None = ...,
        gpus: collections.abc.Iterable[Global___GpuDevice] | None = ...,
        sev_supported: builtins.bool = ...,
        sev_es_supported: builtins.bool = ...,
        sev_snp_supported: builtins.bool = ...,
        tdx_supported: builtins.bool = ...,
        hostname: builtins.str = ...,
        kernel_version: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cpu_architecture", b"cpu_architecture", "cpu_count", b"cpu_count", "cpu_frequency_mhz", b"cpu_frequency_mhz", "cpu_model", b"cpu_model", "cpu_vendor", b"cpu_vendor", "gpus", b"gpus", "hostname", b"hostname", "kernel_version", b"kernel_version", "memory_clock_mhz", b"memory_clock_mhz", "memory_mib", b"memory_mib", "memory_type", b"memory_type", "numa_nodes", b"numa_nodes", "sev_es_supported", b"sev_es_supported", "sev_snp_supported", b"sev_snp_supported", "sev_supported", b"sev_supported", "tdx_supported", b"tdx_supported"]) -> None: ...

Global___HostInfo: typing_extensions.TypeAlias = HostInfo

@typing.final
class NumaNode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INDEX_FIELD_NUMBER: builtins.int
    CPU_COUNT_FIELD_NUMBER: builtins.int
    MEMORY_MIB_FIELD_NUMBER: builtins.int
    index: builtins.int
    cpu_count: builtins.int
    memory_mib: builtins.int
    def __init__(
        self,
        *,
        index: builtins.int = ...,
        cpu_count: builtins.int = ...,
        memory_mib: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cpu_count", b"cpu_count", "index", b"index", "memory_mib", b"memory_mib"]) -> None: ...

Global___NumaNode: typing_extensions.TypeAlias = NumaNode

@typing.final
class GpuDevice(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PCI_HOST_FIELD_NUMBER: builtins.int
    DEVICE_ID_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    SUPPORTS_X_VGA_FIELD_NUMBER: builtins.int
    pci_host: builtins.str
    """e.g. "0000:01:00.0" """
    device_id: builtins.str
    """vendor:device"""
    model: builtins.str
    supports_x_vga: builtins.bool
    def __init__(
        self,
        *,
        pci_host: builtins.str = ...,
        device_id: builtins.str = ...,
        model: builtins.str = ...,
        supports_x_vga: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["device_id", b"device_id", "model", b"model", "pci_host", b"pci_host", "supports_x_vga", b"supports_x_vga"]) -> None: ...

Global___GpuDevice: typing_extensions.TypeAlias = GpuDevice

@typing.final
class CreateVmRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    BACKEND_FIELD_NUMBER: builtins.int
    KERNEL_PATH_FIELD_NUMBER: builtins.int
    INITRD_PATH_FIELD_NUMBER: builtins.int
    DISKS_FIELD_NUMBER: builtins.int
    VCPUS_FIELD_NUMBER: builtins.int
    MEMORY_MIB_FIELD_NUMBER: builtins.int
    TEE_FIELD_NUMBER: builtins.int
    NETWORK_FIELD_NUMBER: builtins.int
    GPUS_FIELD_NUMBER: builtins.int
    NUMA_NODE_FIELD_NUMBER: builtins.int
    PERSISTENT_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    """agent-issued id, opaque to supervisor"""
    backend: Global___Backend.ValueType
    kernel_path: builtins.str
    """empty for disk-boot"""
    initrd_path: builtins.str
    """empty for disk-boot"""
    vcpus: builtins.int
    memory_mib: builtins.int
    numa_node: builtins.int
    """requested placement (0-indexed). Unset = auto. See VmInfo.numa_node for the effective placement."""
    persistent: builtins.bool
    """supervisor wraps in systemd if true"""
    @property
    def disks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___DiskConfig]: ...
    @property
    def tee(self) -> Global___TeeConfig:
        """only meaningful when backend is *_SEV"""

    @property
    def network(self) -> Global___NetworkConfig: ...
    @property
    def gpus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___GpuConfig]: ...
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        backend: Global___Backend.ValueType = ...,
        kernel_path: builtins.str = ...,
        initrd_path: builtins.str = ...,
        disks: collections.abc.Iterable[Global___DiskConfig] | None = ...,
        vcpus: builtins.int = ...,
        memory_mib: builtins.int = ...,
        tee: Global___TeeConfig | None = ...,
        network: Global___NetworkConfig | None = ...,
        gpus: collections.abc.Iterable[Global___GpuConfig] | None = ...,
        numa_node: builtins.int | None = ...,
        persistent: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_numa_node", b"_numa_node", "network", b"network", "numa_node", b"numa_node", "tee", b"tee"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_numa_node", b"_numa_node", "backend", b"backend", "disks", b"disks", "gpus", b"gpus", "initrd_path", b"initrd_path", "kernel_path", b"kernel_path", "memory_mib", b"memory_mib", "network", b"network", "numa_node", b"numa_node", "persistent", b"persistent", "tee", b"tee", "vcpus", b"vcpus", "vm_id", b"vm_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_numa_node", b"_numa_node"]) -> typing.Literal["numa_node"] | None: ...

Global___CreateVmRequest: typing_extensions.TypeAlias = CreateVmRequest

@typing.final
class DiskConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Format:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _FormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DiskConfig._Format.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        FORMAT_UNSPECIFIED: DiskConfig._Format.ValueType  # 0
        FORMAT_RAW: DiskConfig._Format.ValueType  # 1
        FORMAT_QCOW2: DiskConfig._Format.ValueType  # 2
        FORMAT_SQUASHFS: DiskConfig._Format.ValueType  # 3

    class Format(_Format, metaclass=_FormatEnumTypeWrapper): ...
    FORMAT_UNSPECIFIED: DiskConfig.Format.ValueType  # 0
    FORMAT_RAW: DiskConfig.Format.ValueType  # 1
    FORMAT_QCOW2: DiskConfig.Format.ValueType  # 2
    FORMAT_SQUASHFS: DiskConfig.Format.ValueType  # 3

    class _DiskRole:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DiskRoleEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DiskConfig._DiskRole.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        DISK_ROLE_UNSPECIFIED: DiskConfig._DiskRole.ValueType  # 0
        DISK_ROLE_ROOTFS: DiskConfig._DiskRole.ValueType  # 1
        DISK_ROLE_CODE: DiskConfig._DiskRole.ValueType  # 2
        DISK_ROLE_RUNTIME: DiskConfig._DiskRole.ValueType  # 3
        DISK_ROLE_DATA: DiskConfig._DiskRole.ValueType  # 4
        DISK_ROLE_EXTRA: DiskConfig._DiskRole.ValueType  # 5

    class DiskRole(_DiskRole, metaclass=_DiskRoleEnumTypeWrapper): ...
    DISK_ROLE_UNSPECIFIED: DiskConfig.DiskRole.ValueType  # 0
    DISK_ROLE_ROOTFS: DiskConfig.DiskRole.ValueType  # 1
    DISK_ROLE_CODE: DiskConfig.DiskRole.ValueType  # 2
    DISK_ROLE_RUNTIME: DiskConfig.DiskRole.ValueType  # 3
    DISK_ROLE_DATA: DiskConfig.DiskRole.ValueType  # 4
    DISK_ROLE_EXTRA: DiskConfig.DiskRole.ValueType  # 5

    PATH_FIELD_NUMBER: builtins.int
    READONLY_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    path: builtins.str
    """absolute host path"""
    readonly: builtins.bool
    format: Global___DiskConfig.Format.ValueType
    role: Global___DiskConfig.DiskRole.ValueType
    def __init__(
        self,
        *,
        path: builtins.str = ...,
        readonly: builtins.bool = ...,
        format: Global___DiskConfig.Format.ValueType = ...,
        role: Global___DiskConfig.DiskRole.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["format", b"format", "path", b"path", "readonly", b"readonly", "role", b"role"]) -> None: ...

Global___DiskConfig: typing_extensions.TypeAlias = DiskConfig

@typing.final
class TeeConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BACKEND_FIELD_NUMBER: builtins.int
    POLICY_FIELD_NUMBER: builtins.int
    SESSION_DIR_FIELD_NUMBER: builtins.int
    backend: builtins.str
    """TEE attestation backend: "sev-snp", "tdx", "nvidia-cc", or "" (orthogonal to the top-level Backend enum, which selects the VMM)."""
    policy: builtins.str
    """empty = default"""
    session_dir: builtins.str
    """confidential session files"""
    def __init__(
        self,
        *,
        backend: builtins.str = ...,
        policy: builtins.str = ...,
        session_dir: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["backend", b"backend", "policy", b"policy", "session_dir", b"session_dir"]) -> None: ...

Global___TeeConfig: typing_extensions.TypeAlias = TeeConfig

@typing.final
class NetworkConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INTERNET_ACCESS_FIELD_NUMBER: builtins.int
    REQUESTED_IPV6_FIELD_NUMBER: builtins.int
    IPV6_PREFIX_LEN_FIELD_NUMBER: builtins.int
    internet_access: builtins.bool
    requested_ipv6: builtins.str
    """empty = pool-assigned"""
    ipv6_prefix_len: builtins.int
    """0 = /128"""
    def __init__(
        self,
        *,
        internet_access: builtins.bool = ...,
        requested_ipv6: builtins.str = ...,
        ipv6_prefix_len: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["internet_access", b"internet_access", "ipv6_prefix_len", b"ipv6_prefix_len", "requested_ipv6", b"requested_ipv6"]) -> None: ...

Global___NetworkConfig: typing_extensions.TypeAlias = NetworkConfig

@typing.final
class GpuConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PCI_HOST_FIELD_NUMBER: builtins.int
    SUPPORTS_X_VGA_FIELD_NUMBER: builtins.int
    pci_host: builtins.str
    supports_x_vga: builtins.bool
    def __init__(
        self,
        *,
        pci_host: builtins.str = ...,
        supports_x_vga: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pci_host", b"pci_host", "supports_x_vga", b"supports_x_vga"]) -> None: ...

Global___GpuConfig: typing_extensions.TypeAlias = GpuConfig

@typing.final
class VmInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    IPV4_FIELD_NUMBER: builtins.int
    IPV6_FIELD_NUMBER: builtins.int
    UPTIME_SECS_FIELD_NUMBER: builtins.int
    BACKEND_FIELD_NUMBER: builtins.int
    NUMA_NODE_FIELD_NUMBER: builtins.int
    STATUS_MESSAGE_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    status: Global___VmStatus.ValueType
    ipv4: builtins.str
    ipv6: builtins.str
    uptime_secs: builtins.int
    backend: Global___Backend.ValueType
    numa_node: builtins.int
    """effective placement (0-indexed). Unset until status is BOOTING/RUNNING."""
    status_message: builtins.str
    """human-readable, optional"""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        status: Global___VmStatus.ValueType = ...,
        ipv4: builtins.str = ...,
        ipv6: builtins.str = ...,
        uptime_secs: builtins.int = ...,
        backend: Global___Backend.ValueType = ...,
        numa_node: builtins.int | None = ...,
        status_message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_numa_node", b"_numa_node", "numa_node", b"numa_node"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_numa_node", b"_numa_node", "backend", b"backend", "ipv4", b"ipv4", "ipv6", b"ipv6", "numa_node", b"numa_node", "status", b"status", "status_message", b"status_message", "uptime_secs", b"uptime_secs", "vm_id", b"vm_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_numa_node", b"_numa_node"]) -> typing.Literal["numa_node"] | None: ...

Global___VmInfo: typing_extensions.TypeAlias = VmInfo

@typing.final
class GetVmRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

Global___GetVmRequest: typing_extensions.TypeAlias = GetVmRequest

@typing.final
class ListVmsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ListVmsRequest: typing_extensions.TypeAlias = ListVmsRequest

@typing.final
class ListVmsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VMS_FIELD_NUMBER: builtins.int
    @property
    def vms(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___VmInfo]: ...
    def __init__(
        self,
        *,
        vms: collections.abc.Iterable[Global___VmInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vms", b"vms"]) -> None: ...

Global___ListVmsResponse: typing_extensions.TypeAlias = ListVmsResponse

@typing.final
class DeleteVmRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

Global___DeleteVmRequest: typing_extensions.TypeAlias = DeleteVmRequest

@typing.final
class DeleteVmResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DeleteVmResponse: typing_extensions.TypeAlias = DeleteVmResponse

@typing.final
class RebootVmRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    """Note: aleph-vm performs soft reboot only today (systemd restart
    for persistent VMs, recreate for ephemeral). Firecracker has no
    reboot API. Add a `hard` option when a real implementation lands.
    """
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

Global___RebootVmRequest: typing_extensions.TypeAlias = RebootVmRequest

@typing.final
class ReinstallVmRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

Global___ReinstallVmRequest: typing_extensions.TypeAlias = ReinstallVmRequest

@typing.final
class AddPortForwardRequest(google.protobuf.message.Message):
    """── Port forwarding ──────────────────────────────────────────────────────"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    HOST_PORT_FIELD_NUMBER: builtins.int
    VM_PORT_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    host_port: builtins.int
    """0 = auto-allocate"""
    vm_port: builtins.int
    protocol: builtins.str
    """"tcp" | "udp" """
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        host_port: builtins.int = ...,
        vm_port: builtins.int = ...,
        protocol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["host_port", b"host_port", "protocol", b"protocol", "vm_id", b"vm_id", "vm_port", b"vm_port"]) -> None: ...

Global___AddPortForwardRequest: typing_extensions.TypeAlias = AddPortForwardRequest

@typing.final
class PortForwardInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    HOST_PORT_FIELD_NUMBER: builtins.int
    VM_PORT_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    host_port: builtins.int
    vm_port: builtins.int
    protocol: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        host_port: builtins.int = ...,
        vm_port: builtins.int = ...,
        protocol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["host_port", b"host_port", "protocol", b"protocol", "vm_id", b"vm_id", "vm_port", b"vm_port"]) -> None: ...

Global___PortForwardInfo: typing_extensions.TypeAlias = PortForwardInfo

@typing.final
class RemovePortForwardRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    HOST_PORT_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    host_port: builtins.int
    protocol: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        host_port: builtins.int = ...,
        protocol: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["host_port", b"host_port", "protocol", b"protocol", "vm_id", b"vm_id"]) -> None: ...

Global___RemovePortForwardRequest: typing_extensions.TypeAlias = RemovePortForwardRequest

@typing.final
class RemovePortForwardResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___RemovePortForwardResponse: typing_extensions.TypeAlias = RemovePortForwardResponse

@typing.final
class ListPortForwardsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    """empty = all VMs"""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

Global___ListPortForwardsRequest: typing_extensions.TypeAlias = ListPortForwardsRequest

@typing.final
class ListPortForwardsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FORWARDS_FIELD_NUMBER: builtins.int
    @property
    def forwards(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___PortForwardInfo]: ...
    def __init__(
        self,
        *,
        forwards: collections.abc.Iterable[Global___PortForwardInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["forwards", b"forwards"]) -> None: ...

Global___ListPortForwardsResponse: typing_extensions.TypeAlias = ListPortForwardsResponse

@typing.final
class GetLogsRequest(google.protobuf.message.Message):
    """── Logs ─────────────────────────────────────────────────────────────────"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    MAX_LINES_FIELD_NUMBER: builtins.int
    FROM_TAIL_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    max_lines: builtins.int
    """0 = unlimited (subject to server cap)"""
    from_tail: builtins.bool
    """true = most recent lines"""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        max_lines: builtins.int = ...,
        from_tail: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["from_tail", b"from_tail", "max_lines", b"max_lines", "vm_id", b"vm_id"]) -> None: ...

Global___GetLogsRequest: typing_extensions.TypeAlias = GetLogsRequest

@typing.final
class GetLogsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LINES_FIELD_NUMBER: builtins.int
    @property
    def lines(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___LogChunk]: ...
    def __init__(
        self,
        *,
        lines: collections.abc.Iterable[Global___LogChunk] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["lines", b"lines"]) -> None: ...

Global___GetLogsResponse: typing_extensions.TypeAlias = GetLogsResponse

@typing.final
class StreamLogsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    INCLUDE_HISTORY_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    include_history: builtins.bool
    """false = only new lines from now"""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        include_history: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["include_history", b"include_history", "vm_id", b"vm_id"]) -> None: ...

Global___StreamLogsRequest: typing_extensions.TypeAlias = StreamLogsRequest

@typing.final
class LogChunk(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _LogSource:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _LogSourceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LogChunk._LogSource.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        LOG_SOURCE_UNSPECIFIED: LogChunk._LogSource.ValueType  # 0
        LOG_SOURCE_SERIAL: LogChunk._LogSource.ValueType  # 1
        """QEMU serial console"""
        LOG_SOURCE_STDOUT: LogChunk._LogSource.ValueType  # 2
        """Firecracker vm-stdout"""
        LOG_SOURCE_SYSTEMD: LogChunk._LogSource.ValueType  # 3
        """systemd journal for persistent VM unit"""

    class LogSource(_LogSource, metaclass=_LogSourceEnumTypeWrapper): ...
    LOG_SOURCE_UNSPECIFIED: LogChunk.LogSource.ValueType  # 0
    LOG_SOURCE_SERIAL: LogChunk.LogSource.ValueType  # 1
    """QEMU serial console"""
    LOG_SOURCE_STDOUT: LogChunk.LogSource.ValueType  # 2
    """Firecracker vm-stdout"""
    LOG_SOURCE_SYSTEMD: LogChunk.LogSource.ValueType  # 3
    """systemd journal for persistent VM unit"""

    TIMESTAMP_NS_FIELD_NUMBER: builtins.int
    LINE_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    timestamp_ns: builtins.int
    """unix ns at server-side capture time"""
    line: builtins.str
    """single log line, no trailing newline"""
    source: Global___LogChunk.LogSource.ValueType
    def __init__(
        self,
        *,
        timestamp_ns: builtins.int = ...,
        line: builtins.str = ...,
        source: Global___LogChunk.LogSource.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["line", b"line", "source", b"source", "timestamp_ns", b"timestamp_ns"]) -> None: ...

Global___LogChunk: typing_extensions.TypeAlias = LogChunk

@typing.final
class BackupInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    BACKUP_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    SIZE_BYTES_FIELD_NUMBER: builtins.int
    CREATED_AT_UNIX_SECS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    backup_id: builtins.str
    """supervisor-issued"""
    status: Global___BackupStatus.ValueType
    size_bytes: builtins.int
    """0 until COMPLETE"""
    created_at_unix_secs: builtins.int
    error_message: builtins.str
    """populated when status = FAILED"""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        backup_id: builtins.str = ...,
        status: Global___BackupStatus.ValueType = ...,
        size_bytes: builtins.int = ...,
        created_at_unix_secs: builtins.int = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["backup_id", b"backup_id", "created_at_unix_secs", b"created_at_unix_secs", "error_message", b"error_message", "size_bytes", b"size_bytes", "status", b"status", "vm_id", b"vm_id"]) -> None: ...

Global___BackupInfo: typing_extensions.TypeAlias = BackupInfo

@typing.final
class StartBackupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    QUIESCE_GUEST_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    quiesce_guest: builtins.bool
    """request guest fs-freeze if supported"""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        quiesce_guest: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["quiesce_guest", b"quiesce_guest", "vm_id", b"vm_id"]) -> None: ...

Global___StartBackupRequest: typing_extensions.TypeAlias = StartBackupRequest

@typing.final
class GetBackupStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    BACKUP_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    backup_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        backup_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["backup_id", b"backup_id", "vm_id", b"vm_id"]) -> None: ...

Global___GetBackupStatusRequest: typing_extensions.TypeAlias = GetBackupStatusRequest

@typing.final
class ListBackupsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

Global___ListBackupsRequest: typing_extensions.TypeAlias = ListBackupsRequest

@typing.final
class ListBackupsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BACKUPS_FIELD_NUMBER: builtins.int
    @property
    def backups(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___BackupInfo]: ...
    def __init__(
        self,
        *,
        backups: collections.abc.Iterable[Global___BackupInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["backups", b"backups"]) -> None: ...

Global___ListBackupsResponse: typing_extensions.TypeAlias = ListBackupsResponse

@typing.final
class DownloadBackupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    BACKUP_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    backup_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        backup_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["backup_id", b"backup_id", "vm_id", b"vm_id"]) -> None: ...

Global___DownloadBackupRequest: typing_extensions.TypeAlias = DownloadBackupRequest

@typing.final
class BackupChunk(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    offset: builtins.int
    """byte offset of `data` in the backup; lets the client detect gaps and resume after a transient stream failure."""
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        offset: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "offset", b"offset"]) -> None: ...

Global___BackupChunk: typing_extensions.TypeAlias = BackupChunk

@typing.final
class DeleteBackupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    BACKUP_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    backup_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        backup_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["backup_id", b"backup_id", "vm_id", b"vm_id"]) -> None: ...

Global___DeleteBackupRequest: typing_extensions.TypeAlias = DeleteBackupRequest

@typing.final
class DeleteBackupResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DeleteBackupResponse: typing_extensions.TypeAlias = DeleteBackupResponse

@typing.final
class RestoreBackupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    BACKUP_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    backup_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        backup_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["backup_id", b"backup_id", "vm_id", b"vm_id"]) -> None: ...

Global___RestoreBackupRequest: typing_extensions.TypeAlias = RestoreBackupRequest

@typing.final
class MigrationInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    MIGRATION_ID_FIELD_NUMBER: builtins.int
    PHASE_FIELD_NUMBER: builtins.int
    BYTES_TRANSFERRED_FIELD_NUMBER: builtins.int
    BYTES_TOTAL_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    migration_id: builtins.str
    phase: Global___MigrationPhase.ValueType
    bytes_transferred: builtins.int
    bytes_total: builtins.int
    error_message: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        migration_id: builtins.str = ...,
        phase: Global___MigrationPhase.ValueType = ...,
        bytes_transferred: builtins.int = ...,
        bytes_total: builtins.int = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bytes_total", b"bytes_total", "bytes_transferred", b"bytes_transferred", "error_message", b"error_message", "migration_id", b"migration_id", "phase", b"phase", "vm_id", b"vm_id"]) -> None: ...

Global___MigrationInfo: typing_extensions.TypeAlias = MigrationInfo

@typing.final
class ExportVmRequest(google.protobuf.message.Message):
    """NOTE (Plan 0.A): the directory-based shape below is provisional.
    aleph-vm's current migration is HTTP-based (the source exposes
    /control/machine/{ref}/migration/disk/... and the destination
    fetches). The contract needs reshaping for host-to-host transport
    before Plan 0.C wires real implementations. See design doc §9 open
    questions.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    DESTINATION_DIR_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    destination_dir: builtins.str
    """PROVISIONAL: local path on the host"""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        destination_dir: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["destination_dir", b"destination_dir", "vm_id", b"vm_id"]) -> None: ...

Global___ExportVmRequest: typing_extensions.TypeAlias = ExportVmRequest

@typing.final
class ImportVmRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    SOURCE_DIR_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    """id the new VM will be assigned post-import"""
    source_dir: builtins.str
    """PROVISIONAL: see note on ExportVmRequest"""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        source_dir: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["source_dir", b"source_dir", "vm_id", b"vm_id"]) -> None: ...

Global___ImportVmRequest: typing_extensions.TypeAlias = ImportVmRequest

@typing.final
class GetMigrationStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    MIGRATION_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    migration_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        migration_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["migration_id", b"migration_id", "vm_id", b"vm_id"]) -> None: ...

Global___GetMigrationStatusRequest: typing_extensions.TypeAlias = GetMigrationStatusRequest

@typing.final
class InitializeConfidentialRequest(google.protobuf.message.Message):
    """── Confidential ─────────────────────────────────────────────────────────"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    SESSION_BYTES_FIELD_NUMBER: builtins.int
    GODH_BYTES_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    session_bytes: builtins.bytes
    """SEV session blob"""
    godh_bytes: builtins.bytes
    """SEV guest-owner DH key"""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        session_bytes: builtins.bytes = ...,
        godh_bytes: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["godh_bytes", b"godh_bytes", "session_bytes", b"session_bytes", "vm_id", b"vm_id"]) -> None: ...

Global___InitializeConfidentialRequest: typing_extensions.TypeAlias = InitializeConfidentialRequest

@typing.final
class InitializeConfidentialResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___InitializeConfidentialResponse: typing_extensions.TypeAlias = InitializeConfidentialResponse

@typing.final
class GetMeasurementRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

Global___GetMeasurementRequest: typing_extensions.TypeAlias = GetMeasurementRequest

@typing.final
class Measurement(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    MEASUREMENT_BYTES_FIELD_NUMBER: builtins.int
    TEE_BACKEND_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    measurement_bytes: builtins.bytes
    """attestation report / SEV launch measure"""
    tee_backend: builtins.str
    """"sev-snp" | "tdx" | ..."""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        measurement_bytes: builtins.bytes = ...,
        tee_backend: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["measurement_bytes", b"measurement_bytes", "tee_backend", b"tee_backend", "vm_id", b"vm_id"]) -> None: ...

Global___Measurement: typing_extensions.TypeAlias = Measurement

@typing.final
class InjectSecretRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    SECRET_HEADER_BYTES_FIELD_NUMBER: builtins.int
    SECRET_BYTES_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    secret_header_bytes: builtins.bytes
    secret_bytes: builtins.bytes
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        secret_header_bytes: builtins.bytes = ...,
        secret_bytes: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["secret_bytes", b"secret_bytes", "secret_header_bytes", b"secret_header_bytes", "vm_id", b"vm_id"]) -> None: ...

Global___InjectSecretRequest: typing_extensions.TypeAlias = InjectSecretRequest

@typing.final
class InjectSecretResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___InjectSecretResponse: typing_extensions.TypeAlias = InjectSecretResponse

@typing.final
class ErrorDetail(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    VM_ID_FIELD_NUMBER: builtins.int
    code: Global___ErrorCode.ValueType
    message: builtins.str
    """human-readable, agent surfaces verbatim"""
    vm_id: builtins.str
    """optional context"""
    def __init__(
        self,
        *,
        code: Global___ErrorCode.ValueType = ...,
        message: builtins.str = ...,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "message", b"message", "vm_id", b"vm_id"]) -> None: ...

Global___ErrorDetail: typing_extensions.TypeAlias = ErrorDetail
