"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
SPDX-License-Identifier: MIT

Aleph VM Hypervisor contract.

This service is the infra-only boundary between the network-agent
(Aleph orchestration: HTTP CRN API, messages, payments, allocations)
and the hypervisor (controllers, hypervisors, networking, systemd,
backups). Reference: docs/plans/2026-05-28-aleph-vm-architecture-
backport-design.md.
"""

import google.protobuf.descriptor

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
