# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hypervisor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hypervisor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10hypervisor.proto\x12\x13\x61leph.hypervisor.v1\"\x0f\n\rHealthRequest\"2\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08vm_count\x18\x02 \x01(\r\"\x14\n\x12GetHostInfoRequest\"\xee\x01\n\x08HostInfo\x12\x11\n\tcpu_count\x18\x01 \x01(\r\x12\x12\n\nmemory_mib\x18\x02 \x01(\x04\x12\x31\n\nnuma_nodes\x18\x03 \x03(\x0b\x32\x1d.aleph.hypervisor.v1.NumaNode\x12,\n\x04gpus\x18\x04 \x03(\x0b\x32\x1e.aleph.hypervisor.v1.GpuDevice\x12\x19\n\x11sev_snp_supported\x18\x05 \x01(\x08\x12\x15\n\rtdx_supported\x18\x06 \x01(\x08\x12\x10\n\x08hostname\x18\x07 \x01(\t\x12\x16\n\x0ekernel_version\x18\x08 \x01(\t\"@\n\x08NumaNode\x12\r\n\x05index\x18\x01 \x01(\r\x12\x11\n\tcpu_count\x18\x02 \x01(\r\x12\x12\n\nmemory_mib\x18\x03 \x01(\x04\"W\n\tGpuDevice\x12\x10\n\x08pci_host\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x16\n\x0esupports_x_vga\x18\x04 \x01(\x08\x32\xb6\x01\n\nHypervisor\x12Q\n\x06Health\x12\".aleph.hypervisor.v1.HealthRequest\x1a#.aleph.hypervisor.v1.HealthResponse\x12U\n\x0bGetHostInfo\x12\'.aleph.hypervisor.v1.GetHostInfoRequest\x1a\x1d.aleph.hypervisor.v1.HostInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hypervisor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=41
  _globals['_HEALTHREQUEST']._serialized_end=56
  _globals['_HEALTHRESPONSE']._serialized_start=58
  _globals['_HEALTHRESPONSE']._serialized_end=108
  _globals['_GETHOSTINFOREQUEST']._serialized_start=110
  _globals['_GETHOSTINFOREQUEST']._serialized_end=130
  _globals['_HOSTINFO']._serialized_start=133
  _globals['_HOSTINFO']._serialized_end=371
  _globals['_NUMANODE']._serialized_start=373
  _globals['_NUMANODE']._serialized_end=437
  _globals['_GPUDEVICE']._serialized_start=439
  _globals['_GPUDEVICE']._serialized_end=526
  _globals['_HYPERVISOR']._serialized_start=529
  _globals['_HYPERVISOR']._serialized_end=711
# @@protoc_insertion_point(module_scope)
