# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hypervisor_pb2 as hypervisor__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hypervisor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HypervisorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/aleph.hypervisor.v1.Hypervisor/Health',
                request_serializer=hypervisor__pb2.HealthRequest.SerializeToString,
                response_deserializer=hypervisor__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetHostInfo = channel.unary_unary(
                '/aleph.hypervisor.v1.Hypervisor/GetHostInfo',
                request_serializer=hypervisor__pb2.GetHostInfoRequest.SerializeToString,
                response_deserializer=hypervisor__pb2.HostInfo.FromString,
                _registered_method=True)
        self.CreateVm = channel.unary_unary(
                '/aleph.hypervisor.v1.Hypervisor/CreateVm',
                request_serializer=hypervisor__pb2.CreateVmRequest.SerializeToString,
                response_deserializer=hypervisor__pb2.VmInfo.FromString,
                _registered_method=True)
        self.GetVm = channel.unary_unary(
                '/aleph.hypervisor.v1.Hypervisor/GetVm',
                request_serializer=hypervisor__pb2.GetVmRequest.SerializeToString,
                response_deserializer=hypervisor__pb2.VmInfo.FromString,
                _registered_method=True)
        self.ListVms = channel.unary_unary(
                '/aleph.hypervisor.v1.Hypervisor/ListVms',
                request_serializer=hypervisor__pb2.ListVmsRequest.SerializeToString,
                response_deserializer=hypervisor__pb2.ListVmsResponse.FromString,
                _registered_method=True)
        self.DeleteVm = channel.unary_unary(
                '/aleph.hypervisor.v1.Hypervisor/DeleteVm',
                request_serializer=hypervisor__pb2.DeleteVmRequest.SerializeToString,
                response_deserializer=hypervisor__pb2.DeleteVmResponse.FromString,
                _registered_method=True)
        self.RebootVm = channel.unary_unary(
                '/aleph.hypervisor.v1.Hypervisor/RebootVm',
                request_serializer=hypervisor__pb2.RebootVmRequest.SerializeToString,
                response_deserializer=hypervisor__pb2.VmInfo.FromString,
                _registered_method=True)
        self.ReinstallVm = channel.unary_unary(
                '/aleph.hypervisor.v1.Hypervisor/ReinstallVm',
                request_serializer=hypervisor__pb2.ReinstallVmRequest.SerializeToString,
                response_deserializer=hypervisor__pb2.VmInfo.FromString,
                _registered_method=True)
        self.AddPortForward = channel.unary_unary(
                '/aleph.hypervisor.v1.Hypervisor/AddPortForward',
                request_serializer=hypervisor__pb2.AddPortForwardRequest.SerializeToString,
                response_deserializer=hypervisor__pb2.PortForwardInfo.FromString,
                _registered_method=True)
        self.RemovePortForward = channel.unary_unary(
                '/aleph.hypervisor.v1.Hypervisor/RemovePortForward',
                request_serializer=hypervisor__pb2.RemovePortForwardRequest.SerializeToString,
                response_deserializer=hypervisor__pb2.RemovePortForwardResponse.FromString,
                _registered_method=True)
        self.ListPortForwards = channel.unary_unary(
                '/aleph.hypervisor.v1.Hypervisor/ListPortForwards',
                request_serializer=hypervisor__pb2.ListPortForwardsRequest.SerializeToString,
                response_deserializer=hypervisor__pb2.ListPortForwardsResponse.FromString,
                _registered_method=True)


class HypervisorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """── Host ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHostInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVm(self, request, context):
        """── VM lifecycle ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RebootVm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReinstallVm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPortForward(self, request, context):
        """── Port forwarding ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePortForward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPortForwards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HypervisorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=hypervisor__pb2.HealthRequest.FromString,
                    response_serializer=hypervisor__pb2.HealthResponse.SerializeToString,
            ),
            'GetHostInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHostInfo,
                    request_deserializer=hypervisor__pb2.GetHostInfoRequest.FromString,
                    response_serializer=hypervisor__pb2.HostInfo.SerializeToString,
            ),
            'CreateVm': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVm,
                    request_deserializer=hypervisor__pb2.CreateVmRequest.FromString,
                    response_serializer=hypervisor__pb2.VmInfo.SerializeToString,
            ),
            'GetVm': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVm,
                    request_deserializer=hypervisor__pb2.GetVmRequest.FromString,
                    response_serializer=hypervisor__pb2.VmInfo.SerializeToString,
            ),
            'ListVms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVms,
                    request_deserializer=hypervisor__pb2.ListVmsRequest.FromString,
                    response_serializer=hypervisor__pb2.ListVmsResponse.SerializeToString,
            ),
            'DeleteVm': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVm,
                    request_deserializer=hypervisor__pb2.DeleteVmRequest.FromString,
                    response_serializer=hypervisor__pb2.DeleteVmResponse.SerializeToString,
            ),
            'RebootVm': grpc.unary_unary_rpc_method_handler(
                    servicer.RebootVm,
                    request_deserializer=hypervisor__pb2.RebootVmRequest.FromString,
                    response_serializer=hypervisor__pb2.VmInfo.SerializeToString,
            ),
            'ReinstallVm': grpc.unary_unary_rpc_method_handler(
                    servicer.ReinstallVm,
                    request_deserializer=hypervisor__pb2.ReinstallVmRequest.FromString,
                    response_serializer=hypervisor__pb2.VmInfo.SerializeToString,
            ),
            'AddPortForward': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPortForward,
                    request_deserializer=hypervisor__pb2.AddPortForwardRequest.FromString,
                    response_serializer=hypervisor__pb2.PortForwardInfo.SerializeToString,
            ),
            'RemovePortForward': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePortForward,
                    request_deserializer=hypervisor__pb2.RemovePortForwardRequest.FromString,
                    response_serializer=hypervisor__pb2.RemovePortForwardResponse.SerializeToString,
            ),
            'ListPortForwards': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPortForwards,
                    request_deserializer=hypervisor__pb2.ListPortForwardsRequest.FromString,
                    response_serializer=hypervisor__pb2.ListPortForwardsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aleph.hypervisor.v1.Hypervisor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aleph.hypervisor.v1.Hypervisor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Hypervisor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.hypervisor.v1.Hypervisor/Health',
            hypervisor__pb2.HealthRequest.SerializeToString,
            hypervisor__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHostInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.hypervisor.v1.Hypervisor/GetHostInfo',
            hypervisor__pb2.GetHostInfoRequest.SerializeToString,
            hypervisor__pb2.HostInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.hypervisor.v1.Hypervisor/CreateVm',
            hypervisor__pb2.CreateVmRequest.SerializeToString,
            hypervisor__pb2.VmInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.hypervisor.v1.Hypervisor/GetVm',
            hypervisor__pb2.GetVmRequest.SerializeToString,
            hypervisor__pb2.VmInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.hypervisor.v1.Hypervisor/ListVms',
            hypervisor__pb2.ListVmsRequest.SerializeToString,
            hypervisor__pb2.ListVmsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.hypervisor.v1.Hypervisor/DeleteVm',
            hypervisor__pb2.DeleteVmRequest.SerializeToString,
            hypervisor__pb2.DeleteVmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RebootVm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.hypervisor.v1.Hypervisor/RebootVm',
            hypervisor__pb2.RebootVmRequest.SerializeToString,
            hypervisor__pb2.VmInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReinstallVm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.hypervisor.v1.Hypervisor/ReinstallVm',
            hypervisor__pb2.ReinstallVmRequest.SerializeToString,
            hypervisor__pb2.VmInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPortForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.hypervisor.v1.Hypervisor/AddPortForward',
            hypervisor__pb2.AddPortForwardRequest.SerializeToString,
            hypervisor__pb2.PortForwardInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemovePortForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.hypervisor.v1.Hypervisor/RemovePortForward',
            hypervisor__pb2.RemovePortForwardRequest.SerializeToString,
            hypervisor__pb2.RemovePortForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPortForwards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.hypervisor.v1.Hypervisor/ListPortForwards',
            hypervisor__pb2.ListPortForwardsRequest.SerializeToString,
            hypervisor__pb2.ListPortForwardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
