# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hypervisor_pb2 as hypervisor__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hypervisor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HypervisorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/aleph.hypervisor.v1.Hypervisor/Health',
                request_serializer=hypervisor__pb2.HealthRequest.SerializeToString,
                response_deserializer=hypervisor__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetHostInfo = channel.unary_unary(
                '/aleph.hypervisor.v1.Hypervisor/GetHostInfo',
                request_serializer=hypervisor__pb2.GetHostInfoRequest.SerializeToString,
                response_deserializer=hypervisor__pb2.HostInfo.FromString,
                _registered_method=True)


class HypervisorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """── Host ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHostInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HypervisorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=hypervisor__pb2.HealthRequest.FromString,
                    response_serializer=hypervisor__pb2.HealthResponse.SerializeToString,
            ),
            'GetHostInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHostInfo,
                    request_deserializer=hypervisor__pb2.GetHostInfoRequest.FromString,
                    response_serializer=hypervisor__pb2.HostInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aleph.hypervisor.v1.Hypervisor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aleph.hypervisor.v1.Hypervisor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Hypervisor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.hypervisor.v1.Hypervisor/Health',
            hypervisor__pb2.HealthRequest.SerializeToString,
            hypervisor__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHostInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.hypervisor.v1.Hypervisor/GetHostInfo',
            hypervisor__pb2.GetHostInfoRequest.SerializeToString,
            hypervisor__pb2.HostInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
