#!/bin/bash
set -euf -o pipefail

if ! id -u jailman > /dev/null 2>&1; then
  useradd jailman
fi

mkdir -p /srv/jailer

systemctl daemon-reload
systemctl enable aleph-vm-supervisor.service
systemctl restart aleph-vm-supervisor.service
