#!/bin/bash
set -uf -o pipefail

# Documentation: https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html

# Systemd is absent from containers
if ! [[ -v container ]]; then
  # Stop the service during an upgrade.
  # The service does not exist during a new install and will fail, this is okay
  systemctl stop aleph-vm-supervisor.service
fi

set -e


