//! Parser for the on-disk controller configuration files
//! (`{EXECUTION_ROOT}/{vm_hash}-controller.json`).
//!
//! The JSON shape is defined by the pydantic models in
//! `src/aleph/vm/supervisor_interface/configuration.py`: `Configuration`
//! wrapping the 9-field `ControllerSettings` slice (PR #1016) and a
//! `vm_configuration` union. The union is resolved by SHAPE, the way
//! pydantic's smart union does for these models; the `hypervisor` field is
//! validated (unknown values fail) but does NOT drive the resolution
//! (probe-confirmed against the Python models: a QEMU-shaped payload with
//! `hypervisor: firecracker`, or with the key absent, still validates as a
//! QEMU configuration and is adopted). Within the QEMU shape,
//! `QemuConfidentialVMConfiguration` validates only when all four
//! confidential fields are present, so a QEMU payload is confidential
//! exactly when `ovmf_path`, `sev_session_file`, `sev_dh_cert_file` and
//! `sev_policy` all appear; otherwise it is a plain `QemuVMConfiguration`.
//! A payload that only fits `VMConfiguration` (Firecracker) is carried as
//! the unsupported variant, which adoption skips (mirroring the Python
//! `spec_from_controller_configuration`, which raises InvalidBackendError
//! for it); a payload fitting no union member fails the whole config, like
//! the pydantic ValidationError.
//!
//! Like the pydantic models (`extra="ignore"`, defaulted slice fields),
//! unknown keys are ignored and absent slice keys fall back to the conf.py
//! defaults; known keys with invalid values fail loudly.
//!
//! Test fixtures under `tests/fixtures/` are generated by the actual Python
//! models (`scripts/generate_rust_fixtures.py`), never hand-written.

use std::path::PathBuf;

use serde::{Deserialize, Deserializer};

/// A parse failure for one controller config file. The world view logs it
/// and skips the VM; it never aborts the daemon (the Python crash-loop
/// lesson behind PR #1016).
#[derive(Debug, thiserror::Error)]
#[error("{0}")]
pub struct ConfigParseError(pub String);

/// `ControllerSettings`: the node-settings slice a controller reads.
/// Defaults mirror conf.py so keys absent from an old dump fall back
/// instead of failing.
#[derive(Debug, Clone, Deserialize)]
#[serde(default)]
pub struct ControllerSettingsSlice {
    #[serde(rename = "JAILER_BASE_DIR")]
    pub jailer_base_dir: Option<PathBuf>,
    #[serde(rename = "NETWORK_INTERFACE")]
    pub network_interface: Option<String>,
    #[serde(rename = "IPV4_ADDRESS_POOL")]
    pub ipv4_address_pool: String,
    #[serde(rename = "IPV4_NETWORK_PREFIX_LENGTH")]
    pub ipv4_network_prefix_length: u8,
    #[serde(rename = "IPV6_ADDRESS_POOL")]
    pub ipv6_address_pool: String,
    #[serde(rename = "IPV6_ALLOCATION_POLICY")]
    pub ipv6_allocation_policy: AllocationPolicyValue,
    #[serde(rename = "IPV6_SUBNET_PREFIX")]
    pub ipv6_subnet_prefix: u8,
    #[serde(rename = "IPV6_FORWARDING_ENABLED")]
    pub ipv6_forwarding_enabled: bool,
    #[serde(rename = "USE_NDP_PROXY")]
    pub use_ndp_proxy: bool,
}

impl Default for ControllerSettingsSlice {
    fn default() -> Self {
        Self {
            jailer_base_dir: None,
            network_interface: None,
            ipv4_address_pool: "172.16.0.0/12".to_string(),
            ipv4_network_prefix_length: 24,
            ipv6_address_pool: "fc00:1:2:3::/64".to_string(),
            ipv6_allocation_policy: AllocationPolicyValue::Static,
            ipv6_subnet_prefix: 124,
            ipv6_forwarding_enabled: true,
            use_ndp_proxy: true,
        }
    }
}

/// The `IPv6AllocationPolicy` str-enum values, validated like pydantic
/// (an unknown value is an error, not a fallback).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, serde::Serialize)]
pub enum AllocationPolicyValue {
    #[serde(rename = "static")]
    Static,
    #[serde(rename = "dynamic")]
    Dynamic,
}

/// One `QemuVMHostVolume` entry. `mount` is carried for shape completeness
/// only; QemuVM never consumed it and it is written empty since the spec
/// path.
#[derive(Debug, Clone, Deserialize)]
pub struct QemuHostVolume {
    #[serde(default)]
    pub mount: String,
    pub path_on_host: String,
    pub read_only: bool,
}

/// One `QemuGPU` entry. `supports_x_vga` defaults to true like the pydantic
/// field (backward compatibility with configs that predate it).
#[derive(Debug, Clone, Deserialize)]
pub struct QemuGpu {
    pub pci_host: String,
    #[serde(default = "default_true")]
    pub supports_x_vga: bool,
}

fn default_true() -> bool {
    true
}

/// The four fields `QemuConfidentialVMConfiguration` adds over the plain
/// `QemuVMConfiguration`.
#[derive(Debug, Clone)]
pub struct ConfidentialConfig {
    pub ovmf_path: String,
    pub sev_session_file: String,
    pub sev_dh_cert_file: String,
    pub sev_policy: u32,
}

/// The SEV-SNP measured-boot slice (increment B1). Distinct from
/// [`ConfidentialConfig`]: SNP carries no session/godh (secrets are injected at
/// runtime over the attested channel), and it is a direct-kernel boot, so it
/// carries the measured kernel/initrd/cmdline instead. `ovmf_path` is the
/// measured OVMF, `sev_policy` the SNP policy (default 0x30000 upstream).
#[derive(Debug, Clone)]
pub struct SnpConfig {
    pub ovmf_path: String,
    pub kernel_path: String,
    pub initrd_path: String,
    pub kernel_cmdline: String,
    pub sev_policy: u32,
}

/// `QemuVMConfiguration` / `QemuConfidentialVMConfiguration` (the plain
/// fields are shared; the confidential four are optional here and resolved
/// by [`QemuVmConfig::confidential`]).
#[derive(Debug, Clone, Deserialize)]
pub struct QemuVmConfig {
    pub qemu_bin_path: String,
    #[serde(default)]
    pub cloud_init_drive_path: Option<String>,
    pub image_path: String,
    pub monitor_socket_path: String,
    pub qmp_socket_path: String,
    #[serde(default)]
    pub qga_socket_path: Option<String>,
    pub vcpu_count: u32,
    #[serde(deserialize_with = "deserialize_mem_size_mib")]
    pub mem_size_mb: u64,
    #[serde(default)]
    pub interface_name: Option<String>,
    pub host_volumes: Vec<QemuHostVolume>,
    pub gpus: Vec<QemuGpu>,

    // Confidential slice; all four present means the payload is a
    // QemuConfidentialVMConfiguration (pydantic union order: the
    // confidential model is tried first and requires them all).
    #[serde(default)]
    ovmf_path: Option<String>,
    #[serde(default)]
    sev_session_file: Option<String>,
    #[serde(default)]
    sev_dh_cert_file: Option<String>,
    #[serde(default)]
    sev_policy: Option<u32>,

    // SEV-SNP measured-boot slice (increment B1). `sev_snp: true` is the
    // explicit backend marker; when set, ovmf_path/sev_policy plus these three
    // are all present. Rust-only fields (no Python controller SNP path).
    #[serde(default)]
    sev_snp: Option<bool>,
    #[serde(default)]
    kernel_path: Option<String>,
    #[serde(default)]
    initrd_path: Option<String>,
    #[serde(default)]
    kernel_cmdline: Option<String>,

    // NUMA memory binding + hugepages (increment C2), Rust-only. Present when
    // the supervisor placed this VM on a node; the controller then binds guest
    // RAM to it. Carried here so an adopted config round-trips, though the
    // daemon's own source of truth for placement is `VmEntry.numa_node` + the
    // AllowedCPUs drop-in (reconcile), not this field. `pub` (informational):
    // the daemon does not consume them, but a config on disk carries them.
    #[serde(default)]
    pub numa_node: Option<u32>,
    #[serde(default)]
    pub hugepage_size: Option<String>,
}

impl QemuVmConfig {
    /// The synthesized record an ephemeral program's world entry carries
    /// (see `VmEntry::config`): only the fields the shared accounting
    /// paths read (memory backstop, networking_enabled, GPU exclusion)
    /// are meaningful. Never written to disk.
    pub fn for_program(mem_size_mb: u64, interface_name: Option<String>) -> Self {
        Self {
            qemu_bin_path: String::new(),
            cloud_init_drive_path: None,
            image_path: String::new(),
            monitor_socket_path: String::new(),
            qmp_socket_path: String::new(),
            qga_socket_path: None,
            vcpu_count: 0,
            mem_size_mb,
            interface_name,
            host_volumes: Vec::new(),
            gpus: Vec::new(),
            ovmf_path: None,
            sev_session_file: None,
            sev_dh_cert_file: None,
            sev_policy: None,
            sev_snp: None,
            kernel_path: None,
            initrd_path: None,
            kernel_cmdline: None,
            numa_node: None,
            hugepage_size: None,
        }
    }

    /// The confidential slice when this is a
    /// `QemuConfidentialVMConfiguration`, `None` for a plain QEMU config OR an
    /// SEV-SNP config (SNP carries no session/godh, so it is not confidential
    /// in this SEV sense; use [`QemuVmConfig::snp`] for it).
    pub fn confidential(&self) -> Option<ConfidentialConfig> {
        match (
            &self.ovmf_path,
            &self.sev_session_file,
            &self.sev_dh_cert_file,
            self.sev_policy,
        ) {
            (Some(ovmf), Some(session), Some(dh_cert), Some(policy)) => Some(ConfidentialConfig {
                ovmf_path: ovmf.clone(),
                sev_session_file: session.clone(),
                sev_dh_cert_file: dh_cert.clone(),
                sev_policy: policy,
            }),
            _ => None,
        }
    }

    /// The SEV-SNP measured-boot slice when this is an SNP config (`sev_snp`
    /// marker set with all measured-boot fields present), `None` otherwise. The
    /// daemon writer always fills the fields together, so a marker with a
    /// missing field yields `None` (treated as non-SNP, fail-closed).
    pub fn snp(&self) -> Option<SnpConfig> {
        if self.sev_snp != Some(true) {
            return None;
        }
        match (
            &self.ovmf_path,
            &self.kernel_path,
            &self.initrd_path,
            &self.kernel_cmdline,
            self.sev_policy,
        ) {
            (Some(ovmf), Some(kernel), Some(initrd), Some(cmdline), Some(policy)) => {
                Some(SnpConfig {
                    ovmf_path: ovmf.clone(),
                    kernel_path: kernel.clone(),
                    initrd_path: initrd.clone(),
                    kernel_cmdline: cmdline.clone(),
                    sev_policy: policy,
                })
            }
            _ => None,
        }
    }
}

/// `MemSizeMib` reads with the coercion of the Python `_coerce_mib`
/// (`MiB(int(value))`): an integer, a float JSON number (Python's `int()`
/// truncates) or an INTEGER string. A float STRING like "2048.5" raises in
/// Python's `int(value)` and makes the whole config unparseable; it is
/// rejected here too.
fn deserialize_mem_size_mib<'de, D>(deserializer: D) -> Result<u64, D::Error>
where
    D: Deserializer<'de>,
{
    let value = serde_json::Value::deserialize(deserializer)?;
    let parsed = match &value {
        serde_json::Value::Number(number) => number
            .as_u64()
            .or_else(|| number.as_f64().map(|float| float as u64)),
        serde_json::Value::String(text) => text.trim().parse::<u64>().ok(),
        _ => None,
    };
    parsed.ok_or_else(|| serde::de::Error::custom(format!("cannot coerce {value} to MiB")))
}

/// The resolved `vm_configuration` union member.
#[derive(Debug, Clone)]
pub enum VmConfiguration {
    Qemu(Box<QemuVmConfig>),
    /// A `VMConfiguration` (Firecracker) payload. Adoption is QEMU-only:
    /// the world view reports these and leaves them alone, exactly like the
    /// Python reattach (spec_from_controller_configuration raises
    /// InvalidBackendError, isolating the VM as a failed reattach).
    Firecracker,
}

/// The `VMConfiguration` (Firecracker) shape, deserialized only to decide
/// whether a non-QEMU payload is a valid union member (pydantic parity) or
/// garbage that fails the whole `Configuration`. Field values are unused.
#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct FirecrackerShape {
    use_jailer: bool,
    firecracker_bin_path: String,
    jailer_bin_path: String,
    config_file_path: String,
    init_timeout: f64,
}

/// The top-level `Configuration` model.
#[derive(Debug, Clone)]
pub struct ControllerConfig {
    /// `Configuration.vm_id`: the vm_index (tap interface / IPv4 range id).
    pub vm_index: i64,
    /// `Configuration.vm_hash`: the VM item hash, our world-view key.
    pub vm_hash: String,
    pub settings: ControllerSettingsSlice,
    pub vm: VmConfiguration,
}

#[derive(Debug, Deserialize)]
struct RawConfiguration {
    vm_id: i64,
    vm_hash: String,
    settings: ControllerSettingsSlice,
    vm_configuration: serde_json::Value,
    // The pydantic default is HypervisorType.firecracker.
    #[serde(default = "default_hypervisor")]
    hypervisor: String,
}

fn default_hypervisor() -> String {
    "firecracker".to_string()
}

/// Parse one controller configuration file's JSON contents.
pub fn parse_controller_config(json: &str) -> Result<ControllerConfig, ConfigParseError> {
    let raw: RawConfiguration = serde_json::from_str(json)
        .map_err(|error| ConfigParseError(format!("invalid Configuration JSON: {error}")))?;
    // The hypervisor field is validated like the pydantic HypervisorType
    // enum, but it does not pick the union member (see the module docs).
    if raw.hypervisor != "qemu" && raw.hypervisor != "firecracker" {
        return Err(ConfigParseError(format!(
            "unknown hypervisor {:?}",
            raw.hypervisor
        )));
    }
    // Shape-based union resolution, like pydantic's smart union over
    // QemuConfidentialVMConfiguration | QemuVMConfiguration |
    // VMConfiguration (the two QEMU members are one struct here, the
    // confidential slice being optional).
    let vm = match serde_json::from_value::<QemuVmConfig>(raw.vm_configuration.clone()) {
        Ok(config) => VmConfiguration::Qemu(Box::new(config)),
        Err(qemu_error) => match serde_json::from_value::<FirecrackerShape>(raw.vm_configuration) {
            Ok(_) => VmConfiguration::Firecracker,
            Err(firecracker_error) => {
                return Err(ConfigParseError(format!(
                    "vm_configuration fits no union member: \
                     not QEMU ({qemu_error}); not Firecracker ({firecracker_error})"
                )));
            }
        },
    };
    Ok(ControllerConfig {
        vm_index: raw.vm_id,
        vm_hash: raw.vm_hash,
        settings: raw.settings,
        vm,
    })
}

// ── Writer (the create path) ────────────────────────────────────────────
//
// The increment 3 counterpart of the parser above: CreateVm writes the
// `Configuration` JSON the controller reads, byte-identical to
// `save_controller_configuration` (pydantic model_dump_json(by_alias=True,
// exclude_none=True, indent=4)), so a rollback to the Python daemon
// reparses these files unchanged. Field order follows the pydantic model
// declarations; the committed fixture `written-controller-config.json`
// (generated by the actual models) pins the bytes.

use serde::Serialize;

/// `ControllerSettings` as written. Only JAILER_BASE_DIR / NETWORK_INTERFACE
/// can be None, and exclude_none drops them then.
#[derive(Debug, Clone, Serialize)]
pub struct WrittenControllerSettings {
    #[serde(rename = "JAILER_BASE_DIR", skip_serializing_if = "Option::is_none")]
    pub jailer_base_dir: Option<String>,
    #[serde(rename = "NETWORK_INTERFACE", skip_serializing_if = "Option::is_none")]
    pub network_interface: Option<String>,
    #[serde(rename = "IPV4_ADDRESS_POOL")]
    pub ipv4_address_pool: String,
    #[serde(rename = "IPV4_NETWORK_PREFIX_LENGTH")]
    pub ipv4_network_prefix_length: u8,
    #[serde(rename = "IPV6_ADDRESS_POOL")]
    pub ipv6_address_pool: String,
    #[serde(rename = "IPV6_ALLOCATION_POLICY")]
    pub ipv6_allocation_policy: AllocationPolicyValue,
    #[serde(rename = "IPV6_SUBNET_PREFIX")]
    pub ipv6_subnet_prefix: u8,
    #[serde(rename = "IPV6_FORWARDING_ENABLED")]
    pub ipv6_forwarding_enabled: bool,
    #[serde(rename = "USE_NDP_PROXY")]
    pub use_ndp_proxy: bool,
}

#[derive(Debug, Clone, Serialize)]
pub struct WrittenHostVolume {
    pub mount: String,
    pub path_on_host: String,
    pub read_only: bool,
}

#[derive(Debug, Clone, Serialize)]
pub struct WrittenGpu {
    pub pci_host: String,
    pub supports_x_vga: bool,
}

/// `QemuVMConfiguration` as `build_qemu_configuration` fills it. Every
/// Option is set on the create path; the skips only guard exclude_none
/// parity for hypothetical absent values.
#[derive(Debug, Clone, Serialize)]
pub struct WrittenQemuVmConfiguration {
    pub qemu_bin_path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cloud_init_drive_path: Option<String>,
    pub image_path: String,
    pub monitor_socket_path: String,
    pub qmp_socket_path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub qga_socket_path: Option<String>,
    pub vcpu_count: u32,
    pub mem_size_mb: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub interface_name: Option<String>,
    pub host_volumes: Vec<WrittenHostVolume>,
    pub gpus: Vec<WrittenGpu>,
    // The QemuConfidentialVMConfiguration slice (increment 6). Declared after
    // gpus, matching the pydantic model field order; all four are present for
    // a confidential VM and absent (exclude_none) for a plain one.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ovmf_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sev_session_file: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sev_dh_cert_file: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sev_policy: Option<u32>,
    // SEV-SNP measured-boot slice (increment B1), Rust-only. All None (and so
    // omitted) for plain and SEV/SEV-ES configs, keeping their bytes identical
    // to the pydantic writer; for an SNP VM the daemon sets sev_snp:true plus
    // the measured kernel/initrd/cmdline (ovmf_path/sev_policy are shared).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sev_snp: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kernel_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub initrd_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kernel_cmdline: Option<String>,
    // NUMA memory binding + hugepages slice (increment C2), Rust-only. Both
    // None (and so omitted via exclude_none) for single-node / no-NUMA /
    // unplaced VMs, keeping their bytes identical to the pydantic writer and to
    // pre-C2; set together when the supervisor placed the VM on a node (and, if
    // hugepages are enabled and available, chose a page size).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub numa_node: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hugepage_size: Option<String>,
}

/// The top-level `Configuration` as written (QEMU instances only in this
/// increment).
#[derive(Debug, Clone, Serialize)]
pub struct WrittenControllerConfig {
    /// `Configuration.vm_id`: the vm_index.
    pub vm_id: i64,
    pub vm_hash: String,
    pub settings: WrittenControllerSettings,
    pub vm_configuration: WrittenQemuVmConfiguration,
    pub hypervisor: &'static str,
}

impl WrittenControllerConfig {
    /// pydantic `model_dump_json(by_alias=True, exclude_none=True,
    /// indent=4)`.
    pub fn to_json(&self) -> String {
        let mut buffer = Vec::new();
        let formatter = serde_json::ser::PrettyFormatter::with_indent(b"    ");
        let mut serializer = serde_json::Serializer::with_formatter(&mut buffer, formatter);
        self.serialize(&mut serializer)
            .expect("controller configs always serialize");
        String::from_utf8(buffer).expect("serde_json emits UTF-8")
    }
}

/// The config file path, `{EXECUTION_ROOT}/{vm_hash}-controller.json`.
pub fn controller_config_path(execution_root: &std::path::Path, vm_hash: &str) -> PathBuf {
    execution_root.join(format!("{vm_hash}-controller.json"))
}

/// Python `save_controller_configuration`: atomic write (temp file in the
/// same directory, fsync, rename) so a scanning daemon never sees a
/// truncated config; the temp name never ends in "-controller.json".
pub fn save_controller_config(
    execution_root: &std::path::Path,
    config: &WrittenControllerConfig,
) -> Result<PathBuf, String> {
    use std::io::Write;
    let path = controller_config_path(execution_root, &config.vm_hash);
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .expect("config paths carry a file name");
    let mut temp = tempfile::Builder::new()
        .prefix(&format!(".{file_name}."))
        .suffix(".tmp")
        .tempfile_in(execution_root)
        .map_err(|error| format!("cannot create a temp config file: {error}"))?;
    temp.write_all(config.to_json().as_bytes())
        .and_then(|_| temp.flush())
        .and_then(|_| temp.as_file().sync_all())
        .map_err(|error| format!("cannot write the controller config: {error}"))?;
    // Python chmods 0644 before the rename (mkstemp creates 0600).
    std::fs::set_permissions(temp.path(), {
        use std::os::unix::fs::PermissionsExt;
        std::fs::Permissions::from_mode(0o644)
    })
    .map_err(|error| format!("cannot chmod the controller config: {error}"))?;
    temp.persist(&path)
        .map_err(|error| format!("cannot move the controller config in place: {error}"))?;
    Ok(path)
}

/// Python `remove_controller_configuration`: the on-disk artifacts that
/// define a VM across restarts (config, cloud-init seed, dead qemu control
/// sockets). Delete-path only; a stopped VM keeps them. A missing file is
/// tolerated (Python's `unlink(missing_ok=True)`); any other unlink error
/// propagates and fails the caller, exactly like the Python unlink.
pub fn remove_controller_configuration(
    execution_root: &std::path::Path,
    vm_hash: &str,
) -> Result<(), String> {
    let mut paths = vec![
        controller_config_path(execution_root, vm_hash),
        execution_root.join(format!("cloud-init-{vm_hash}.img")),
    ];
    for socket_kind in ["monitor", "qmp", "qga"] {
        paths.push(execution_root.join(format!("{vm_hash}-{socket_kind}.socket")));
    }
    for path in paths {
        if let Err(error) = std::fs::remove_file(&path)
            && error.kind() != std::io::ErrorKind::NotFound
        {
            return Err(format!(
                "cannot remove the VM artifact {}: {error}",
                path.display()
            ));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture(name: &str) -> String {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures")
            .join(name);
        std::fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("cannot read fixture {}: {error}", path.display()))
    }

    #[test]
    fn parses_the_plain_qemu_fixture() {
        let name = format!("{}-controller.json", crate::test_fixtures::QEMU_HASH);
        let config = parse_controller_config(&fixture(&name)).unwrap();
        assert_eq!(config.vm_hash, crate::test_fixtures::QEMU_HASH);
        assert_eq!(config.vm_index, 3);
        assert_eq!(config.settings.ipv4_address_pool, "172.16.0.0/12");
        assert_eq!(config.settings.ipv4_network_prefix_length, 24);
        assert_eq!(config.settings.ipv6_address_pool, "fc00:1:2:3::/64");
        assert_eq!(
            config.settings.ipv6_allocation_policy,
            AllocationPolicyValue::Static
        );
        assert_eq!(config.settings.ipv6_subnet_prefix, 124);
        assert!(config.settings.ipv6_forwarding_enabled);
        assert!(config.settings.use_ndp_proxy);
        let VmConfiguration::Qemu(vm) = &config.vm else {
            panic!("expected a QEMU configuration");
        };
        assert_eq!(vm.vcpu_count, 2);
        assert_eq!(vm.mem_size_mb, 2048);
        assert_eq!(vm.interface_name.as_deref(), Some("vmtap3"));
        assert!(vm.image_path.ends_with("rootfs.qcow2"));
        assert_eq!(vm.host_volumes.len(), 1);
        assert!(!vm.host_volumes[0].read_only);
        assert!(vm.gpus.is_empty());
        assert!(vm.confidential().is_none());
    }

    #[test]
    fn parses_the_gpu_fixture() {
        let name = format!("{}-controller.json", crate::test_fixtures::GPU_HASH);
        let config = parse_controller_config(&fixture(&name)).unwrap();
        let VmConfiguration::Qemu(vm) = &config.vm else {
            panic!("expected a QEMU configuration");
        };
        assert_eq!(vm.gpus.len(), 1);
        assert_eq!(vm.gpus[0].pci_host, "0000:01:00.0");
        assert!(vm.gpus[0].supports_x_vga);
        assert!(vm.confidential().is_none());
    }

    #[test]
    fn parses_the_confidential_fixture() {
        let name = format!(
            "{}-controller.json",
            crate::test_fixtures::CONFIDENTIAL_HASH
        );
        let config = parse_controller_config(&fixture(&name)).unwrap();
        let VmConfiguration::Qemu(vm) = &config.vm else {
            panic!("expected a QEMU configuration");
        };
        let confidential = vm.confidential().expect("must resolve as confidential");
        assert_eq!(confidential.sev_policy, 0x5);
        assert!(confidential.ovmf_path.ends_with("OVMF_CSV.fd"));
        assert!(confidential.sev_session_file.ends_with("vm_session.b64"));
        assert!(confidential.sev_dh_cert_file.ends_with("vm_godh.b64"));
    }

    #[test]
    fn an_snp_config_resolves_as_snp_not_sev() {
        // The SNP measured-boot slice: sev_snp marker + ovmf/policy shared with
        // the SEV slot + the measured kernel/initrd/cmdline. It must NOT resolve
        // as a SEV confidential config (no session/godh), and snp() must carry
        // the measured fields.
        let json = r#"{
            "vm_id": 9, "vm_hash": "abcd", "settings": {},
            "hypervisor": "qemu",
            "vm_configuration": {
                "qemu_bin_path": "/usr/bin/qemu-system-x86_64",
                "image_path": "/img/rootfs.ext4",
                "monitor_socket_path": "/m.sock", "qmp_socket_path": "/q.sock",
                "vcpu_count": 2, "mem_size_mb": 2048,
                "host_volumes": [], "gpus": [],
                "sev_snp": true,
                "ovmf_path": "/img/OVMF.fd",
                "sev_policy": 196608,
                "kernel_path": "/img/bzImage",
                "initrd_path": "/img/initrd",
                "kernel_cmdline": "console=ttyS0 root=/dev/mapper/verity-root ro roothash=abc"
            }
        }"#;
        let config = parse_controller_config(json).unwrap();
        let VmConfiguration::Qemu(vm) = &config.vm else {
            panic!("expected a QEMU configuration");
        };
        assert!(
            vm.confidential().is_none(),
            "SNP is not a SEV confidential config"
        );
        let snp = vm.snp().expect("must resolve as SNP");
        assert_eq!(snp.ovmf_path, "/img/OVMF.fd");
        assert_eq!(snp.sev_policy, 0x30000);
        assert_eq!(snp.kernel_path, "/img/bzImage");
        assert_eq!(snp.initrd_path, "/img/initrd");
        assert_eq!(
            snp.kernel_cmdline,
            "console=ttyS0 root=/dev/mapper/verity-root ro roothash=abc"
        );

        // A SEV config (no sev_snp marker) never resolves as SNP.
        let name = format!(
            "{}-controller.json",
            crate::test_fixtures::CONFIDENTIAL_HASH
        );
        let sev = parse_controller_config(&fixture(&name)).unwrap();
        let VmConfiguration::Qemu(sev_vm) = &sev.vm else {
            panic!("expected a QEMU configuration");
        };
        assert!(sev_vm.snp().is_none(), "a SEV config is not SNP");
    }

    #[test]
    fn a_firecracker_config_resolves_to_the_unsupported_variant() {
        let json = r#"{
            "vm_id": 7,
            "vm_hash": "deadbeef",
            "settings": {},
            "vm_configuration": {
                "use_jailer": true,
                "firecracker_bin_path": "/opt/firecracker/firecracker",
                "jailer_bin_path": "/opt/firecracker/jailer",
                "config_file_path": "/var/lib/aleph/vm/deadbeef.json",
                "init_timeout": 5.0
            },
            "hypervisor": "firecracker"
        }"#;
        let config = parse_controller_config(json).unwrap();
        assert!(matches!(config.vm, VmConfiguration::Firecracker));
    }

    #[test]
    fn a_firecracker_shaped_payload_without_the_hypervisor_field_still_resolves() {
        // Configs predating the field (pydantic default: firecracker); the
        // union is resolved by shape either way.
        let json = r#"{
            "vm_id": 1,
            "vm_hash": "aa",
            "settings": {},
            "vm_configuration": {
                "use_jailer": true,
                "firecracker_bin_path": "/opt/firecracker/firecracker",
                "jailer_bin_path": "/opt/firecracker/jailer",
                "config_file_path": "/var/lib/aleph/vm/aa.json",
                "init_timeout": 5.0
            }
        }"#;
        let config = parse_controller_config(json).unwrap();
        assert!(matches!(config.vm, VmConfiguration::Firecracker));
    }

    #[test]
    fn the_union_is_resolved_by_shape_not_by_the_hypervisor_field() {
        // Probe-confirmed pydantic behavior: a QEMU-shaped payload with
        // hypervisor "firecracker", or with the key absent, still validates
        // as a QemuVMConfiguration and is adopted as QEMU.
        let name = format!("{}-controller.json", crate::test_fixtures::QEMU_HASH);
        let mut value: serde_json::Value = serde_json::from_str(&fixture(&name)).unwrap();

        value["hypervisor"] = "firecracker".into();
        let config = parse_controller_config(&value.to_string()).unwrap();
        assert!(matches!(config.vm, VmConfiguration::Qemu(_)));

        value.as_object_mut().unwrap().remove("hypervisor");
        let config = parse_controller_config(&value.to_string()).unwrap();
        assert!(matches!(config.vm, VmConfiguration::Qemu(_)));
    }

    #[test]
    fn a_payload_fitting_no_union_member_fails_the_whole_config() {
        // pydantic parity: vm_configuration must validate as one union
        // member or the whole Configuration raises (Rust: the VM is then
        // skipped per ledger entry 12).
        let json = r#"{"vm_id": 1, "vm_hash": "aa", "settings": {}, "vm_configuration": {}}"#;
        assert!(parse_controller_config(json).is_err());
    }

    #[test]
    fn unknown_keys_are_ignored_like_extra_ignore() {
        // Old configs embedded a full Settings dump; surplus keys are
        // ignored on read (the 1.13.0 CONNECTIVITY_DNS_HOSTNAME lesson).
        let name = format!("{}-controller.json", crate::test_fixtures::QEMU_HASH);
        let mut value: serde_json::Value = serde_json::from_str(&fixture(&name)).unwrap();
        value["settings"]["CONNECTIVITY_DNS_HOSTNAME"] = "example.org".into();
        value["vm_configuration"]["surplus_key"] = 42.into();
        assert!(parse_controller_config(&value.to_string()).is_ok());
    }

    #[test]
    fn invalid_json_and_invalid_values_are_errors() {
        assert!(parse_controller_config("not json").is_err());
        // A known key with an invalid value fails loudly, like pydantic.
        let json = r#"{
            "vm_id": 1,
            "vm_hash": "aa",
            "settings": {"IPV6_ALLOCATION_POLICY": "sometimes"},
            "vm_configuration": {},
            "hypervisor": "firecracker"
        }"#;
        assert!(parse_controller_config(json).is_err());
    }

    #[test]
    fn mem_size_accepts_pydantic_lax_forms() {
        let name = format!("{}-controller.json", crate::test_fixtures::QEMU_HASH);
        let mut value: serde_json::Value = serde_json::from_str(&fixture(&name)).unwrap();
        for lax in [
            serde_json::Value::from("2048"),
            serde_json::Value::from(2048.0),
            // Python's int() truncates a float JSON number.
            serde_json::Value::from(2048.7),
        ] {
            value["vm_configuration"]["mem_size_mb"] = lax;
            let config = parse_controller_config(&value.to_string()).unwrap();
            let VmConfiguration::Qemu(vm) = &config.vm else {
                panic!("expected a QEMU configuration");
            };
            assert_eq!(vm.mem_size_mb, 2048);
        }
    }

    #[test]
    fn the_writer_matches_pydantic_byte_for_byte() {
        // written-controller-config.json is what
        // save_controller_configuration writes for these exact inputs
        // (generated by the actual pydantic models); the Rust writer must
        // reproduce it byte for byte so a rollback to the Python daemon
        // reparses Rust-written files unchanged.
        let hash = crate::test_fixtures::CREATED_HASH;
        let root = "/var/lib/aleph/vm";
        let config = WrittenControllerConfig {
            vm_id: 6,
            vm_hash: hash.to_string(),
            settings: WrittenControllerSettings {
                jailer_base_dir: Some(format!("{root}/jailer")),
                network_interface: Some("eth0".to_string()),
                ipv4_address_pool: "172.16.0.0/12".to_string(),
                ipv4_network_prefix_length: 24,
                ipv6_address_pool: "fc00:1:2:3::/64".to_string(),
                ipv6_allocation_policy: AllocationPolicyValue::Static,
                ipv6_subnet_prefix: 124,
                ipv6_forwarding_enabled: true,
                use_ndp_proxy: true,
            },
            vm_configuration: WrittenQemuVmConfiguration {
                qemu_bin_path: "/usr/bin/qemu-system-x86_64".to_string(),
                cloud_init_drive_path: Some(format!("{root}/cloud-init-{hash}.img")),
                image_path: format!("{root}/volumes/persistent/{hash}/rootfs.qcow2"),
                monitor_socket_path: format!("{root}/{hash}-monitor.socket"),
                qmp_socket_path: format!("{root}/{hash}-qmp.socket"),
                qga_socket_path: Some(format!("{root}/{hash}-qga.socket")),
                vcpu_count: 2,
                mem_size_mb: 2048,
                interface_name: Some("vmtap6".to_string()),
                host_volumes: vec![WrittenHostVolume {
                    mount: String::new(),
                    path_on_host: format!("{root}/volumes/persistent/{hash}/data.qcow2"),
                    read_only: false,
                }],
                gpus: vec![WrittenGpu {
                    pci_host: "0000:01:00.0".to_string(),
                    supports_x_vga: true,
                }],
                ovmf_path: None,
                sev_session_file: None,
                sev_dh_cert_file: None,
                sev_policy: None,
                sev_snp: None,
                kernel_path: None,
                initrd_path: None,
                kernel_cmdline: None,
                numa_node: None,
                hugepage_size: None,
            },
            hypervisor: "qemu",
        };
        let expected = fixture("written-controller-config.json");
        assert_eq!(config.to_json(), expected);

        // Round-trip: the parser must accept what the writer wrote and
        // resolve it as a plain QEMU config.
        let parsed = parse_controller_config(&config.to_json()).unwrap();
        assert_eq!(parsed.vm_hash, hash);
        assert_eq!(parsed.vm_index, 6);
        assert!(matches!(parsed.vm, VmConfiguration::Qemu(_)));
    }

    #[test]
    fn save_is_atomic_and_remove_sweeps_the_artifacts() {
        let tmp = tempfile::tempdir().unwrap();
        let hash = "ab";
        let config = WrittenControllerConfig {
            vm_id: 1,
            vm_hash: hash.to_string(),
            settings: WrittenControllerSettings {
                jailer_base_dir: None,
                network_interface: None,
                ipv4_address_pool: "172.16.0.0/12".to_string(),
                ipv4_network_prefix_length: 24,
                ipv6_address_pool: "fc00:1:2:3::/64".to_string(),
                ipv6_allocation_policy: AllocationPolicyValue::Static,
                ipv6_subnet_prefix: 124,
                ipv6_forwarding_enabled: true,
                use_ndp_proxy: true,
            },
            vm_configuration: WrittenQemuVmConfiguration {
                qemu_bin_path: "/usr/bin/qemu-system-x86_64".to_string(),
                cloud_init_drive_path: None,
                image_path: "/tmp/rootfs.qcow2".to_string(),
                monitor_socket_path: "/tmp/m.socket".to_string(),
                qmp_socket_path: "/tmp/q.socket".to_string(),
                qga_socket_path: None,
                vcpu_count: 1,
                mem_size_mb: 256,
                interface_name: None,
                host_volumes: Vec::new(),
                gpus: Vec::new(),
                ovmf_path: None,
                sev_session_file: None,
                sev_dh_cert_file: None,
                sev_policy: None,
                sev_snp: None,
                kernel_path: None,
                initrd_path: None,
                kernel_cmdline: None,
                numa_node: None,
                hugepage_size: None,
            },
            hypervisor: "qemu",
        };
        let path = save_controller_config(tmp.path(), &config).unwrap();
        assert_eq!(path, tmp.path().join("ab-controller.json"));
        // exclude_none: the None fields are absent from the payload.
        let written = std::fs::read_to_string(&path).unwrap();
        assert!(!written.contains("JAILER_BASE_DIR"));
        assert!(!written.contains("cloud_init_drive_path"));
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&path).unwrap().permissions().mode();
            assert_eq!(mode & 0o777, 0o644);
        }
        // No temp litter, and nothing else matches the scanner suffix.
        let names: Vec<String> = std::fs::read_dir(tmp.path())
            .unwrap()
            .map(|entry| entry.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        assert_eq!(names, vec!["ab-controller.json".to_string()]);

        std::fs::write(tmp.path().join("cloud-init-ab.img"), b"seed").unwrap();
        std::fs::write(tmp.path().join("ab-qmp.socket"), b"dead").unwrap();
        remove_controller_configuration(tmp.path(), hash).unwrap();
        assert_eq!(std::fs::read_dir(tmp.path()).unwrap().count(), 0);
    }

    #[test]
    fn a_float_string_mem_size_fails_the_whole_config() {
        // Python parity: _coerce_mib does MiB(int(value)) and
        // int("2048.5") raises, so the whole Configuration is unparseable
        // (the world view then skips the VM, ledger entry 12). The payload
        // does not fit the Firecracker shape either, so the shape-based
        // union cannot rescue it.
        let name = format!("{}-controller.json", crate::test_fixtures::QEMU_HASH);
        let mut value: serde_json::Value = serde_json::from_str(&fixture(&name)).unwrap();
        value["vm_configuration"]["mem_size_mb"] = "2048.5".into();
        assert!(parse_controller_config(&value.to_string()).is_err());
    }
}
