//! Parser for the on-disk controller configuration files
//! (`{EXECUTION_ROOT}/{vm_hash}-controller.json`).
//!
//! The JSON shape is defined by the pydantic models in
//! `src/aleph/vm/supervisor_interface/configuration.py`: `Configuration`
//! wrapping the 9-field `ControllerSettings` slice (PR #1016) and a
//! `vm_configuration` union. The union is resolved by SHAPE, the way
//! pydantic's smart union does for these models; the `hypervisor` field is
//! validated (unknown values fail) but does NOT drive the resolution
//! (probe-confirmed against the Python models: a QEMU-shaped payload with
//! `hypervisor: firecracker`, or with the key absent, still validates as a
//! QEMU configuration and is adopted). Within the QEMU shape,
//! `QemuConfidentialVMConfiguration` validates only when all four
//! confidential fields are present, so a QEMU payload is confidential
//! exactly when `ovmf_path`, `sev_session_file`, `sev_dh_cert_file` and
//! `sev_policy` all appear; otherwise it is a plain `QemuVMConfiguration`.
//! A payload that only fits `VMConfiguration` (Firecracker) is carried as
//! the unsupported variant, which adoption skips (mirroring the Python
//! `spec_from_controller_configuration`, which raises InvalidBackendError
//! for it); a payload fitting no union member fails the whole config, like
//! the pydantic ValidationError.
//!
//! Like the pydantic models (`extra="ignore"`, defaulted slice fields),
//! unknown keys are ignored and absent slice keys fall back to the conf.py
//! defaults; known keys with invalid values fail loudly.
//!
//! Test fixtures under `tests/fixtures/` are generated by the actual Python
//! models (`scripts/generate_rust_fixtures.py`), never hand-written.

use std::path::PathBuf;

use serde::{Deserialize, Deserializer};

/// A parse failure for one controller config file. The world view logs it
/// and skips the VM; it never aborts the daemon (the Python crash-loop
/// lesson behind PR #1016).
#[derive(Debug, thiserror::Error)]
#[error("{0}")]
pub struct ConfigParseError(pub String);

/// `ControllerSettings`: the node-settings slice a controller reads.
/// Defaults mirror conf.py so keys absent from an old dump fall back
/// instead of failing.
#[derive(Debug, Clone, Deserialize)]
#[serde(default)]
pub struct ControllerSettingsSlice {
    #[serde(rename = "JAILER_BASE_DIR")]
    pub jailer_base_dir: Option<PathBuf>,
    #[serde(rename = "NETWORK_INTERFACE")]
    pub network_interface: Option<String>,
    #[serde(rename = "IPV4_ADDRESS_POOL")]
    pub ipv4_address_pool: String,
    #[serde(rename = "IPV4_NETWORK_PREFIX_LENGTH")]
    pub ipv4_network_prefix_length: u8,
    #[serde(rename = "IPV6_ADDRESS_POOL")]
    pub ipv6_address_pool: String,
    #[serde(rename = "IPV6_ALLOCATION_POLICY")]
    pub ipv6_allocation_policy: AllocationPolicyValue,
    #[serde(rename = "IPV6_SUBNET_PREFIX")]
    pub ipv6_subnet_prefix: u8,
    #[serde(rename = "IPV6_FORWARDING_ENABLED")]
    pub ipv6_forwarding_enabled: bool,
    #[serde(rename = "USE_NDP_PROXY")]
    pub use_ndp_proxy: bool,
}

impl Default for ControllerSettingsSlice {
    fn default() -> Self {
        Self {
            jailer_base_dir: None,
            network_interface: None,
            ipv4_address_pool: "172.16.0.0/12".to_string(),
            ipv4_network_prefix_length: 24,
            ipv6_address_pool: "fc00:1:2:3::/64".to_string(),
            ipv6_allocation_policy: AllocationPolicyValue::Static,
            ipv6_subnet_prefix: 124,
            ipv6_forwarding_enabled: true,
            use_ndp_proxy: true,
        }
    }
}

/// The `IPv6AllocationPolicy` str-enum values, validated like pydantic
/// (an unknown value is an error, not a fallback).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
pub enum AllocationPolicyValue {
    #[serde(rename = "static")]
    Static,
    #[serde(rename = "dynamic")]
    Dynamic,
}

/// One `QemuVMHostVolume` entry. `mount` is carried for shape completeness
/// only; QemuVM never consumed it and it is written empty since the spec
/// path.
#[derive(Debug, Clone, Deserialize)]
pub struct QemuHostVolume {
    #[serde(default)]
    pub mount: String,
    pub path_on_host: String,
    pub read_only: bool,
}

/// One `QemuGPU` entry. `supports_x_vga` defaults to true like the pydantic
/// field (backward compatibility with configs that predate it).
#[derive(Debug, Clone, Deserialize)]
pub struct QemuGpu {
    pub pci_host: String,
    #[serde(default = "default_true")]
    pub supports_x_vga: bool,
}

fn default_true() -> bool {
    true
}

/// The four fields `QemuConfidentialVMConfiguration` adds over the plain
/// `QemuVMConfiguration`.
#[derive(Debug, Clone)]
pub struct ConfidentialConfig {
    pub ovmf_path: String,
    pub sev_session_file: String,
    pub sev_dh_cert_file: String,
    pub sev_policy: u32,
}

/// `QemuVMConfiguration` / `QemuConfidentialVMConfiguration` (the plain
/// fields are shared; the confidential four are optional here and resolved
/// by [`QemuVmConfig::confidential`]).
#[derive(Debug, Clone, Deserialize)]
pub struct QemuVmConfig {
    pub qemu_bin_path: String,
    #[serde(default)]
    pub cloud_init_drive_path: Option<String>,
    pub image_path: String,
    pub monitor_socket_path: String,
    pub qmp_socket_path: String,
    #[serde(default)]
    pub qga_socket_path: Option<String>,
    pub vcpu_count: u32,
    #[serde(deserialize_with = "deserialize_mem_size_mib")]
    pub mem_size_mb: u64,
    #[serde(default)]
    pub interface_name: Option<String>,
    pub host_volumes: Vec<QemuHostVolume>,
    pub gpus: Vec<QemuGpu>,

    // Confidential slice; all four present means the payload is a
    // QemuConfidentialVMConfiguration (pydantic union order: the
    // confidential model is tried first and requires them all).
    #[serde(default)]
    ovmf_path: Option<String>,
    #[serde(default)]
    sev_session_file: Option<String>,
    #[serde(default)]
    sev_dh_cert_file: Option<String>,
    #[serde(default)]
    sev_policy: Option<u32>,
}

impl QemuVmConfig {
    /// The confidential slice when this is a
    /// `QemuConfidentialVMConfiguration`, `None` for a plain QEMU config.
    pub fn confidential(&self) -> Option<ConfidentialConfig> {
        match (
            &self.ovmf_path,
            &self.sev_session_file,
            &self.sev_dh_cert_file,
            self.sev_policy,
        ) {
            (Some(ovmf), Some(session), Some(dh_cert), Some(policy)) => Some(ConfidentialConfig {
                ovmf_path: ovmf.clone(),
                sev_session_file: session.clone(),
                sev_dh_cert_file: dh_cert.clone(),
                sev_policy: policy,
            }),
            _ => None,
        }
    }
}

/// `MemSizeMib` reads with the coercion of the Python `_coerce_mib`
/// (`MiB(int(value))`): an integer, a float JSON number (Python's `int()`
/// truncates) or an INTEGER string. A float STRING like "2048.5" raises in
/// Python's `int(value)` and makes the whole config unparseable; it is
/// rejected here too.
fn deserialize_mem_size_mib<'de, D>(deserializer: D) -> Result<u64, D::Error>
where
    D: Deserializer<'de>,
{
    let value = serde_json::Value::deserialize(deserializer)?;
    let parsed = match &value {
        serde_json::Value::Number(number) => number
            .as_u64()
            .or_else(|| number.as_f64().map(|float| float as u64)),
        serde_json::Value::String(text) => text.trim().parse::<u64>().ok(),
        _ => None,
    };
    parsed.ok_or_else(|| serde::de::Error::custom(format!("cannot coerce {value} to MiB")))
}

/// The resolved `vm_configuration` union member.
#[derive(Debug, Clone)]
pub enum VmConfiguration {
    Qemu(Box<QemuVmConfig>),
    /// A `VMConfiguration` (Firecracker) payload. Adoption is QEMU-only:
    /// the world view reports these and leaves them alone, exactly like the
    /// Python reattach (spec_from_controller_configuration raises
    /// InvalidBackendError, isolating the VM as a failed reattach).
    Firecracker,
}

/// The `VMConfiguration` (Firecracker) shape, deserialized only to decide
/// whether a non-QEMU payload is a valid union member (pydantic parity) or
/// garbage that fails the whole `Configuration`. Field values are unused.
#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct FirecrackerShape {
    use_jailer: bool,
    firecracker_bin_path: String,
    jailer_bin_path: String,
    config_file_path: String,
    init_timeout: f64,
}

/// The top-level `Configuration` model.
#[derive(Debug, Clone)]
pub struct ControllerConfig {
    /// `Configuration.vm_id`: the vm_index (tap interface / IPv4 range id).
    pub vm_index: i64,
    /// `Configuration.vm_hash`: the VM item hash, our world-view key.
    pub vm_hash: String,
    pub settings: ControllerSettingsSlice,
    pub vm: VmConfiguration,
}

#[derive(Debug, Deserialize)]
struct RawConfiguration {
    vm_id: i64,
    vm_hash: String,
    settings: ControllerSettingsSlice,
    vm_configuration: serde_json::Value,
    // The pydantic default is HypervisorType.firecracker.
    #[serde(default = "default_hypervisor")]
    hypervisor: String,
}

fn default_hypervisor() -> String {
    "firecracker".to_string()
}

/// Parse one controller configuration file's JSON contents.
pub fn parse_controller_config(json: &str) -> Result<ControllerConfig, ConfigParseError> {
    let raw: RawConfiguration = serde_json::from_str(json)
        .map_err(|error| ConfigParseError(format!("invalid Configuration JSON: {error}")))?;
    // The hypervisor field is validated like the pydantic HypervisorType
    // enum, but it does not pick the union member (see the module docs).
    if raw.hypervisor != "qemu" && raw.hypervisor != "firecracker" {
        return Err(ConfigParseError(format!(
            "unknown hypervisor {:?}",
            raw.hypervisor
        )));
    }
    // Shape-based union resolution, like pydantic's smart union over
    // QemuConfidentialVMConfiguration | QemuVMConfiguration |
    // VMConfiguration (the two QEMU members are one struct here, the
    // confidential slice being optional).
    let vm = match serde_json::from_value::<QemuVmConfig>(raw.vm_configuration.clone()) {
        Ok(config) => VmConfiguration::Qemu(Box::new(config)),
        Err(qemu_error) => match serde_json::from_value::<FirecrackerShape>(raw.vm_configuration) {
            Ok(_) => VmConfiguration::Firecracker,
            Err(firecracker_error) => {
                return Err(ConfigParseError(format!(
                    "vm_configuration fits no union member: \
                     not QEMU ({qemu_error}); not Firecracker ({firecracker_error})"
                )));
            }
        },
    };
    Ok(ControllerConfig {
        vm_index: raw.vm_id,
        vm_hash: raw.vm_hash,
        settings: raw.settings,
        vm,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture(name: &str) -> String {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures")
            .join(name);
        std::fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("cannot read fixture {}: {error}", path.display()))
    }

    #[test]
    fn parses_the_plain_qemu_fixture() {
        let name = format!("{}-controller.json", crate::test_fixtures::QEMU_HASH);
        let config = parse_controller_config(&fixture(&name)).unwrap();
        assert_eq!(config.vm_hash, crate::test_fixtures::QEMU_HASH);
        assert_eq!(config.vm_index, 3);
        assert_eq!(config.settings.ipv4_address_pool, "172.16.0.0/12");
        assert_eq!(config.settings.ipv4_network_prefix_length, 24);
        assert_eq!(config.settings.ipv6_address_pool, "fc00:1:2:3::/64");
        assert_eq!(
            config.settings.ipv6_allocation_policy,
            AllocationPolicyValue::Static
        );
        assert_eq!(config.settings.ipv6_subnet_prefix, 124);
        assert!(config.settings.ipv6_forwarding_enabled);
        assert!(config.settings.use_ndp_proxy);
        let VmConfiguration::Qemu(vm) = &config.vm else {
            panic!("expected a QEMU configuration");
        };
        assert_eq!(vm.vcpu_count, 2);
        assert_eq!(vm.mem_size_mb, 2048);
        assert_eq!(vm.interface_name.as_deref(), Some("vmtap3"));
        assert!(vm.image_path.ends_with("rootfs.qcow2"));
        assert_eq!(vm.host_volumes.len(), 1);
        assert!(!vm.host_volumes[0].read_only);
        assert!(vm.gpus.is_empty());
        assert!(vm.confidential().is_none());
    }

    #[test]
    fn parses_the_gpu_fixture() {
        let name = format!("{}-controller.json", crate::test_fixtures::GPU_HASH);
        let config = parse_controller_config(&fixture(&name)).unwrap();
        let VmConfiguration::Qemu(vm) = &config.vm else {
            panic!("expected a QEMU configuration");
        };
        assert_eq!(vm.gpus.len(), 1);
        assert_eq!(vm.gpus[0].pci_host, "0000:01:00.0");
        assert!(vm.gpus[0].supports_x_vga);
        assert!(vm.confidential().is_none());
    }

    #[test]
    fn parses_the_confidential_fixture() {
        let name = format!(
            "{}-controller.json",
            crate::test_fixtures::CONFIDENTIAL_HASH
        );
        let config = parse_controller_config(&fixture(&name)).unwrap();
        let VmConfiguration::Qemu(vm) = &config.vm else {
            panic!("expected a QEMU configuration");
        };
        let confidential = vm.confidential().expect("must resolve as confidential");
        assert_eq!(confidential.sev_policy, 0x5);
        assert!(confidential.ovmf_path.ends_with("OVMF_CSV.fd"));
        assert!(confidential.sev_session_file.ends_with("vm_session.b64"));
        assert!(confidential.sev_dh_cert_file.ends_with("vm_godh.b64"));
    }

    #[test]
    fn a_firecracker_config_resolves_to_the_unsupported_variant() {
        let json = r#"{
            "vm_id": 7,
            "vm_hash": "deadbeef",
            "settings": {},
            "vm_configuration": {
                "use_jailer": true,
                "firecracker_bin_path": "/opt/firecracker/firecracker",
                "jailer_bin_path": "/opt/firecracker/jailer",
                "config_file_path": "/var/lib/aleph/vm/deadbeef.json",
                "init_timeout": 5.0
            },
            "hypervisor": "firecracker"
        }"#;
        let config = parse_controller_config(json).unwrap();
        assert!(matches!(config.vm, VmConfiguration::Firecracker));
    }

    #[test]
    fn a_firecracker_shaped_payload_without_the_hypervisor_field_still_resolves() {
        // Configs predating the field (pydantic default: firecracker); the
        // union is resolved by shape either way.
        let json = r#"{
            "vm_id": 1,
            "vm_hash": "aa",
            "settings": {},
            "vm_configuration": {
                "use_jailer": true,
                "firecracker_bin_path": "/opt/firecracker/firecracker",
                "jailer_bin_path": "/opt/firecracker/jailer",
                "config_file_path": "/var/lib/aleph/vm/aa.json",
                "init_timeout": 5.0
            }
        }"#;
        let config = parse_controller_config(json).unwrap();
        assert!(matches!(config.vm, VmConfiguration::Firecracker));
    }

    #[test]
    fn the_union_is_resolved_by_shape_not_by_the_hypervisor_field() {
        // Probe-confirmed pydantic behavior: a QEMU-shaped payload with
        // hypervisor "firecracker", or with the key absent, still validates
        // as a QemuVMConfiguration and is adopted as QEMU.
        let name = format!("{}-controller.json", crate::test_fixtures::QEMU_HASH);
        let mut value: serde_json::Value = serde_json::from_str(&fixture(&name)).unwrap();

        value["hypervisor"] = "firecracker".into();
        let config = parse_controller_config(&value.to_string()).unwrap();
        assert!(matches!(config.vm, VmConfiguration::Qemu(_)));

        value.as_object_mut().unwrap().remove("hypervisor");
        let config = parse_controller_config(&value.to_string()).unwrap();
        assert!(matches!(config.vm, VmConfiguration::Qemu(_)));
    }

    #[test]
    fn a_payload_fitting_no_union_member_fails_the_whole_config() {
        // pydantic parity: vm_configuration must validate as one union
        // member or the whole Configuration raises (Rust: the VM is then
        // skipped per ledger entry 12).
        let json = r#"{"vm_id": 1, "vm_hash": "aa", "settings": {}, "vm_configuration": {}}"#;
        assert!(parse_controller_config(json).is_err());
    }

    #[test]
    fn unknown_keys_are_ignored_like_extra_ignore() {
        // Old configs embedded a full Settings dump; surplus keys are
        // ignored on read (the 1.13.0 CONNECTIVITY_DNS_HOSTNAME lesson).
        let name = format!("{}-controller.json", crate::test_fixtures::QEMU_HASH);
        let mut value: serde_json::Value = serde_json::from_str(&fixture(&name)).unwrap();
        value["settings"]["CONNECTIVITY_DNS_HOSTNAME"] = "example.org".into();
        value["vm_configuration"]["surplus_key"] = 42.into();
        assert!(parse_controller_config(&value.to_string()).is_ok());
    }

    #[test]
    fn invalid_json_and_invalid_values_are_errors() {
        assert!(parse_controller_config("not json").is_err());
        // A known key with an invalid value fails loudly, like pydantic.
        let json = r#"{
            "vm_id": 1,
            "vm_hash": "aa",
            "settings": {"IPV6_ALLOCATION_POLICY": "sometimes"},
            "vm_configuration": {},
            "hypervisor": "firecracker"
        }"#;
        assert!(parse_controller_config(json).is_err());
    }

    #[test]
    fn mem_size_accepts_pydantic_lax_forms() {
        let name = format!("{}-controller.json", crate::test_fixtures::QEMU_HASH);
        let mut value: serde_json::Value = serde_json::from_str(&fixture(&name)).unwrap();
        for lax in [
            serde_json::Value::from("2048"),
            serde_json::Value::from(2048.0),
            // Python's int() truncates a float JSON number.
            serde_json::Value::from(2048.7),
        ] {
            value["vm_configuration"]["mem_size_mb"] = lax;
            let config = parse_controller_config(&value.to_string()).unwrap();
            let VmConfiguration::Qemu(vm) = &config.vm else {
                panic!("expected a QEMU configuration");
            };
            assert_eq!(vm.mem_size_mb, 2048);
        }
    }

    #[test]
    fn a_float_string_mem_size_fails_the_whole_config() {
        // Python parity: _coerce_mib does MiB(int(value)) and
        // int("2048.5") raises, so the whole Configuration is unparseable
        // (the world view then skips the VM, ledger entry 12). The payload
        // does not fit the Firecracker shape either, so the shape-based
        // union cannot rescue it.
        let name = format!("{}-controller.json", crate::test_fixtures::QEMU_HASH);
        let mut value: serde_json::Value = serde_json::from_str(&fixture(&name)).unwrap();
        value["vm_configuration"]["mem_size_mb"] = "2048.5".into();
        assert!(parse_controller_config(&value.to_string()).is_err());
    }
}
