//! The supervisor's port-mapping store
//! (`{SUPERVISOR_DATABASE}`, default `{EXECUTION_ROOT}/supervisor.sqlite3`)
//! and the host-port allocator.
//!
//! Schema (SQLAlchemy `PortMapping` in
//! src/aleph/vm/supervisor/networking_db.py): `port_mappings(id INTEGER
//! PRIMARY KEY, vm_hash TEXT, vm_port INTEGER, host_port INTEGER, tcp
//! BOOLEAN, udp BOOLEAN, created_at DATETIME, deleted_at DATETIME)`, soft
//! delete via `deleted_at IS NULL`, a partial unique index on active
//! host_port. The DDL below is byte-identical to what SQLAlchemy's
//! create_all emits, and datetimes are written in its sqlite rendering
//! ("YYYY-MM-DD HH:MM:SS.ffffff", UTC, no offset), so a rollback to the
//! Python daemon reads whatever this daemon wrote and vice versa.
//!
//! Python parity for the fold: `get_port_mappings` builds a dict keyed by
//! vm_port from an unordered SELECT (sqlite returns rowid order), so a
//! duplicate active vm_port keeps the first row's position with the last
//! row's values. The test fixture database is generated by the actual
//! SQLAlchemy models (`scripts/generate_rust_fixtures.py`).
//!
//! The allocator ports network/port_availability_checker.py: DB actives,
//! nftables redirections and a TCP+UDP bind probe per candidate, plus the
//! rotating fast-path cursor.

use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use crate::nft;

/// One active port mapping of a VM, in Python's `mapped_ports` shape
/// (vm_port keyed, host port plus per-protocol flags).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PortForward {
    pub vm_port: u32,
    pub host_port: u32,
    pub tcp: bool,
    pub udp: bool,
}

/// Load the active (non-deleted) port mappings of one VM.
///
/// A missing database file means no mappings (the read-only daemon never
/// creates the store; the Python daemon's `pool.setup()` does).
pub fn load_port_forwards(database: &Path, vm_hash: &str) -> Result<Vec<PortForward>, String> {
    if !database.exists() {
        tracing::debug!(
            database = %database.display(),
            "supervisor database absent; no port mappings"
        );
        return Ok(Vec::new());
    }
    let connection =
        rusqlite::Connection::open_with_flags(database, rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY)
            .map_err(|error| format!("cannot open {}: {error}", database.display()))?;
    // During adoption the draining Python daemon may still hold the write
    // lock on this database; an immediate SQLITE_BUSY would silently cost a
    // VM its port forwards, so wait up to 5 seconds for the lock instead.
    connection
        .busy_timeout(std::time::Duration::from_secs(5))
        .map_err(|error| {
            format!(
                "cannot set a busy timeout on {}: {error}",
                database.display()
            )
        })?;
    let mut statement = connection
        .prepare(
            "SELECT vm_port, host_port, tcp, udp FROM port_mappings \
             WHERE vm_hash = ?1 AND deleted_at IS NULL ORDER BY id",
        )
        .map_err(|error| format!("cannot query port_mappings: {error}"))?;
    let rows = statement
        .query_map([vm_hash], |row| {
            Ok(PortForward {
                vm_port: row.get(0)?,
                host_port: row.get(1)?,
                tcp: row.get(2)?,
                udp: row.get(3)?,
            })
        })
        .map_err(|error| format!("cannot read port_mappings: {error}"))?;

    // Fold like the Python dict build: last row wins per vm_port, first
    // occurrence keeps its position.
    let mut forwards: Vec<PortForward> = Vec::new();
    for row in rows {
        let row = row.map_err(|error| format!("cannot read port_mappings row: {error}"))?;
        match forwards
            .iter_mut()
            .find(|forward| forward.vm_port == row.vm_port)
        {
            Some(existing) => *existing = row,
            None => forwards.push(row),
        }
    }
    Ok(forwards)
}

/// Open the store read-write with the same 5 second lock patience as the
/// read path (the draining Python daemon may still hold the write lock
/// during an adoption swap).
fn open_rw(database: &Path) -> Result<rusqlite::Connection, String> {
    let connection = rusqlite::Connection::open(database)
        .map_err(|error| format!("cannot open {}: {error}", database.display()))?;
    connection
        .busy_timeout(std::time::Duration::from_secs(5))
        .map_err(|error| {
            format!(
                "cannot set a busy timeout on {}: {error}",
                database.display()
            )
        })?;
    Ok(connection)
}

/// Create the port_mappings schema when absent, the Python
/// `create_supervisor_tables` (SQLAlchemy metadata.create_all) the daemon
/// runs in pool.setup(). The DDL matches SQLAlchemy's output exactly so
/// either daemon can have created the file.
pub fn ensure_schema(database: &Path) -> Result<(), String> {
    let connection = open_rw(database)?;
    let exists: bool = connection
        .query_row(
            "SELECT COUNT(*) FROM sqlite_master WHERE type = 'table' AND name = 'port_mappings'",
            [],
            |row| row.get::<_, i64>(0).map(|count| count > 0),
        )
        .map_err(|error| format!("cannot inspect {}: {error}", database.display()))?;
    if exists {
        return Ok(());
    }
    connection
        .execute_batch(
            "CREATE TABLE port_mappings (\n\
             \tid INTEGER NOT NULL, \n\
             \tvm_hash VARCHAR NOT NULL, \n\
             \tvm_port INTEGER NOT NULL, \n\
             \thost_port INTEGER NOT NULL, \n\
             \ttcp BOOLEAN NOT NULL, \n\
             \tudp BOOLEAN NOT NULL, \n\
             \tcreated_at DATETIME NOT NULL, \n\
             \tdeleted_at DATETIME, \n\
             \tPRIMARY KEY (id)\n\
             );\n\
             CREATE INDEX ix_port_mappings_vm_hash ON port_mappings (vm_hash);\n\
             CREATE UNIQUE INDEX ix_port_mappings_host_port_active \
             ON port_mappings (host_port) WHERE deleted_at IS NULL;",
        )
        .map_err(|error| format!("cannot create port_mappings: {error}"))
}

/// UTC now in SQLAlchemy's sqlite DATETIME rendering:
/// "YYYY-MM-DD HH:MM:SS.ffffff" (microseconds, no offset).
pub fn sqlalchemy_utc_now() -> String {
    let elapsed = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default();
    format_sqlalchemy_datetime(elapsed.as_secs(), elapsed.subsec_micros())
}

fn format_sqlalchemy_datetime(unix_secs: u64, micros: u32) -> String {
    let days = unix_secs / 86_400;
    let seconds_of_day = unix_secs % 86_400;
    let (year, month, day) = civil_from_days(days as i64);
    format!(
        "{year:04}-{month:02}-{day:02} {:02}:{:02}:{:02}.{micros:06}",
        seconds_of_day / 3600,
        (seconds_of_day % 3600) / 60,
        seconds_of_day % 60,
    )
}

/// Days-since-epoch to civil date (Howard Hinnant's algorithm); valid for
/// every post-epoch instant this daemon can observe.
fn civil_from_days(days: i64) -> (i64, u32, u32) {
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z.rem_euclid(146_097);
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let year = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let day = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let month = (if mp < 10 { mp + 3 } else { mp - 9 }) as u32;
    (if month <= 2 { year + 1 } else { year }, month, day)
}

/// Persist one VM's mappings, the Python `save_port_mappings`: unchanged
/// active rows are left alone, changed ones are soft-deleted and
/// re-inserted, vanished ones soft-deleted; all under one transaction so
/// the partial unique index sees the deletes before the inserts.
pub fn save_port_mappings(
    database: &Path,
    vm_hash: &str,
    forwards: &[PortForward],
    now: &str,
) -> Result<(), String> {
    let mut connection = open_rw(database)?;
    let transaction = connection
        .transaction()
        .map_err(|error| format!("cannot begin a transaction: {error}"))?;

    // Active rows keyed by vm_port, LAST row winning like the Python dict
    // build (an earlier duplicate simply drops out and stays active).
    let mut existing: std::collections::HashMap<u32, (i64, PortForward)> =
        std::collections::HashMap::new();
    {
        let mut statement = transaction
            .prepare(
                "SELECT id, vm_port, host_port, tcp, udp FROM port_mappings \
                 WHERE vm_hash = ?1 AND deleted_at IS NULL",
            )
            .map_err(|error| format!("cannot query port_mappings: {error}"))?;
        let rows = statement
            .query_map([vm_hash], |row| {
                Ok((
                    row.get::<_, i64>(0)?,
                    PortForward {
                        vm_port: row.get(1)?,
                        host_port: row.get(2)?,
                        tcp: row.get(3)?,
                        udp: row.get(4)?,
                    },
                ))
            })
            .map_err(|error| format!("cannot read port_mappings: {error}"))?;
        for row in rows {
            let (id, forward) =
                row.map_err(|error| format!("cannot read port_mappings row: {error}"))?;
            existing.insert(forward.vm_port, (id, forward));
        }
    }

    let mut inserts: Vec<&PortForward> = Vec::new();
    let mut soft_deletes: Vec<i64> = Vec::new();
    for forward in forwards {
        match existing.remove(&forward.vm_port) {
            Some((_, old)) if old == *forward => {}
            Some((id, _)) => {
                soft_deletes.push(id);
                inserts.push(forward);
            }
            None => inserts.push(forward),
        }
    }
    soft_deletes.extend(existing.values().map(|(id, _)| *id));

    for id in soft_deletes {
        transaction
            .execute(
                "UPDATE port_mappings SET deleted_at = ?1 WHERE id = ?2",
                rusqlite::params![now, id],
            )
            .map_err(|error| format!("cannot soft-delete port mapping {id}: {error}"))?;
    }
    for forward in inserts {
        transaction
            .execute(
                "INSERT INTO port_mappings (vm_hash, vm_port, host_port, tcp, udp, created_at) \
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
                rusqlite::params![
                    vm_hash,
                    forward.vm_port,
                    forward.host_port,
                    forward.tcp,
                    forward.udp,
                    now
                ],
            )
            .map_err(|error| format!("cannot insert a port mapping: {error}"))?;
    }
    transaction
        .commit()
        .map_err(|error| format!("cannot commit port mappings: {error}"))
}

/// Python `delete_port_mappings`: soft-delete every active row of a VM.
pub fn delete_port_mappings(database: &Path, vm_hash: &str, now: &str) -> Result<(), String> {
    let connection = open_rw(database)?;
    connection
        .execute(
            "UPDATE port_mappings SET deleted_at = ?1 \
             WHERE vm_hash = ?2 AND deleted_at IS NULL",
            rusqlite::params![now, vm_hash],
        )
        .map(|_| ())
        .map_err(|error| format!("cannot delete port mappings of {vm_hash}: {error}"))
}

// ── Host port allocation (network/port_availability_checker.py) ─────────

pub const MIN_DYNAMIC_PORT: u32 = 24000;
pub const MAX_PORT: u32 = 65535;

/// Python `_get_active_host_ports`: every active host_port in the store; a
/// missing table (or file) means none yet.
fn active_host_ports(database: &Path) -> Result<std::collections::HashSet<u32>, String> {
    if !database.exists() {
        return Ok(Default::default());
    }
    let connection = open_rw(database)?;
    let mut statement =
        match connection.prepare("SELECT host_port FROM port_mappings WHERE deleted_at IS NULL") {
            Ok(statement) => statement,
            Err(rusqlite::Error::SqliteFailure(_, Some(message)))
                if message.to_lowercase().contains("no such table") =>
            {
                tracing::debug!("port_mappings table not available yet");
                return Ok(Default::default());
            }
            Err(error) => return Err(format!("cannot query port_mappings: {error}")),
        };
    let rows = statement
        .query_map([], |row| row.get::<_, u32>(0))
        .map_err(|error| format!("cannot read host ports: {error}"))?;
    rows.collect::<Result<_, _>>()
        .map_err(|error| format!("cannot read host ports: {error}"))
}

/// Python `is_host_port_available`: a short-lived TCP+UDP bind probe on
/// 0.0.0.0 (no nftables check).
pub fn is_host_port_available(port: u32) -> bool {
    let Ok(port) = u16::try_from(port) else {
        return false;
    };
    std::net::TcpListener::bind(("0.0.0.0", port)).is_ok()
        && std::net::UdpSocket::bind(("0.0.0.0", port)).is_ok()
}

/// Python `get_available_host_port`: first port from `start_port` that is
/// absent from the store, not referenced by any nftables redirect (the
/// ruleset is re-fetched per candidate, like the Python loop), and
/// bindable on both protocols.
pub fn get_available_host_port(
    database: &Path,
    executor: &dyn nft::NftExecutor,
    start_port: u32,
) -> Result<u32, String> {
    let start = if start_port >= MIN_DYNAMIC_PORT {
        start_port
    } else {
        MIN_DYNAMIC_PORT
    };
    // TOCTOU accepted, as in Python: the partial unique index on active
    // host_port is the real safety net.
    let active = active_host_ports(database)?;
    for port in start..MAX_PORT {
        if active.contains(&port) {
            continue;
        }
        if nft::check_nftables_redirections(&nft::fetch_ruleset(executor), port) {
            continue;
        }
        if !is_host_port_available(port) {
            tracing::debug!(port, "port unavailable (bind failed)");
            continue;
        }
        return Ok(port);
    }
    Err(format!(
        "No available ports found in range {MIN_DYNAMIC_PORT}-{MAX_PORT}"
    ))
}

/// Python `fast_get_available_host_port`'s LAST_ASSIGNED_HOST_PORT global:
/// a rotating cursor so consecutive allocations skip the slow re-checks of
/// low ports. Per-daemon state, like the Python module global.
pub struct PortCursor {
    last: std::sync::atomic::AtomicU32,
}

impl Default for PortCursor {
    fn default() -> Self {
        Self {
            last: std::sync::atomic::AtomicU32::new(MIN_DYNAMIC_PORT),
        }
    }
}

impl PortCursor {
    pub fn fast_get_available_host_port(
        &self,
        database: &Path,
        executor: &dyn nft::NftExecutor,
    ) -> Result<u32, String> {
        use std::sync::atomic::Ordering;
        let start = self.last.load(Ordering::SeqCst);
        let port = get_available_host_port(database, executor, start)?;
        let mut next = port + 1;
        if next >= MAX_PORT {
            next = MIN_DYNAMIC_PORT;
        }
        self.last.store(next, Ordering::SeqCst);
        Ok(port)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_fixtures;

    fn fixture_db() -> std::path::PathBuf {
        test_fixtures::fixtures_dir().join("supervisor.sqlite3")
    }

    #[test]
    fn loads_active_mappings_in_rowid_order_skipping_soft_deleted() {
        let forwards = load_port_forwards(&fixture_db(), test_fixtures::QEMU_HASH).unwrap();
        // The fixture holds a soft-deleted 22->24022 row that must not
        // surface, then the active 22->24000 (tcp) and 8080->24001
        // (tcp+udp) rows.
        assert_eq!(
            forwards,
            vec![
                PortForward {
                    vm_port: 22,
                    host_port: 24000,
                    tcp: true,
                    udp: false,
                },
                PortForward {
                    vm_port: 8080,
                    host_port: 24001,
                    tcp: true,
                    udp: true,
                },
            ]
        );
    }

    #[test]
    fn a_vm_without_rows_gets_no_mappings() {
        let forwards = load_port_forwards(&fixture_db(), test_fixtures::GPU_HASH).unwrap();
        assert!(forwards.is_empty());
    }

    #[test]
    fn a_missing_database_means_no_mappings() {
        let tmp = tempfile::tempdir().unwrap();
        let forwards =
            load_port_forwards(&tmp.path().join("absent.sqlite3"), test_fixtures::QEMU_HASH)
                .unwrap();
        assert!(forwards.is_empty());
    }

    #[test]
    fn a_database_without_the_table_is_an_error() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("empty.sqlite3");
        rusqlite::Connection::open(&path).unwrap();
        let error = load_port_forwards(&path, test_fixtures::QEMU_HASH).unwrap_err();
        assert!(error.contains("port_mappings"));
    }

    fn schema_dump(path: &std::path::Path) -> Vec<String> {
        let connection = rusqlite::Connection::open(path).unwrap();
        let mut statement = connection
            .prepare("SELECT sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY name")
            .unwrap();
        let rows = statement
            .query_map([], |row| row.get::<_, String>(0))
            .unwrap();
        rows.collect::<Result<_, _>>().unwrap()
    }

    #[test]
    fn ensure_schema_matches_the_sqlalchemy_ddl_byte_for_byte() {
        // The fixture database was created by SQLAlchemy's create_all; a
        // store created by the Rust daemon must carry the identical DDL so
        // a rollback to the Python daemon (which introspects nothing but
        // relies on the same schema) is safe.
        let tmp = tempfile::tempdir().unwrap();
        let ours = tmp.path().join("supervisor.sqlite3");
        ensure_schema(&ours).unwrap();
        assert_eq!(schema_dump(&ours), schema_dump(&fixture_db()));

        // Idempotent, including on a database SQLAlchemy created.
        ensure_schema(&ours).unwrap();
        ensure_schema(&fixture_db()).unwrap();
    }

    #[test]
    fn timestamps_render_like_sqlalchemy() {
        // The fixture rows carry datetime(2026, 1, 1, tzinfo=utc) as
        // "2026-01-01 00:00:00.000000"; 2026-01-01 is 1767225600.
        assert_eq!(
            format_sqlalchemy_datetime(1_767_225_600, 0),
            "2026-01-01 00:00:00.000000"
        );
        assert_eq!(
            format_sqlalchemy_datetime(1_767_225_600 + 3661, 42),
            "2026-01-01 01:01:01.000042"
        );
        // Leap-year day.
        assert_eq!(
            format_sqlalchemy_datetime(1_709_164_800, 0),
            "2024-02-29 00:00:00.000000"
        );
        let now = sqlalchemy_utc_now();
        assert_eq!(now.len(), 26);
        assert_eq!(&now[4..5], "-");
        assert_eq!(&now[10..11], " ");
    }

    #[test]
    fn save_port_mappings_soft_deletes_and_reinserts_like_python() {
        let tmp = tempfile::tempdir().unwrap();
        let db = tmp.path().join("supervisor.sqlite3");
        ensure_schema(&db).unwrap();
        let hash = "aa";

        let initial = vec![
            PortForward {
                vm_port: 22,
                host_port: 24000,
                tcp: true,
                udp: false,
            },
            PortForward {
                vm_port: 8080,
                host_port: 24001,
                tcp: true,
                udp: true,
            },
        ];
        save_port_mappings(&db, hash, &initial, "2026-01-01 00:00:00.000000").unwrap();
        assert_eq!(load_port_forwards(&db, hash).unwrap(), initial);

        // 22 unchanged (row kept), 8080 gains udp-only (soft-delete +
        // reinsert), 9000 is new; nothing vanished.
        let updated = vec![
            PortForward {
                vm_port: 22,
                host_port: 24000,
                tcp: true,
                udp: false,
            },
            PortForward {
                vm_port: 8080,
                host_port: 24001,
                tcp: false,
                udp: true,
            },
            PortForward {
                vm_port: 9000,
                host_port: 24002,
                tcp: true,
                udp: false,
            },
        ];
        save_port_mappings(&db, hash, &updated, "2026-01-01 00:00:01.000000").unwrap();
        assert_eq!(load_port_forwards(&db, hash).unwrap(), updated);

        let connection = rusqlite::Connection::open(&db).unwrap();
        let unchanged_created: String = connection
            .query_row(
                "SELECT created_at FROM port_mappings \
                 WHERE vm_hash = 'aa' AND vm_port = 22 AND deleted_at IS NULL",
                [],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(
            unchanged_created, "2026-01-01 00:00:00.000000",
            "an unchanged mapping keeps its original row"
        );
        let soft_deleted: i64 = connection
            .query_row(
                "SELECT COUNT(*) FROM port_mappings WHERE deleted_at IS NOT NULL",
                [],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(soft_deleted, 1, "only the changed 8080 row was retired");

        // An empty request soft-deletes everything (the audit trail stays).
        save_port_mappings(&db, hash, &[], "2026-01-01 00:00:02.000000").unwrap();
        assert!(load_port_forwards(&db, hash).unwrap().is_empty());

        delete_port_mappings(&db, hash, "2026-01-01 00:00:03.000000").unwrap();
        assert!(load_port_forwards(&db, hash).unwrap().is_empty());
    }

    #[test]
    fn the_python_daemon_shape_reads_rust_written_rows() {
        // Round-trip through the committed SQLAlchemy fixture: writing to a
        // COPY of it and reading back exercises both directions against a
        // database whose file SQLAlchemy created.
        let tmp = tempfile::tempdir().unwrap();
        let db = tmp.path().join("supervisor.sqlite3");
        std::fs::copy(fixture_db(), &db).unwrap();
        let forward = PortForward {
            vm_port: 443,
            host_port: 24100,
            tcp: true,
            udp: false,
        };
        save_port_mappings(
            &db,
            "cc",
            std::slice::from_ref(&forward),
            &sqlalchemy_utc_now(),
        )
        .unwrap();
        assert_eq!(load_port_forwards(&db, "cc").unwrap(), vec![forward]);
        // The pre-existing rows are untouched.
        assert_eq!(
            load_port_forwards(&db, test_fixtures::QEMU_HASH)
                .unwrap()
                .len(),
            2
        );
    }

    #[test]
    fn port_allocation_skips_db_nftables_and_bound_ports() {
        let tmp = tempfile::tempdir().unwrap();
        let db = tmp.path().join("supervisor.sqlite3");
        ensure_schema(&db).unwrap();
        save_port_mappings(
            &db,
            "aa",
            &[PortForward {
                vm_port: 22,
                host_port: 24000,
                tcp: true,
                udp: false,
            }],
            &sqlalchemy_utc_now(),
        )
        .unwrap();
        // 24001 is redirected in nftables only.
        let executor = nft::StaticRuleset::new(vec![serde_json::json!({"rule": {
            "family": "ip", "table": "nat", "chain": "aleph-supervisor-prerouting",
            "handle": 1,
            "expr": [
                {"match": {"op": "==", "left": {"meta": {"key": "iifname"}}, "right": "eth0"}},
                {"match": {"op": "==", "left": {"payload": {"protocol": "tcp", "field": "dport"}}, "right": 24001}},
                {"dnat": {"addr": "172.16.3.2", "port": 22}},
            ],
        }})]);
        // 24002 is bound by a live socket.
        let _holder = std::net::TcpListener::bind(("0.0.0.0", 24002)).ok();
        let port = get_available_host_port(&db, &executor, 0).unwrap();
        assert!(port >= 24003 || _holder.is_none());
        assert_ne!(port, 24000);
        assert_ne!(port, 24001);

        let cursor = PortCursor::default();
        let first = cursor.fast_get_available_host_port(&db, &executor).unwrap();
        let second = cursor.fast_get_available_host_port(&db, &executor).unwrap();
        assert!(second > first, "the cursor advances past the last grant");
    }

    #[test]
    fn a_missing_store_means_no_active_ports() {
        let tmp = tempfile::tempdir().unwrap();
        assert!(
            active_host_ports(&tmp.path().join("absent.sqlite3"))
                .unwrap()
                .is_empty()
        );
        // A store without the table degrades the same way (Python catches
        // "no such table").
        let path = tmp.path().join("empty.sqlite3");
        rusqlite::Connection::open(&path).unwrap();
        assert!(active_host_ports(&path).unwrap().is_empty());
    }
}
