//! Read-only access to the supervisor's port-mapping store
//! (`{SUPERVISOR_DATABASE}`, default `{EXECUTION_ROOT}/supervisor.sqlite3`).
//!
//! Schema (SQLAlchemy `PortMapping` in
//! src/aleph/vm/supervisor/networking_db.py): `port_mappings(id INTEGER
//! PRIMARY KEY, vm_hash TEXT, vm_port INTEGER, host_port INTEGER, tcp
//! BOOLEAN, udp BOOLEAN, created_at DATETIME, deleted_at DATETIME)`, soft
//! delete via `deleted_at IS NULL`. Datetimes are ISO strings as SQLAlchemy
//! writes them; this increment never parses them (the active filter is
//! NULL-ness), so no datetime handling is needed until the daemon writes
//! rows in increment 3.
//!
//! Python parity for the fold: `get_port_mappings` builds a dict keyed by
//! vm_port from an unordered SELECT (sqlite returns rowid order), so a
//! duplicate active vm_port keeps the first row's position with the last
//! row's values. The test fixture database is generated by the actual
//! SQLAlchemy models (`scripts/generate_rust_fixtures.py`).

use std::path::Path;

/// One active port mapping of a VM, in Python's `mapped_ports` shape
/// (vm_port keyed, host port plus per-protocol flags).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PortForward {
    pub vm_port: u32,
    pub host_port: u32,
    pub tcp: bool,
    pub udp: bool,
}

/// Load the active (non-deleted) port mappings of one VM.
///
/// A missing database file means no mappings (the read-only daemon never
/// creates the store; the Python daemon's `pool.setup()` does).
pub fn load_port_forwards(database: &Path, vm_hash: &str) -> Result<Vec<PortForward>, String> {
    if !database.exists() {
        tracing::debug!(
            database = %database.display(),
            "supervisor database absent; no port mappings"
        );
        return Ok(Vec::new());
    }
    let connection =
        rusqlite::Connection::open_with_flags(database, rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY)
            .map_err(|error| format!("cannot open {}: {error}", database.display()))?;
    // During adoption the draining Python daemon may still hold the write
    // lock on this database; an immediate SQLITE_BUSY would silently cost a
    // VM its port forwards, so wait up to 5 seconds for the lock instead.
    connection
        .busy_timeout(std::time::Duration::from_secs(5))
        .map_err(|error| {
            format!(
                "cannot set a busy timeout on {}: {error}",
                database.display()
            )
        })?;
    let mut statement = connection
        .prepare(
            "SELECT vm_port, host_port, tcp, udp FROM port_mappings \
             WHERE vm_hash = ?1 AND deleted_at IS NULL ORDER BY id",
        )
        .map_err(|error| format!("cannot query port_mappings: {error}"))?;
    let rows = statement
        .query_map([vm_hash], |row| {
            Ok(PortForward {
                vm_port: row.get(0)?,
                host_port: row.get(1)?,
                tcp: row.get(2)?,
                udp: row.get(3)?,
            })
        })
        .map_err(|error| format!("cannot read port_mappings: {error}"))?;

    // Fold like the Python dict build: last row wins per vm_port, first
    // occurrence keeps its position.
    let mut forwards: Vec<PortForward> = Vec::new();
    for row in rows {
        let row = row.map_err(|error| format!("cannot read port_mappings row: {error}"))?;
        match forwards
            .iter_mut()
            .find(|forward| forward.vm_port == row.vm_port)
        {
            Some(existing) => *existing = row,
            None => forwards.push(row),
        }
    }
    Ok(forwards)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_fixtures;

    fn fixture_db() -> std::path::PathBuf {
        test_fixtures::fixtures_dir().join("supervisor.sqlite3")
    }

    #[test]
    fn loads_active_mappings_in_rowid_order_skipping_soft_deleted() {
        let forwards = load_port_forwards(&fixture_db(), test_fixtures::QEMU_HASH).unwrap();
        // The fixture holds a soft-deleted 22->24022 row that must not
        // surface, then the active 22->24000 (tcp) and 8080->24001
        // (tcp+udp) rows.
        assert_eq!(
            forwards,
            vec![
                PortForward {
                    vm_port: 22,
                    host_port: 24000,
                    tcp: true,
                    udp: false,
                },
                PortForward {
                    vm_port: 8080,
                    host_port: 24001,
                    tcp: true,
                    udp: true,
                },
            ]
        );
    }

    #[test]
    fn a_vm_without_rows_gets_no_mappings() {
        let forwards = load_port_forwards(&fixture_db(), test_fixtures::GPU_HASH).unwrap();
        assert!(forwards.is_empty());
    }

    #[test]
    fn a_missing_database_means_no_mappings() {
        let tmp = tempfile::tempdir().unwrap();
        let forwards =
            load_port_forwards(&tmp.path().join("absent.sqlite3"), test_fixtures::QEMU_HASH)
                .unwrap();
        assert!(forwards.is_empty());
    }

    #[test]
    fn a_database_without_the_table_is_an_error() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("empty.sqlite3");
        rusqlite::Connection::open(&path).unwrap();
        let error = load_port_forwards(&path, test_fixtures::QEMU_HASH).unwrap_err();
        assert!(error.contains("port_mappings"));
    }
}
