//! Shared constants for the committed test fixtures under
//! `tests/fixtures/`, used by unit tests and the crate's integration tests.
//!
//! The fixtures are generated by the actual Python models (pydantic
//! `Configuration` for the controller JSONs, SQLAlchemy `PortMapping` for
//! the sqlite database) via `scripts/generate_rust_fixtures.py` at the
//! repository root; regenerate with:
//!
//! ```sh
//! venv/bin/python scripts/generate_rust_fixtures.py
//! ```
//!
//! The hashes are `sha256("rust-fixture-<name>")`, so the script and these
//! constants stay in sync without copy-paste drift risk.

/// A plain QEMU instance (vm_index 3, 2 vCPUs, 2048 MiB, one host volume).
pub const QEMU_HASH: &str = "c1108e43cb5d47e6ceb5bbbb31a8f12390573dc6fda96915b1a6cac5bc2ce2e8";

/// A QEMU instance with one GPU attached (vm_index 4).
pub const GPU_HASH: &str = "f2fb0d483af18aeef7747640de08f47c6ecf4190236f48779f7597508ca009ce";

/// A confidential (SEV) QEMU instance (vm_index 5, policy 0x5 = SEV-ES).
pub const CONFIDENTIAL_HASH: &str =
    "1806f3480aad78e65831caf9031868e28dd53ac2b86fcb2ccdb24cb324675198";

/// Appears only in the sqlite fixture (no controller config): its port
/// mappings must never surface through the world view.
pub const PORTS_ONLY_HASH: &str =
    "b797c7b5d8d8acc7839c9212f8fbf8a11fcb5056b9e117c9adc2941bdac3936b";

/// The written-controller-config.json fixture VM (vm_index 6, one host
/// volume, one GPU): the byte-parity target of the config writer.
pub const CREATED_HASH: &str = "66fc20349b370dd2d15cf9fdf2a0b59ccb906da315619c9f1c34cbcc00e8309c";

/// The committed fixtures directory.
pub fn fixtures_dir() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}
