//! Shared constants for the committed test fixtures under
//! `tests/fixtures/`, used by unit tests and the crate's integration tests.
//!
//! The fixtures were generated by the Python daemon's actual models (pydantic
//! `Configuration` for the controller JSONs, SQLAlchemy `PortMapping` for
//! the sqlite database) by the since-removed `scripts/generate_rust_fixtures.py`,
//! captured from the Python daemon's own models before that daemon was removed (2026-08); they are frozen goldens now, edit them only to record a deliberate change.
//!
//! The hashes are `sha256("rust-fixture-<name>")`, so the generator and these
//! constants stayed in sync without copy-paste drift risk.

/// A plain QEMU instance (vm_index 3, 2 vCPUs, 2048 MiB, one host volume).
pub const QEMU_HASH: &str = "c1108e43cb5d47e6ceb5bbbb31a8f12390573dc6fda96915b1a6cac5bc2ce2e8";

/// A QEMU instance with one GPU attached (vm_index 4).
pub const GPU_HASH: &str = "f2fb0d483af18aeef7747640de08f47c6ecf4190236f48779f7597508ca009ce";

/// A confidential (SEV) QEMU instance (vm_index 5, policy 0x5 = SEV-ES).
pub const CONFIDENTIAL_HASH: &str =
    "1806f3480aad78e65831caf9031868e28dd53ac2b86fcb2ccdb24cb324675198";

/// Appears only in the sqlite fixture (no controller config): its port
/// mappings must never surface through the world view.
pub const PORTS_ONLY_HASH: &str =
    "b797c7b5d8d8acc7839c9212f8fbf8a11fcb5056b9e117c9adc2941bdac3936b";

/// The written-controller-config.json fixture VM (vm_index 6, one host
/// volume, one GPU): the byte-parity target of the config writer.
pub const CREATED_HASH: &str = "66fc20349b370dd2d15cf9fdf2a0b59ccb906da315619c9f1c34cbcc00e8309c";

/// The committed fixtures directory.
pub fn fixtures_dir() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

/// A shared chronological event log for the test fakes (FakeSystemd,
/// FakeTapBackend, StaticRuleset): one clone attached to each fake makes
/// cross-seam ordering observable, so a tap-created-after-unit-start bug
/// fails a cargo test instead of only a root integration run.
#[derive(Debug, Default, Clone)]
pub struct EventLog(std::sync::Arc<std::sync::Mutex<Vec<String>>>);

impl EventLog {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn record(&self, event: &str) {
        self.0
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .push(event.to_string());
    }

    pub fn events(&self) -> Vec<String> {
        self.0
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .clone()
    }

    /// Index of the first event starting with `prefix`; panics with the
    /// full log when absent (assertion helper).
    pub fn position(&self, prefix: &str) -> usize {
        let events = self.events();
        events
            .iter()
            .position(|event| event.starts_with(prefix))
            .unwrap_or_else(|| panic!("no event starting with {prefix:?} in {events:?}"))
    }
}
