# Generated by Django 3.2.4 on 2021-07-02 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("date", models.DateTimeField(auto_created=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the blog article", max_length=256
                    ),
                ),
                ("body", models.TextField(help_text="Body of the blog article")),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("date", models.DateTimeField(auto_created=True, auto_now_add=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=1024)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.article"
                    ),
                ),
            ],
        ),
    ]
