//! Conformance: the Rust `build_confidential_argv` must reproduce the argv the
//! real Python `QemuConfidentialVM.start()` exec's, byte for byte.
//!
//! Each fixture under `tests/conformance/controller_argv_confidential/` was
//! generated by `scripts/generate_controller_argv_fixtures.py` from the actual
//! Python `QemuConfidentialVM` (the parity oracle), never hand-written. The
//! Python `secure_encryption_info()` host-CPUID read is monkeypatched there to
//! a fixed value; each fixture records that value under `sev_host_info` so this
//! test injects the identical [`SevHostInfo`] (a non-SEV CI host cannot read
//! it). A fixture is `{config_json, expected_argv, sev_host_info}`: parse the
//! config, inject the sev info, run the builder, assert equality.

use std::path::Path;

use serde::Deserialize;
use supervisor_controller::config::QemuConfig;
use supervisor_controller::cpuid::SevHostInfo;
use supervisor_controller::qemu::build_confidential_argv;

#[derive(Debug, Deserialize)]
struct SevHostInfoFixture {
    cbitpos: u32,
    reduced_phys_bits: u32,
}

#[derive(Debug, Deserialize)]
struct Fixture {
    config_json: serde_json::Value,
    expected_argv: Vec<String>,
    sev_host_info: SevHostInfoFixture,
}

fn fixture_dir() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/conformance/controller_argv_confidential")
}

fn load(name: &str) -> Fixture {
    let path = fixture_dir().join(format!("{name}.json"));
    let contents = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("cannot read fixture {}: {error}", path.display()));
    serde_json::from_str(&contents)
        .unwrap_or_else(|error| panic!("cannot parse fixture {}: {error}", path.display()))
}

fn assert_parity(name: &str) {
    let fixture = load(name);
    let config = QemuConfig::from_json(&fixture.config_json.to_string())
        .unwrap_or_else(|error| panic!("fixture {name} config did not parse: {error}"));
    assert!(
        config.is_confidential(),
        "fixture {name} is not a confidential config"
    );
    let sev = SevHostInfo {
        cbitpos: fixture.sev_host_info.cbitpos,
        reduced_phys_bits: fixture.sev_host_info.reduced_phys_bits,
    };
    let argv = build_confidential_argv(&config, sev);
    assert_eq!(
        argv, fixture.expected_argv,
        "confidential argv mismatch for fixture {name}"
    );
}

macro_rules! parity_case {
    ($test_name:ident, $fixture:literal) => {
        #[test]
        fn $test_name() {
            assert_parity($fixture);
        }
    };
}

parity_case!(minimal, "minimal");
parity_case!(with_nic, "with_nic");
parity_case!(with_cloud_init, "with_cloud_init");
parity_case!(host_volume, "host_volume");
parity_case!(gpu, "gpu");
parity_case!(sev_es_policy, "sev_es_policy");

/// Every fixture in the directory is covered by a named case above; guard
/// against a fixture being added to the battery without a matching assertion.
#[test]
fn every_confidential_fixture_has_a_case() {
    let declared = [
        "minimal",
        "with_nic",
        "with_cloud_init",
        "host_volume",
        "gpu",
        "sev_es_policy",
    ];
    let mut on_disk: Vec<String> = std::fs::read_dir(fixture_dir())
        .unwrap()
        .filter_map(|entry| {
            let name = entry.unwrap().file_name().to_string_lossy().into_owned();
            name.strip_suffix(".json").map(str::to_string)
        })
        .collect();
    on_disk.sort();
    let mut declared: Vec<String> = declared.iter().map(|name| name.to_string()).collect();
    declared.sort();
    assert_eq!(on_disk, declared, "fixture set and declared cases diverged");
}
