//! Conformance: the Rust `build_argv` must reproduce the argv the real Python
//! `QemuVM.start()` exec's, byte for byte.
//!
//! Each fixture under `tests/conformance/controller_argv/` was generated by
//! `scripts/generate_controller_argv_fixtures.py` from the actual Python
//! QemuVM (the parity oracle), never hand-written. A fixture is a JSON pair
//! `{config_json, expected_argv}`: parse `config_json` with the Rust config
//! reader, run the builder, assert the argv equals `expected_argv` exactly.

use std::path::Path;

use serde::Deserialize;
use supervisor_controller::config::QemuConfig;
use supervisor_controller::qemu::build_argv;

#[derive(Debug, Deserialize)]
struct Fixture {
    config_json: serde_json::Value,
    expected_argv: Vec<String>,
}

fn fixture_dir() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/conformance/controller_argv")
}

fn load(name: &str) -> Fixture {
    let path = fixture_dir().join(format!("{name}.json"));
    let contents = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("cannot read fixture {}: {error}", path.display()));
    serde_json::from_str(&contents)
        .unwrap_or_else(|error| panic!("cannot parse fixture {}: {error}", path.display()))
}

fn assert_parity(name: &str) {
    let fixture = load(name);
    let config = QemuConfig::from_json(&fixture.config_json.to_string())
        .unwrap_or_else(|error| panic!("fixture {name} config did not parse: {error}"));
    let argv = build_argv(&config);
    assert_eq!(
        argv, fixture.expected_argv,
        "argv mismatch for fixture {name}"
    );
}

macro_rules! parity_case {
    ($test_name:ident, $fixture:literal) => {
        #[test]
        fn $test_name() {
            assert_parity($fixture);
        }
    };
}

parity_case!(minimal, "minimal");
parity_case!(with_nic, "with_nic");
parity_case!(with_cloud_init, "with_cloud_init");
parity_case!(host_volume_ro, "host_volume_ro");
parity_case!(host_volume_rw, "host_volume_rw");
parity_case!(host_volumes_multiple, "host_volumes_multiple");
parity_case!(gpu_x_vga, "gpu_x_vga");
parity_case!(gpu_no_x_vga, "gpu_no_x_vga");
parity_case!(gpu_multiple, "gpu_multiple");
parity_case!(no_gpu_full, "no_gpu_full");
parity_case!(gpu_full, "gpu_full");

/// Every fixture in the directory is covered by a named case above; guard
/// against a fixture being added to the battery without a matching assertion.
#[test]
fn every_fixture_has_a_case() {
    let declared = [
        "minimal",
        "with_nic",
        "with_cloud_init",
        "host_volume_ro",
        "host_volume_rw",
        "host_volumes_multiple",
        "gpu_x_vga",
        "gpu_no_x_vga",
        "gpu_multiple",
        "no_gpu_full",
        "gpu_full",
    ];
    let mut on_disk: Vec<String> = std::fs::read_dir(fixture_dir())
        .unwrap()
        .filter_map(|entry| {
            let name = entry.unwrap().file_name().to_string_lossy().into_owned();
            name.strip_suffix(".json").map(str::to_string)
        })
        .collect();
    on_disk.sort();
    let mut declared: Vec<String> = declared.iter().map(|name| name.to_string()).collect();
    declared.sort();
    assert_eq!(on_disk, declared, "fixture set and declared cases diverged");
}
