name: 'Build Aleph Runtime Rootfs'
description: 'Builds the Aleph runtime rootfs for a specified OS'
inputs:
  os:
    description: 'Operating system to build (e.g., debian-12)'
    required: true
    default: 'debian-12'
  artifact-name:
    description: 'Name of the artifact to upload'
    required: true
outputs:
  artifact-name:
    description: 'Name of the artifact'
    value: ${{ inputs.artifact-name }}
  artifact-path:
    description: 'Path to the built rootfs'
    value: runtimes/aleph-${{ inputs.os }}-python/rootfs.squashfs
runs:
  using: 'composite'
  steps:
    - name: Workaround github issue https://github.com/actions/runner-images/issues/7192
      shell: bash
      run: sudo echo RESET grub-efi/install_devices | sudo debconf-communicate grub-pc

    - name: Install dependencies and build rootfs
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y debootstrap
        cd runtimes/aleph-${{ inputs.os }}-python && sudo ./create_disk_image.sh && cd ../..

    - name: Upload rootfs artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: runtimes/aleph-${{ inputs.os }}-python/rootfs.squashfs
