"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
SPDX-License-Identifier: MIT

Aleph VM Supervisor contract.

This service is the infra-only boundary between the network-agent
(Aleph orchestration: HTTP CRN API, messages, payments, allocations)
and the supervisor (controllers, hypervisors, networking, systemd).
Reference: docs/plans/2026-05-28-aleph-vm-architecture-
backport-design.md.

SAME-HOST INVARIANT: this is a process boundary, not a network
boundary. Agent and supervisor share a filesystem; every path in this
contract (kernel_path, DiskConfig.path, TeeConfig.session_dir,
VmInfo.guest_channel_path, migration directories) is exchanged by
reference and must resolve identically on both sides, with file
ownership that lets the supervisor (and its jailer) read what the
agent downloaded. A remote supervisor would need a content-transfer
mechanism this contract deliberately does not define.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _HealthStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _HealthStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_HealthStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    HEALTH_STATUS_UNSPECIFIED: _HealthStatus.ValueType  # 0
    HEALTH_STATUS_OK: _HealthStatus.ValueType  # 1
    HEALTH_STATUS_DEGRADED: _HealthStatus.ValueType  # 2

class HealthStatus(_HealthStatus, metaclass=_HealthStatusEnumTypeWrapper): ...

HEALTH_STATUS_UNSPECIFIED: HealthStatus.ValueType  # 0
HEALTH_STATUS_OK: HealthStatus.ValueType  # 1
HEALTH_STATUS_DEGRADED: HealthStatus.ValueType  # 2
global___HealthStatus = HealthStatus

class _Backend:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BackendEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Backend.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BACKEND_UNSPECIFIED: _Backend.ValueType  # 0
    BACKEND_FIRECRACKER: _Backend.ValueType  # 1
    BACKEND_QEMU: _Backend.ValueType  # 2

class Backend(_Backend, metaclass=_BackendEnumTypeWrapper):
    """── Lifecycle ────────────────────────────────────────────────────────────

    The VMM. Orthogonal to confidential computing: a confidential VM is
    `backend: BACKEND_QEMU` plus a `tee` config (whose presence selects the
    confidential launch path).
    """

BACKEND_UNSPECIFIED: Backend.ValueType  # 0
BACKEND_FIRECRACKER: Backend.ValueType  # 1
BACKEND_QEMU: Backend.ValueType  # 2
global___Backend = Backend

class _TeeBackend:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TeeBackendEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TeeBackend.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TEE_BACKEND_UNSPECIFIED: _TeeBackend.ValueType  # 0
    """no TEE"""
    TEE_BACKEND_SEV: _TeeBackend.ValueType  # 1
    """AMD SEV / SEV-ES; the mode is refined by TeeConfig.policy"""
    TEE_BACKEND_SEV_SNP: _TeeBackend.ValueType  # 2
    TEE_BACKEND_TDX: _TeeBackend.ValueType  # 3
    TEE_BACKEND_NVIDIA_CC: _TeeBackend.ValueType  # 4

class TeeBackend(_TeeBackend, metaclass=_TeeBackendEnumTypeWrapper):
    """TEE attestation backend (see TeeConfig)."""

TEE_BACKEND_UNSPECIFIED: TeeBackend.ValueType  # 0
"""no TEE"""
TEE_BACKEND_SEV: TeeBackend.ValueType  # 1
"""AMD SEV / SEV-ES; the mode is refined by TeeConfig.policy"""
TEE_BACKEND_SEV_SNP: TeeBackend.ValueType  # 2
TEE_BACKEND_TDX: TeeBackend.ValueType  # 3
TEE_BACKEND_NVIDIA_CC: TeeBackend.ValueType  # 4
global___TeeBackend = TeeBackend

class _VmStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _VmStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_VmStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    VM_STATUS_UNSPECIFIED: _VmStatus.ValueType  # 0
    VM_STATUS_DEFINED: _VmStatus.ValueType  # 1
    VM_STATUS_BOOTING: _VmStatus.ValueType  # 2
    VM_STATUS_RUNNING: _VmStatus.ValueType  # 3
    VM_STATUS_STOPPING: _VmStatus.ValueType  # 4
    VM_STATUS_STOPPED: _VmStatus.ValueType  # 5
    VM_STATUS_FAILED: _VmStatus.ValueType  # 6

class VmStatus(_VmStatus, metaclass=_VmStatusEnumTypeWrapper): ...

VM_STATUS_UNSPECIFIED: VmStatus.ValueType  # 0
VM_STATUS_DEFINED: VmStatus.ValueType  # 1
VM_STATUS_BOOTING: VmStatus.ValueType  # 2
VM_STATUS_RUNNING: VmStatus.ValueType  # 3
VM_STATUS_STOPPING: VmStatus.ValueType  # 4
VM_STATUS_STOPPED: VmStatus.ValueType  # 5
VM_STATUS_FAILED: VmStatus.ValueType  # 6
global___VmStatus = VmStatus

class _ConfidentialMode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ConfidentialModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ConfidentialMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CONFIDENTIAL_MODE_NONE: _ConfidentialMode.ValueType  # 0
    CONFIDENTIAL_MODE_SEV: _ConfidentialMode.ValueType  # 1
    CONFIDENTIAL_MODE_SEV_ES: _ConfidentialMode.ValueType  # 2
    CONFIDENTIAL_MODE_SEV_SNP: _ConfidentialMode.ValueType  # 3

class ConfidentialMode(_ConfidentialMode, metaclass=_ConfidentialModeEnumTypeWrapper):
    """The confidential-computing mode a VM is actually running under. Precise by
    design: the agent reduces this to a boolean for Aleph APIs; the contract does
    not pre-reduce it. SEV vs SEV-ES is distinguished by the AMD SEV policy;
    SEV-SNP is a distinct measured-boot launch path.
    """

CONFIDENTIAL_MODE_NONE: ConfidentialMode.ValueType  # 0
CONFIDENTIAL_MODE_SEV: ConfidentialMode.ValueType  # 1
CONFIDENTIAL_MODE_SEV_ES: ConfidentialMode.ValueType  # 2
CONFIDENTIAL_MODE_SEV_SNP: ConfidentialMode.ValueType  # 3
global___ConfidentialMode = ConfidentialMode

class _Protocol:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ProtocolEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Protocol.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PROTOCOL_UNSPECIFIED: _Protocol.ValueType  # 0
    PROTOCOL_TCP: _Protocol.ValueType  # 1
    PROTOCOL_UDP: _Protocol.ValueType  # 2

class Protocol(_Protocol, metaclass=_ProtocolEnumTypeWrapper):
    """── Port forwarding ──────────────────────────────────────────────────────"""

PROTOCOL_UNSPECIFIED: Protocol.ValueType  # 0
PROTOCOL_TCP: Protocol.ValueType  # 1
PROTOCOL_UDP: Protocol.ValueType  # 2
global___Protocol = Protocol

class _ErrorCode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ErrorCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ErrorCode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ERROR_CODE_UNSPECIFIED: _ErrorCode.ValueType  # 0
    ERROR_CODE_VM_NOT_FOUND: _ErrorCode.ValueType  # 1
    """Lifecycle"""
    ERROR_CODE_VM_ALREADY_EXISTS: _ErrorCode.ValueType  # 2
    ERROR_CODE_INSUFFICIENT_RESOURCES: _ErrorCode.ValueType  # 3
    ERROR_CODE_RESOURCE_DOWNLOAD_FAILED: _ErrorCode.ValueType  # 4
    """Resource preparation"""
    ERROR_CODE_FILE_TOO_LARGE: _ErrorCode.ValueType  # 5
    ERROR_CODE_VM_SETUP_FAILED: _ErrorCode.ValueType  # 6
    """Backend"""
    ERROR_CODE_MICROVM_INIT_FAILED: _ErrorCode.ValueType  # 7
    ERROR_CODE_INVALID_BACKEND: _ErrorCode.ValueType  # 8
    ERROR_CODE_TEE_UNAVAILABLE: _ErrorCode.ValueType  # 9
    ERROR_CODE_PORT_UNAVAILABLE: _ErrorCode.ValueType  # 10
    """Networking"""
    ERROR_CODE_HOST_NOT_FOUND: _ErrorCode.ValueType  # 11
    ERROR_CODE_INTERNAL: _ErrorCode.ValueType  # 99
    """Catch-all"""

class ErrorCode(_ErrorCode, metaclass=_ErrorCodeEnumTypeWrapper):
    """── Wire error vocabulary ────────────────────────────────────────────────

    Closed enum of errors the supervisor can return. Server side: map
    backend exceptions (FileTooLargeError, VmSetupError,
    MicroVMFailedInitError, ResourceDownloadError,
    InsufficientResourcesError, HostNotFoundError, ...) into this enum
    and attach an ErrorDetail in the gRPC status trailers. Agent side:
    catch grpc.AioRpcError, read the trailer, translate to HTTP.
    """

ERROR_CODE_UNSPECIFIED: ErrorCode.ValueType  # 0
ERROR_CODE_VM_NOT_FOUND: ErrorCode.ValueType  # 1
"""Lifecycle"""
ERROR_CODE_VM_ALREADY_EXISTS: ErrorCode.ValueType  # 2
ERROR_CODE_INSUFFICIENT_RESOURCES: ErrorCode.ValueType  # 3
ERROR_CODE_RESOURCE_DOWNLOAD_FAILED: ErrorCode.ValueType  # 4
"""Resource preparation"""
ERROR_CODE_FILE_TOO_LARGE: ErrorCode.ValueType  # 5
ERROR_CODE_VM_SETUP_FAILED: ErrorCode.ValueType  # 6
"""Backend"""
ERROR_CODE_MICROVM_INIT_FAILED: ErrorCode.ValueType  # 7
ERROR_CODE_INVALID_BACKEND: ErrorCode.ValueType  # 8
ERROR_CODE_TEE_UNAVAILABLE: ErrorCode.ValueType  # 9
ERROR_CODE_PORT_UNAVAILABLE: ErrorCode.ValueType  # 10
"""Networking"""
ERROR_CODE_HOST_NOT_FOUND: ErrorCode.ValueType  # 11
ERROR_CODE_INTERNAL: ErrorCode.ValueType  # 99
"""Catch-all"""
global___ErrorCode = ErrorCode

@typing.final
class HealthRequest(google.protobuf.message.Message):
    """── Host ─────────────────────────────────────────────────────────────────"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___HealthRequest = HealthRequest

@typing.final
class HealthResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    VM_COUNT_FIELD_NUMBER: builtins.int
    status: global___HealthStatus.ValueType
    vm_count: builtins.int
    def __init__(
        self,
        *,
        status: global___HealthStatus.ValueType = ...,
        vm_count: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status", "vm_count", b"vm_count"]) -> None: ...

global___HealthResponse = HealthResponse

@typing.final
class GetHostInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetHostInfoRequest = GetHostInfoRequest

@typing.final
class HostInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CPU_COUNT_FIELD_NUMBER: builtins.int
    CPU_ARCHITECTURE_FIELD_NUMBER: builtins.int
    CPU_VENDOR_FIELD_NUMBER: builtins.int
    CPU_MODEL_FIELD_NUMBER: builtins.int
    CPU_FREQUENCY_MHZ_FIELD_NUMBER: builtins.int
    MEMORY_MIB_FIELD_NUMBER: builtins.int
    MEMORY_TYPE_FIELD_NUMBER: builtins.int
    MEMORY_CLOCK_MHZ_FIELD_NUMBER: builtins.int
    NUMA_NODES_FIELD_NUMBER: builtins.int
    GPUS_FIELD_NUMBER: builtins.int
    SEV_SUPPORTED_FIELD_NUMBER: builtins.int
    SEV_ES_SUPPORTED_FIELD_NUMBER: builtins.int
    SEV_SNP_SUPPORTED_FIELD_NUMBER: builtins.int
    TDX_SUPPORTED_FIELD_NUMBER: builtins.int
    HOSTNAME_FIELD_NUMBER: builtins.int
    KERNEL_VERSION_FIELD_NUMBER: builtins.int
    HOST_IPV4_FIELD_NUMBER: builtins.int
    AVAILABLE_DISK_BYTES_FIELD_NUMBER: builtins.int
    GPU_INVENTORY_JSON_FIELD_NUMBER: builtins.int
    AVAILABLE_GPUS_JSON_FIELD_NUMBER: builtins.int
    cpu_count: builtins.int
    """CPU"""
    cpu_architecture: builtins.str
    """e.g. "x86_64", "aarch64" """
    cpu_vendor: builtins.str
    """e.g. "AuthenticAMD", "GenuineIntel" """
    cpu_model: builtins.str
    """e.g. "AMD EPYC 9354P" """
    cpu_frequency_mhz: builtins.int
    """base clock"""
    memory_mib: builtins.int
    """Memory"""
    memory_type: builtins.str
    """e.g. "DDR5" """
    memory_clock_mhz: builtins.int
    sev_supported: builtins.bool
    """TEE support
    SEV (base AMD memory encryption)
    """
    sev_es_supported: builtins.bool
    """SEV-ES (encrypted register state)"""
    sev_snp_supported: builtins.bool
    """SEV-SNP (full attestation)"""
    tdx_supported: builtins.bool
    hostname: builtins.str
    """Identity"""
    kernel_version: builtins.str
    host_ipv4: builtins.str
    """Networking
    primary external IPv4 of the host; empty when host networking is disabled
    """
    available_disk_bytes: builtins.int
    """Usage-aware figures the agent's /about endpoints surface"""
    gpu_inventory_json: builtins.str
    """list[dict] as JSON; rich agent GPU inventory"""
    available_gpus_json: builtins.str
    """list[dict] as JSON"""
    @property
    def numa_nodes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NumaNode]:
        """Topology"""

    @property
    def gpus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GpuDevice]: ...
    def __init__(
        self,
        *,
        cpu_count: builtins.int = ...,
        cpu_architecture: builtins.str = ...,
        cpu_vendor: builtins.str = ...,
        cpu_model: builtins.str = ...,
        cpu_frequency_mhz: builtins.int = ...,
        memory_mib: builtins.int = ...,
        memory_type: builtins.str = ...,
        memory_clock_mhz: builtins.int = ...,
        numa_nodes: collections.abc.Iterable[global___NumaNode] | None = ...,
        gpus: collections.abc.Iterable[global___GpuDevice] | None = ...,
        sev_supported: builtins.bool = ...,
        sev_es_supported: builtins.bool = ...,
        sev_snp_supported: builtins.bool = ...,
        tdx_supported: builtins.bool = ...,
        hostname: builtins.str = ...,
        kernel_version: builtins.str = ...,
        host_ipv4: builtins.str = ...,
        available_disk_bytes: builtins.int = ...,
        gpu_inventory_json: builtins.str = ...,
        available_gpus_json: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["available_disk_bytes", b"available_disk_bytes", "available_gpus_json", b"available_gpus_json", "cpu_architecture", b"cpu_architecture", "cpu_count", b"cpu_count", "cpu_frequency_mhz", b"cpu_frequency_mhz", "cpu_model", b"cpu_model", "cpu_vendor", b"cpu_vendor", "gpu_inventory_json", b"gpu_inventory_json", "gpus", b"gpus", "host_ipv4", b"host_ipv4", "hostname", b"hostname", "kernel_version", b"kernel_version", "memory_clock_mhz", b"memory_clock_mhz", "memory_mib", b"memory_mib", "memory_type", b"memory_type", "numa_nodes", b"numa_nodes", "sev_es_supported", b"sev_es_supported", "sev_snp_supported", b"sev_snp_supported", "sev_supported", b"sev_supported", "tdx_supported", b"tdx_supported"]) -> None: ...

global___HostInfo = HostInfo

@typing.final
class NumaNode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INDEX_FIELD_NUMBER: builtins.int
    CPU_COUNT_FIELD_NUMBER: builtins.int
    MEMORY_MIB_FIELD_NUMBER: builtins.int
    index: builtins.int
    cpu_count: builtins.int
    memory_mib: builtins.int
    def __init__(
        self,
        *,
        index: builtins.int = ...,
        cpu_count: builtins.int = ...,
        memory_mib: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cpu_count", b"cpu_count", "index", b"index", "memory_mib", b"memory_mib"]) -> None: ...

global___NumaNode = NumaNode

@typing.final
class GpuDevice(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PCI_HOST_FIELD_NUMBER: builtins.int
    DEVICE_ID_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    SUPPORTS_X_VGA_FIELD_NUMBER: builtins.int
    CC_MODE_FIELD_NUMBER: builtins.int
    pci_host: builtins.str
    """e.g. "0000:01:00.0" """
    device_id: builtins.str
    """vendor:device"""
    model: builtins.str
    supports_x_vga: builtins.bool
    cc_mode: builtins.str
    """NVIDIA confidential-computing mode: "on", "devtools", "off"; empty when unknown"""
    def __init__(
        self,
        *,
        pci_host: builtins.str = ...,
        device_id: builtins.str = ...,
        model: builtins.str = ...,
        supports_x_vga: builtins.bool = ...,
        cc_mode: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cc_mode", b"cc_mode", "device_id", b"device_id", "model", b"model", "pci_host", b"pci_host", "supports_x_vga", b"supports_x_vga"]) -> None: ...

global___GpuDevice = GpuDevice

@typing.final
class VmSpec(google.protobuf.message.Message):
    """The full definition of a VM the supervisor runs. Sent to CreateVm and
    returned verbatim by GetVmSpec (so a restarted client can rebuild its
    records). Named VmSpec, not CreateVmRequest, because it IS the spec, not a
    one-shot RPC payload.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    BACKEND_FIELD_NUMBER: builtins.int
    KERNEL_PATH_FIELD_NUMBER: builtins.int
    INITRD_PATH_FIELD_NUMBER: builtins.int
    DISKS_FIELD_NUMBER: builtins.int
    VCPUS_FIELD_NUMBER: builtins.int
    MEMORY_MIB_FIELD_NUMBER: builtins.int
    TEE_FIELD_NUMBER: builtins.int
    NETWORK_FIELD_NUMBER: builtins.int
    GPUS_FIELD_NUMBER: builtins.int
    NUMA_NODE_FIELD_NUMBER: builtins.int
    PERSISTENT_FIELD_NUMBER: builtins.int
    SSH_AUTHORIZED_KEYS_FIELD_NUMBER: builtins.int
    GUEST_CHANNEL_FIELD_NUMBER: builtins.int
    HOSTNAME_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    """agent-issued id, opaque to supervisor"""
    backend: global___Backend.ValueType
    kernel_path: builtins.str
    """empty for disk-boot"""
    initrd_path: builtins.str
    """empty for disk-boot"""
    vcpus: builtins.int
    memory_mib: builtins.int
    numa_node: builtins.int
    """requested placement (0-indexed). Unset = auto. See VmInfo.numa_node for the effective placement."""
    persistent: builtins.bool
    """supervisor wraps in systemd if true"""
    hostname: builtins.str
    """Guest hostname for provisioning (cloud-init). Naming is the client's
    business; empty falls back to a mechanical derivation from vm_id.
    """
    @property
    def disks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DiskConfig]: ...
    @property
    def tee(self) -> global___TeeConfig:
        """presence selects the confidential launch path"""

    @property
    def network(self) -> global___NetworkConfig: ...
    @property
    def gpus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GpuConfig]: ...
    @property
    def ssh_authorized_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """guest cloud-init SSH keys (agent-provided)"""

    @property
    def guest_channel(self) -> global___GuestChannel:
        """Optional host⇄guest control channel (Firecracker vsock today; a QEMU
        backend may implement it with virtio-vsock). When present, the supervisor
        exposes the channel and waits for the guest's ready signal on
        `ready_port` as part of boot: the VM reports RUNNING only after the
        signal. What is spoken over the channel is the client's business, opaque
        to the supervisor.
        """

    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        backend: global___Backend.ValueType = ...,
        kernel_path: builtins.str = ...,
        initrd_path: builtins.str = ...,
        disks: collections.abc.Iterable[global___DiskConfig] | None = ...,
        vcpus: builtins.int = ...,
        memory_mib: builtins.int = ...,
        tee: global___TeeConfig | None = ...,
        network: global___NetworkConfig | None = ...,
        gpus: collections.abc.Iterable[global___GpuConfig] | None = ...,
        numa_node: builtins.int | None = ...,
        persistent: builtins.bool = ...,
        ssh_authorized_keys: collections.abc.Iterable[builtins.str] | None = ...,
        guest_channel: global___GuestChannel | None = ...,
        hostname: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_guest_channel", b"_guest_channel", "_numa_node", b"_numa_node", "guest_channel", b"guest_channel", "network", b"network", "numa_node", b"numa_node", "tee", b"tee"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_guest_channel", b"_guest_channel", "_numa_node", b"_numa_node", "backend", b"backend", "disks", b"disks", "gpus", b"gpus", "guest_channel", b"guest_channel", "hostname", b"hostname", "initrd_path", b"initrd_path", "kernel_path", b"kernel_path", "memory_mib", b"memory_mib", "network", b"network", "numa_node", b"numa_node", "persistent", b"persistent", "ssh_authorized_keys", b"ssh_authorized_keys", "tee", b"tee", "vcpus", b"vcpus", "vm_id", b"vm_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_guest_channel", b"_guest_channel"]) -> typing.Literal["guest_channel"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_numa_node", b"_numa_node"]) -> typing.Literal["numa_node"] | None: ...

global___VmSpec = VmSpec

@typing.final
class GuestChannel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    READY_PORT_FIELD_NUMBER: builtins.int
    READY_TIMEOUT_SECS_FIELD_NUMBER: builtins.int
    ready_port: builtins.int
    """the guest connects here to signal readiness"""
    ready_timeout_secs: builtins.int
    """How long the supervisor waits for the ready signal before failing the
    boot. Workload policy: the client knows how long its guest image
    legitimately takes. 0 = supervisor default.
    """
    def __init__(
        self,
        *,
        ready_port: builtins.int = ...,
        ready_timeout_secs: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ready_port", b"ready_port", "ready_timeout_secs", b"ready_timeout_secs"]) -> None: ...

global___GuestChannel = GuestChannel

@typing.final
class DiskConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Format:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _FormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DiskConfig._Format.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        FORMAT_UNSPECIFIED: DiskConfig._Format.ValueType  # 0
        FORMAT_RAW: DiskConfig._Format.ValueType  # 1
        FORMAT_QCOW2: DiskConfig._Format.ValueType  # 2
        FORMAT_SQUASHFS: DiskConfig._Format.ValueType  # 3

    class Format(_Format, metaclass=_FormatEnumTypeWrapper): ...
    FORMAT_UNSPECIFIED: DiskConfig.Format.ValueType  # 0
    FORMAT_RAW: DiskConfig.Format.ValueType  # 1
    FORMAT_QCOW2: DiskConfig.Format.ValueType  # 2
    FORMAT_SQUASHFS: DiskConfig.Format.ValueType  # 3

    class _DiskRole:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DiskRoleEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DiskConfig._DiskRole.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        DISK_ROLE_UNSPECIFIED: DiskConfig._DiskRole.ValueType  # 0
        DISK_ROLE_ROOTFS: DiskConfig._DiskRole.ValueType  # 1
        DISK_ROLE_EXTRA: DiskConfig._DiskRole.ValueType  # 2

    class DiskRole(_DiskRole, metaclass=_DiskRoleEnumTypeWrapper):
        """Mechanism-only roles: the supervisor needs to know which disk is the
        root device; everything else is attached in spec order (guest device
        names are deterministic from that order, which is how the client maps
        its workload semantics — code, data, caches — onto devices).
        """

    DISK_ROLE_UNSPECIFIED: DiskConfig.DiskRole.ValueType  # 0
    DISK_ROLE_ROOTFS: DiskConfig.DiskRole.ValueType  # 1
    DISK_ROLE_EXTRA: DiskConfig.DiskRole.ValueType  # 2

    PATH_FIELD_NUMBER: builtins.int
    READONLY_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    path: builtins.str
    """absolute host path"""
    readonly: builtins.bool
    format: global___DiskConfig.Format.ValueType
    role: global___DiskConfig.DiskRole.ValueType
    def __init__(
        self,
        *,
        path: builtins.str = ...,
        readonly: builtins.bool = ...,
        format: global___DiskConfig.Format.ValueType = ...,
        role: global___DiskConfig.DiskRole.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["format", b"format", "path", b"path", "readonly", b"readonly", "role", b"role"]) -> None: ...

global___DiskConfig = DiskConfig

@typing.final
class TeeConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BACKEND_FIELD_NUMBER: builtins.int
    POLICY_FIELD_NUMBER: builtins.int
    SESSION_DIR_FIELD_NUMBER: builtins.int
    FIRMWARE_PATH_FIELD_NUMBER: builtins.int
    KERNEL_CMDLINE_FIELD_NUMBER: builtins.int
    CPU_MODEL_FIELD_NUMBER: builtins.int
    backend: global___TeeBackend.ValueType
    """attestation backend (orthogonal to the top-level Backend enum, which selects the VMM)"""
    policy: builtins.str
    """empty = default"""
    session_dir: builtins.str
    """confidential session files"""
    firmware_path: builtins.str
    """resolved OVMF blob path (empty = none)"""
    kernel_cmdline: builtins.str
    """Opaque measured guest kernel cmdline, rendered by the agent from the
    runtime manifest's template. When set (SEV-SNP only), the daemon passes
    it to QEMU verbatim and never parses it; it is mutually exclusive with
    the sidecar-derived verity cmdline. Empty = unset.
    """
    cpu_model: builtins.str
    """QEMU CPU model for a measured SEV-SNP launch (e.g. "EPYC-v4"). The agent
    picks it from the message's launch measurements, intersected with what
    this host's QEMU can launch; it IS a measurement input (per-vCPU VMSA),
    so the supervisor passes it through verbatim. Empty = "EPYC-v4", which is
    what controller configs written before this field imply.
    """
    def __init__(
        self,
        *,
        backend: global___TeeBackend.ValueType = ...,
        policy: builtins.str = ...,
        session_dir: builtins.str = ...,
        firmware_path: builtins.str = ...,
        kernel_cmdline: builtins.str = ...,
        cpu_model: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["backend", b"backend", "cpu_model", b"cpu_model", "firmware_path", b"firmware_path", "kernel_cmdline", b"kernel_cmdline", "policy", b"policy", "session_dir", b"session_dir"]) -> None: ...

global___TeeConfig = TeeConfig

@typing.final
class NetworkConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INTERNET_ACCESS_FIELD_NUMBER: builtins.int
    REQUESTED_IPV6_FIELD_NUMBER: builtins.int
    IPV6_PREFIX_LEN_FIELD_NUMBER: builtins.int
    internet_access: builtins.bool
    requested_ipv6: builtins.str
    """agent-computed static /124 CIDR (network/prefix); empty = daemon-assigned"""
    ipv6_prefix_len: builtins.int
    """the requested prefix (124 for the static scheme); 0 = /128"""
    def __init__(
        self,
        *,
        internet_access: builtins.bool = ...,
        requested_ipv6: builtins.str = ...,
        ipv6_prefix_len: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["internet_access", b"internet_access", "ipv6_prefix_len", b"ipv6_prefix_len", "requested_ipv6", b"requested_ipv6"]) -> None: ...

global___NetworkConfig = NetworkConfig

@typing.final
class GpuConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PCI_HOST_FIELD_NUMBER: builtins.int
    SUPPORTS_X_VGA_FIELD_NUMBER: builtins.int
    pci_host: builtins.str
    """resolved concrete address, always set"""
    supports_x_vga: builtins.bool
    def __init__(
        self,
        *,
        pci_host: builtins.str = ...,
        supports_x_vga: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pci_host", b"pci_host", "supports_x_vga", b"supports_x_vga"]) -> None: ...

global___GpuConfig = GpuConfig

@typing.final
class IpAssignment(google.protobuf.message.Message):
    """One address family's assignment for a VM. All fields are empty until the
    underlying tap device exists.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    NETWORK_CIDR_FIELD_NUMBER: builtins.int
    GATEWAY_FIELD_NUMBER: builtins.int
    address: builtins.str
    """the guest's address, bare IP"""
    network_cidr: builtins.str
    """the tap network, e.g. "172.16.3.0/24" """
    gateway: builtins.str
    """host-side tap address (bare IP); the guest's default route"""
    def __init__(
        self,
        *,
        address: builtins.str = ...,
        network_cidr: builtins.str = ...,
        gateway: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "gateway", b"gateway", "network_cidr", b"network_cidr"]) -> None: ...

global___IpAssignment = IpAssignment

@typing.final
class VmInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    IPV4_FIELD_NUMBER: builtins.int
    IPV6_FIELD_NUMBER: builtins.int
    UPTIME_SECS_FIELD_NUMBER: builtins.int
    BACKEND_FIELD_NUMBER: builtins.int
    NUMA_NODE_FIELD_NUMBER: builtins.int
    STATUS_MESSAGE_FIELD_NUMBER: builtins.int
    DEFINED_AT_NS_FIELD_NUMBER: builtins.int
    PREPARING_AT_NS_FIELD_NUMBER: builtins.int
    PREPARED_AT_NS_FIELD_NUMBER: builtins.int
    STARTING_AT_NS_FIELD_NUMBER: builtins.int
    STARTED_AT_NS_FIELD_NUMBER: builtins.int
    STOPPING_AT_NS_FIELD_NUMBER: builtins.int
    STOPPED_AT_NS_FIELD_NUMBER: builtins.int
    CONFIDENTIAL_MODE_FIELD_NUMBER: builtins.int
    GPUS_FIELD_NUMBER: builtins.int
    GUEST_CHANNEL_PATH_FIELD_NUMBER: builtins.int
    GUEST_READY_PAYLOAD_FIELD_NUMBER: builtins.int
    AWAITING_CONFIDENTIAL_INIT_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    status: global___VmStatus.ValueType
    uptime_secs: builtins.int
    backend: global___Backend.ValueType
    numa_node: builtins.int
    """effective placement (0-indexed). Unset until status is BOOTING/RUNNING."""
    status_message: builtins.str
    """human-readable, optional"""
    defined_at_ns: builtins.int
    """Lifecycle timestamps, unix nanoseconds UTC. 0 = stage not reached."""
    preparing_at_ns: builtins.int
    prepared_at_ns: builtins.int
    starting_at_ns: builtins.int
    started_at_ns: builtins.int
    stopping_at_ns: builtins.int
    stopped_at_ns: builtins.int
    confidential_mode: global___ConfidentialMode.ValueType
    """precise TEE mode; NONE for non-confidential VMs"""
    guest_channel_path: builtins.str
    """Host UDS endpoint of the guest control channel (see
    VmSpec.guest_channel). The client dials it for guest-level
    protocols and binds `<path>_<port>` listeners for guest-initiated
    connections. Empty when the VM was created without a channel.
    """
    guest_ready_payload: builtins.bytes
    """Raw bytes the guest sent with its ready signal, passed through opaquely;
    empty until the signal arrived (or for VMs without a channel). The client
    interprets them (the Aleph runtime sends its version handshake here).
    """
    awaiting_confidential_init: builtins.bool
    """True while a confidential VM is started but waiting for its owner to upload
    the session certificates: not running, but not dead either. The client
    lists such VMs so the scheduler does not re-allocate them forever.
    """
    @property
    def ipv4(self) -> global___IpAssignment: ...
    @property
    def ipv6(self) -> global___IpAssignment: ...
    @property
    def gpus(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GpuDevice]:
        """exact PCI devices attached to this VM (mirrors HostInfo.gpus)"""

    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        status: global___VmStatus.ValueType = ...,
        ipv4: global___IpAssignment | None = ...,
        ipv6: global___IpAssignment | None = ...,
        uptime_secs: builtins.int = ...,
        backend: global___Backend.ValueType = ...,
        numa_node: builtins.int | None = ...,
        status_message: builtins.str = ...,
        defined_at_ns: builtins.int = ...,
        preparing_at_ns: builtins.int = ...,
        prepared_at_ns: builtins.int = ...,
        starting_at_ns: builtins.int = ...,
        started_at_ns: builtins.int = ...,
        stopping_at_ns: builtins.int = ...,
        stopped_at_ns: builtins.int = ...,
        confidential_mode: global___ConfidentialMode.ValueType = ...,
        gpus: collections.abc.Iterable[global___GpuDevice] | None = ...,
        guest_channel_path: builtins.str = ...,
        guest_ready_payload: builtins.bytes = ...,
        awaiting_confidential_init: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_numa_node", b"_numa_node", "ipv4", b"ipv4", "ipv6", b"ipv6", "numa_node", b"numa_node"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_numa_node", b"_numa_node", "awaiting_confidential_init", b"awaiting_confidential_init", "backend", b"backend", "confidential_mode", b"confidential_mode", "defined_at_ns", b"defined_at_ns", "gpus", b"gpus", "guest_channel_path", b"guest_channel_path", "guest_ready_payload", b"guest_ready_payload", "ipv4", b"ipv4", "ipv6", b"ipv6", "numa_node", b"numa_node", "prepared_at_ns", b"prepared_at_ns", "preparing_at_ns", b"preparing_at_ns", "started_at_ns", b"started_at_ns", "starting_at_ns", b"starting_at_ns", "status", b"status", "status_message", b"status_message", "stopped_at_ns", b"stopped_at_ns", "stopping_at_ns", b"stopping_at_ns", "uptime_secs", b"uptime_secs", "vm_id", b"vm_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_numa_node", b"_numa_node"]) -> typing.Literal["numa_node"] | None: ...

global___VmInfo = VmInfo

@typing.final
class GetVmRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

global___GetVmRequest = GetVmRequest

@typing.final
class GetVmSpecRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

global___GetVmSpecRequest = GetVmSpecRequest

@typing.final
class StopVmRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

global___StopVmRequest = StopVmRequest

@typing.final
class StartVmRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

global___StartVmRequest = StartVmRequest

@typing.final
class ListVmsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ListVmsRequest = ListVmsRequest

@typing.final
class ListVmsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VMS_FIELD_NUMBER: builtins.int
    @property
    def vms(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___VmInfo]: ...
    def __init__(
        self,
        *,
        vms: collections.abc.Iterable[global___VmInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vms", b"vms"]) -> None: ...

global___ListVmsResponse = ListVmsResponse

@typing.final
class DeleteVmRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    KEEP_PORT_MAPPINGS_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    keep_port_mappings: builtins.bool
    """the delete is part of a delete+recreate cycle: preserve persisted"""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        keep_port_mappings: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["keep_port_mappings", b"keep_port_mappings", "vm_id", b"vm_id"]) -> None: ...

global___DeleteVmRequest = DeleteVmRequest

@typing.final
class DeleteVmResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DeleteVmResponse = DeleteVmResponse

@typing.final
class RebootVmRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    """Note: aleph-vm performs soft reboot only today: systemd restart for
    persistent VMs; for ephemeral spec-created VMs the supervisor stops the
    VM and recreates it from the spec it holds. Firecracker has no reboot
    API. Add a `hard` option when a real implementation lands.
    """
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

global___RebootVmRequest = RebootVmRequest

@typing.final
class RunProgramCodeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    SCOPE_MSGPACK_FIELD_NUMBER: builtins.int
    TIMEOUT_SECS_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    scope_msgpack: builtins.bytes
    """ASGI scope dict, msgpack-encoded"""
    timeout_secs: builtins.float
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        scope_msgpack: builtins.bytes = ...,
        timeout_secs: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["scope_msgpack", b"scope_msgpack", "timeout_secs", b"timeout_secs", "vm_id", b"vm_id"]) -> None: ...

global___RunProgramCodeRequest = RunProgramCodeRequest

@typing.final
class RunProgramCodeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPLY_FIELD_NUMBER: builtins.int
    reply: builtins.bytes
    """raw runtime reply, opaque to the supervisor"""
    def __init__(
        self,
        *,
        reply: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["reply", b"reply"]) -> None: ...

global___RunProgramCodeResponse = RunProgramCodeResponse

@typing.final
class WatchEventsRequest(google.protobuf.message.Message):
    """── Events ───────────────────────────────────────────────────────────────"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___WatchEventsRequest = WatchEventsRequest

@typing.final
class VmEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    OLD_STATUS_FIELD_NUMBER: builtins.int
    NEW_STATUS_FIELD_NUMBER: builtins.int
    TIMESTAMP_NS_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    old_status: global___VmStatus.ValueType
    new_status: global___VmStatus.ValueType
    timestamp_ns: builtins.int
    """unix ns UTC at emission"""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        old_status: global___VmStatus.ValueType = ...,
        new_status: global___VmStatus.ValueType = ...,
        timestamp_ns: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["new_status", b"new_status", "old_status", b"old_status", "timestamp_ns", b"timestamp_ns", "vm_id", b"vm_id"]) -> None: ...

global___VmEvent = VmEvent

@typing.final
class AddPortForwardRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    HOST_PORT_FIELD_NUMBER: builtins.int
    VM_PORT_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    host_port: builtins.int
    """0 = auto-allocate"""
    vm_port: builtins.int
    protocol: global___Protocol.ValueType
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        host_port: builtins.int = ...,
        vm_port: builtins.int = ...,
        protocol: global___Protocol.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["host_port", b"host_port", "protocol", b"protocol", "vm_id", b"vm_id", "vm_port", b"vm_port"]) -> None: ...

global___AddPortForwardRequest = AddPortForwardRequest

@typing.final
class PortForwardInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    HOST_PORT_FIELD_NUMBER: builtins.int
    VM_PORT_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    host_port: builtins.int
    vm_port: builtins.int
    protocol: global___Protocol.ValueType
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        host_port: builtins.int = ...,
        vm_port: builtins.int = ...,
        protocol: global___Protocol.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["host_port", b"host_port", "protocol", b"protocol", "vm_id", b"vm_id", "vm_port", b"vm_port"]) -> None: ...

global___PortForwardInfo = PortForwardInfo

@typing.final
class RemovePortForwardRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    HOST_PORT_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    host_port: builtins.int
    protocol: global___Protocol.ValueType
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        host_port: builtins.int = ...,
        protocol: global___Protocol.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["host_port", b"host_port", "protocol", b"protocol", "vm_id", b"vm_id"]) -> None: ...

global___RemovePortForwardRequest = RemovePortForwardRequest

@typing.final
class RemovePortForwardResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RemovePortForwardResponse = RemovePortForwardResponse

@typing.final
class ListPortForwardsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    """empty = all VMs"""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

global___ListPortForwardsRequest = ListPortForwardsRequest

@typing.final
class ListPortForwardsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FORWARDS_FIELD_NUMBER: builtins.int
    @property
    def forwards(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PortForwardInfo]: ...
    def __init__(
        self,
        *,
        forwards: collections.abc.Iterable[global___PortForwardInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["forwards", b"forwards"]) -> None: ...

global___ListPortForwardsResponse = ListPortForwardsResponse

@typing.final
class GetLogsRequest(google.protobuf.message.Message):
    """── Logs ─────────────────────────────────────────────────────────────────"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    MAX_LINES_FIELD_NUMBER: builtins.int
    FROM_TAIL_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    max_lines: builtins.int
    """0 = unlimited (subject to server cap)"""
    from_tail: builtins.bool
    """true = most recent lines"""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        max_lines: builtins.int = ...,
        from_tail: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["from_tail", b"from_tail", "max_lines", b"max_lines", "vm_id", b"vm_id"]) -> None: ...

global___GetLogsRequest = GetLogsRequest

@typing.final
class GetLogsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LINES_FIELD_NUMBER: builtins.int
    @property
    def lines(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LogChunk]: ...
    def __init__(
        self,
        *,
        lines: collections.abc.Iterable[global___LogChunk] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["lines", b"lines"]) -> None: ...

global___GetLogsResponse = GetLogsResponse

@typing.final
class StreamLogsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    INCLUDE_HISTORY_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    include_history: builtins.bool
    """false = only new lines from now"""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        include_history: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["include_history", b"include_history", "vm_id", b"vm_id"]) -> None: ...

global___StreamLogsRequest = StreamLogsRequest

@typing.final
class LogChunk(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _LogSource:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _LogSourceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LogChunk._LogSource.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        LOG_SOURCE_UNSPECIFIED: LogChunk._LogSource.ValueType  # 0
        LOG_SOURCE_SERIAL: LogChunk._LogSource.ValueType  # 1
        """QEMU serial console"""
        LOG_SOURCE_STDOUT: LogChunk._LogSource.ValueType  # 2
        """Firecracker vm-stdout"""
        LOG_SOURCE_SYSTEMD: LogChunk._LogSource.ValueType  # 3
        """systemd journal for persistent VM unit"""
        LOG_SOURCE_STDERR: LogChunk._LogSource.ValueType  # 4
        """vm-stderr journal identifier"""

    class LogSource(_LogSource, metaclass=_LogSourceEnumTypeWrapper): ...
    LOG_SOURCE_UNSPECIFIED: LogChunk.LogSource.ValueType  # 0
    LOG_SOURCE_SERIAL: LogChunk.LogSource.ValueType  # 1
    """QEMU serial console"""
    LOG_SOURCE_STDOUT: LogChunk.LogSource.ValueType  # 2
    """Firecracker vm-stdout"""
    LOG_SOURCE_SYSTEMD: LogChunk.LogSource.ValueType  # 3
    """systemd journal for persistent VM unit"""
    LOG_SOURCE_STDERR: LogChunk.LogSource.ValueType  # 4
    """vm-stderr journal identifier"""

    TIMESTAMP_NS_FIELD_NUMBER: builtins.int
    LINE_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    timestamp_ns: builtins.int
    """unix ns at server-side capture time"""
    line: builtins.str
    """single log line, no trailing newline"""
    source: global___LogChunk.LogSource.ValueType
    def __init__(
        self,
        *,
        timestamp_ns: builtins.int = ...,
        line: builtins.str = ...,
        source: global___LogChunk.LogSource.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["line", b"line", "source", b"source", "timestamp_ns", b"timestamp_ns"]) -> None: ...

global___LogChunk = LogChunk

@typing.final
class FreezeGuestRequest(google.protobuf.message.Message):
    """── Guest quiescence ─────────────────────────────────────────────────────"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

global___FreezeGuestRequest = FreezeGuestRequest

@typing.final
class FreezeGuestResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FROZEN_FIELD_NUMBER: builtins.int
    frozen: builtins.bool
    """false: guest agent unavailable, nothing frozen"""
    def __init__(
        self,
        *,
        frozen: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["frozen", b"frozen"]) -> None: ...

global___FreezeGuestResponse = FreezeGuestResponse

@typing.final
class ThawGuestRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

global___ThawGuestRequest = ThawGuestRequest

@typing.final
class ThawGuestResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ThawGuestResponse = ThawGuestResponse

@typing.final
class InitializeConfidentialRequest(google.protobuf.message.Message):
    """── Confidential ─────────────────────────────────────────────────────────"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    SESSION_BYTES_FIELD_NUMBER: builtins.int
    GODH_BYTES_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    session_bytes: builtins.bytes
    """SEV session blob"""
    godh_bytes: builtins.bytes
    """SEV guest-owner DH key"""
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        session_bytes: builtins.bytes = ...,
        godh_bytes: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["godh_bytes", b"godh_bytes", "session_bytes", b"session_bytes", "vm_id", b"vm_id"]) -> None: ...

global___InitializeConfidentialRequest = InitializeConfidentialRequest

@typing.final
class InitializeConfidentialResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___InitializeConfidentialResponse = InitializeConfidentialResponse

@typing.final
class GetMeasurementRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vm_id", b"vm_id"]) -> None: ...

global___GetMeasurementRequest = GetMeasurementRequest

@typing.final
class SevInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLED_FIELD_NUMBER: builtins.int
    API_MAJOR_FIELD_NUMBER: builtins.int
    API_MINOR_FIELD_NUMBER: builtins.int
    BUILD_ID_FIELD_NUMBER: builtins.int
    POLICY_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    HANDLE_FIELD_NUMBER: builtins.int
    enabled: builtins.bool
    api_major: builtins.int
    api_minor: builtins.int
    build_id: builtins.int
    policy: builtins.int
    state: builtins.str
    handle: builtins.int
    def __init__(
        self,
        *,
        enabled: builtins.bool = ...,
        api_major: builtins.int = ...,
        api_minor: builtins.int = ...,
        build_id: builtins.int = ...,
        policy: builtins.int = ...,
        state: builtins.str = ...,
        handle: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["api_major", b"api_major", "api_minor", b"api_minor", "build_id", b"build_id", "enabled", b"enabled", "handle", b"handle", "policy", b"policy", "state", b"state"]) -> None: ...

global___SevInfo = SevInfo

@typing.final
class Measurement(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    MEASUREMENT_BYTES_FIELD_NUMBER: builtins.int
    TEE_BACKEND_FIELD_NUMBER: builtins.int
    SEV_INFO_FIELD_NUMBER: builtins.int
    LAUNCH_MEASURE_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    measurement_bytes: builtins.bytes
    """attestation report / SEV launch measure"""
    tee_backend: global___TeeBackend.ValueType
    launch_measure: builtins.str
    """base64 launch measurement"""
    @property
    def sev_info(self) -> global___SevInfo:
        """present for SEV launches"""

    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        measurement_bytes: builtins.bytes = ...,
        tee_backend: global___TeeBackend.ValueType = ...,
        sev_info: global___SevInfo | None = ...,
        launch_measure: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["sev_info", b"sev_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["launch_measure", b"launch_measure", "measurement_bytes", b"measurement_bytes", "sev_info", b"sev_info", "tee_backend", b"tee_backend", "vm_id", b"vm_id"]) -> None: ...

global___Measurement = Measurement

@typing.final
class InjectSecretRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VM_ID_FIELD_NUMBER: builtins.int
    SECRET_HEADER_BYTES_FIELD_NUMBER: builtins.int
    SECRET_BYTES_FIELD_NUMBER: builtins.int
    vm_id: builtins.str
    secret_header_bytes: builtins.bytes
    secret_bytes: builtins.bytes
    def __init__(
        self,
        *,
        vm_id: builtins.str = ...,
        secret_header_bytes: builtins.bytes = ...,
        secret_bytes: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["secret_bytes", b"secret_bytes", "secret_header_bytes", b"secret_header_bytes", "vm_id", b"vm_id"]) -> None: ...

global___InjectSecretRequest = InjectSecretRequest

@typing.final
class InjectSecretResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___InjectSecretResponse = InjectSecretResponse

@typing.final
class RecreateNetworkRequest(google.protobuf.message.Message):
    """── Network ──────────────────────────────────────────────────────────────"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RecreateNetworkRequest = RecreateNetworkRequest

@typing.final
class RecreateNetworkResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUMMARY_JSON_FIELD_NUMBER: builtins.int
    summary_json: builtins.str
    """JSON-encoded summary dict from the engine"""
    def __init__(
        self,
        *,
        summary_json: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["summary_json", b"summary_json"]) -> None: ...

global___RecreateNetworkResponse = RecreateNetworkResponse

@typing.final
class ErrorDetail(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    VM_ID_FIELD_NUMBER: builtins.int
    code: global___ErrorCode.ValueType
    message: builtins.str
    """human-readable, agent surfaces verbatim"""
    vm_id: builtins.str
    """optional context"""
    def __init__(
        self,
        *,
        code: global___ErrorCode.ValueType = ...,
        message: builtins.str = ...,
        vm_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "message", b"message", "vm_id", b"vm_id"]) -> None: ...

global___ErrorDetail = ErrorDetail
